package windowsmanaged

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"reflect"
	"strings"
	"testing"
	"time"
)

const startupTestGeneration = "sample_0123456789abcdef0123456789abcdef"
const startupTestGrant = "0123456789abcdef0123456789abcdef"

var startupTestAt = time.Date(2026, 10, 8, 12, 0, 0, 0, time.UTC)

func startupTestServices() []Service {
	return []Service{{Name: "alpha", DisplayName: "Alpha", State: "running", PID: 42}, {Name: "beta", DisplayName: "Beta", State: "stopped", PID: 0}}
}
func startupTestRow(mode string, delayed *bool) ServiceStartupRow {
	r := ServiceStartupRow{StartupMode: &mode, StartupQuality: "observed", DelayedAutoStart: delayed, DelayedAutoQuality: "not-applicable"}
	if mode == "automatic" {
		r.DelayedAutoQuality = "observed"
	}
	return r
}
func startupTestSnapshot() ServiceStartupSnapshot {
	services := startupTestServices()
	digest, _ := ServiceStartupRowsSHA256(services)
	b := false
	rows := []ServiceStartupRow{startupTestRow("automatic", &b), startupTestRow("manual", nil)}
	rows[1].ServiceIndex = 1
	return ServiceStartupSnapshot{SchemaVersion: ServiceStartupSchemaVersion, Scope: ServiceStartupScope, GrantID: startupTestGrant, GenerationID: startupTestGeneration, ServicesSHA256: digest, CollectedAt: startupTestAt, RequestedCount: 2, Rows: rows}
}

func TestServiceStartupConsentCanonicalAndIndependent(t *testing.T) {
	binding := strings.Repeat("a", 64)
	c := ServiceStartupConsent{ServiceStartupConsentVersion, ServiceStartupScope, binding, startupTestGrant, false}
	raw, err := EncodeServiceStartupConsent(c, binding)
	if err != nil {
		t.Fatal(err)
	}
	got, err := DecodeServiceStartupConsent(raw, binding)
	if err != nil || got != c || got.Enabled {
		t.Fatal(got, err)
	}
	for _, bad := range [][]byte{
		bytes.Replace(raw, []byte(ServiceStartupScope), []byte(CollectionProfile), 1),
		bytes.Replace(raw, []byte(ServiceStartupConsentVersion), []byte("tracebolt.windows-inventory-consent.v1"), 1),
		bytes.Replace(raw, []byte(`"enabled":false`), []byte(`"enabled":null`), 1),
		bytes.Replace(raw, []byte(`"enabled":false`), []byte(`"enabled":false,"enabled":false`), 1),
		bytes.Replace(raw, []byte(`,"enabled":false`), nil, 1),
		append(append([]byte{}, raw...), '\n'),
	} {
		if _, err := DecodeServiceStartupConsent(bad, binding); !errors.Is(err, ErrServiceStartupInvalid) {
			t.Fatalf("accepted %s: %v", bad, err)
		}
	}
	if _, err := DecodeServiceStartupConsent(raw, strings.Repeat("b", 64)); err == nil {
		t.Fatal("unbound consent")
	}
	c.Enabled = true
	if _, err := EncodeServiceStartupConsent(c, binding); err != nil {
		t.Fatal(err)
	}
}

func TestServiceStartupRowsDigestExactBase(t *testing.T) {
	rows := startupTestServices()
	digest, err := ServiceStartupRowsSHA256(rows)
	b, _ := json.Marshal(rows)
	expected := sha256.Sum256(b)
	if err != nil || digest != hex.EncodeToString(expected[:]) {
		t.Fatal(digest, err)
	}
	mutations := []func([]Service){
		func(s []Service) { s[0], s[1] = s[1], s[0] },
		func(s []Service) { s[0].Name = "different" },
		func(s []Service) { s[0].DisplayName = "different" },
		func(s []Service) { s[0].State = "stopped" },
		func(s []Service) { s[0].PID++ },
	}
	for _, mutate := range mutations {
		copy := append([]Service{}, rows...)
		mutate(copy)
		changed, err := ServiceStartupRowsSHA256(copy)
		if err != nil || changed == digest {
			t.Fatal("digest failed to bind complete ordered base", err)
		}
	}
	empty, err := ServiceStartupRowsSHA256([]Service{})
	emptyHash := sha256.Sum256([]byte("[]"))
	if err != nil || empty != hex.EncodeToString(emptyHash[:]) {
		t.Fatal(empty, err)
	}
	if _, err := ServiceStartupRowsSHA256(nil); err == nil {
		t.Fatal("nil array accepted")
	}
	if _, err := ServiceStartupRowsSHA256(make([]Service, 129)); err == nil {
		t.Fatal("oversize accepted")
	}
}

// The shared file is generated by this Go test, not a second-language JSON or
// hashing implementation. To deliberately refresh the synthetic fixture, run
// TRACEBOLT_UPDATE_SERVICE_STARTUP_FIXTURE=1 go test ./internal/windowsmanaged
// -run '^TestServiceStartupGoGeneratedDigestFixture$'. Ordinary tests only read.
func TestServiceStartupGoGeneratedDigestFixture(t *testing.T) {
	type vector struct {
		Name          string    `json:"name"`
		Services      []Service `json:"services"`
		CanonicalJSON string    `json:"canonicalJSON"`
		SHA256        string    `json:"sha256"`
		ValidBase     bool      `json:"validBase"`
	}
	unicodeRows := []Service{
		{Name: "Dienst-ä-&<β>", DisplayName: "日本語 🚀 \"quoted\" \\ path", State: "stopped", PID: 0},
		{Name: "Дубликат", DisplayName: "A&B > C", State: "paused", PID: 4294967295},
	}
	duplicate := Service{Name: "same", DisplayName: "duplicate", State: "running", PID: 4}
	cases := []vector{
		{Name: "empty", Services: []Service{}, ValidBase: true},
		{Name: "ascii", Services: []Service{{Name: "FixtureService", DisplayName: "Fixture Service", State: "running", PID: 44}}, ValidBase: true},
		{Name: "unicode-html", Services: unicodeRows, ValidBase: true},
		{Name: "duplicates", Services: []Service{duplicate, duplicate}, ValidBase: true},
		{Name: "canonical-escapes-only", Services: []Service{{Name: "line\u2028separator", DisplayName: "paragraph\u2029separator", State: "running", PID: 1}}, ValidBase: false},
		{Name: "unicode-trimmed", Services: unicodeRows[:1], ValidBase: true},
		{Name: "unicode-reordered", Services: []Service{unicodeRows[1], unicodeRows[0]}, ValidBase: true},
	}
	for i := range cases {
		b, err := json.Marshal(cases[i].Services)
		if err != nil {
			t.Fatal(err)
		}
		sum := sha256.Sum256(b)
		cases[i].CanonicalJSON = string(b)
		cases[i].SHA256 = hex.EncodeToString(sum[:])
		got, err := ServiceStartupRowsSHA256(cases[i].Services)
		if cases[i].ValidBase {
			if err != nil || got != cases[i].SHA256 {
				t.Fatal(cases[i].Name, got, err)
			}
		} else if err == nil {
			t.Fatal("v1-invalid labels accepted")
		}
	}
	want, err := json.MarshalIndent(cases, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	want = append(want, '\n')
	const path = "../../web/src/windows-service-startup-go-fixture.json"
	if os.Getenv("TRACEBOLT_UPDATE_SERVICE_STARTUP_FIXTURE") == "1" {
		if err := os.WriteFile(path, want, 0644); err != nil {
			t.Fatal(err)
		}
	}
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(got, want) {
		t.Fatal("Go-generated shared digest fixture differs; regenerate explicitly and review")
	}
}

func TestServiceStartupExactDecodeAndCoherence(t *testing.T) {
	s := startupTestSnapshot()
	raw, err := EncodeServiceStartup(s)
	if err != nil {
		t.Fatal(err)
	}
	got, err := DecodeServiceStartup(raw)
	if err != nil || !reflect.DeepEqual(got, s) {
		t.Fatal(got, err)
	}
	for name, bad := range map[string][]byte{
		"missing":        bytes.Replace(raw, []byte(`,"truncated":false`), nil, 1),
		"duplicate":      bytes.Replace(raw, []byte(`"requestedCount":2`), []byte(`"requestedCount":2,"requestedCount":2`), 1),
		"unknown":        bytes.Replace(raw, []byte(`"serviceIndex":0`), []byte(`"serviceIndex":0,"path":"private"`), 1),
		"wrong-case":     bytes.Replace(raw, []byte(`"startupMode"`), []byte(`"StartupMode"`), 1),
		"null-count":     bytes.Replace(raw, []byte(`"requestedCount":2`), []byte(`"requestedCount":null`), 1),
		"exponent-index": bytes.Replace(raw, []byte(`"serviceIndex":0`), []byte(`"serviceIndex":0e0`), 1),
		"fraction-index": bytes.Replace(raw, []byte(`"serviceIndex":0`), []byte(`"serviceIndex":0.0`), 1),
		"non-utc":        bytes.Replace(raw, []byte(`2026-10-08T12:00:00Z`), []byte(`2026-10-08T12:00:00+00:00`), 1),
		"negative":       bytes.Replace(raw, []byte(`"serviceIndex":0`), []byte(`"serviceIndex":-1`), 1),
		"trailing":       append(append([]byte{}, raw...), []byte(`{}`)...),
		"null-rows":      bytes.Replace(raw, []byte(`"rows":[`), []byte(`"rows":null,"unused":[`), 1),
		"oversize":       bytes.Repeat([]byte(" "), ServiceStartupMaxBytes+1),
	} {
		t.Run(name, func(t *testing.T) {
			if _, err := DecodeServiceStartup(bad); err == nil {
				t.Fatal("accepted invalid JSON")
			}
		})
	}
	for name, mutate := range map[string]func(*ServiceStartupSnapshot){
		"unknown-mode":      func(s *ServiceStartupSnapshot) { *s.Rows[0].StartupMode = "boot" },
		"unknown-as-manual": func(s *ServiceStartupSnapshot) { s.Rows[1].StartupQuality = "unknown" },
		"nonauto-delayed": func(s *ServiceStartupSnapshot) {
			b := false
			s.Rows[1].DelayedAutoStart = &b
			s.Rows[1].DelayedAutoQuality = "observed"
		},
		"auto-not-applicable": func(s *ServiceStartupSnapshot) {
			s.Rows[0].DelayedAutoStart = nil
			s.Rows[0].DelayedAutoQuality = "not-applicable"
		},
		"denied-value":  func(s *ServiceStartupSnapshot) { s.Rows[0].DelayedAutoQuality = "denied" },
		"missing-value": func(s *ServiceStartupSnapshot) { s.Rows[0].DelayedAutoStart = nil },
		"mismatched-quality": func(s *ServiceStartupSnapshot) {
			s.Rows[0] = serviceStartupFailure("denied")
			s.Rows[0].DelayedAutoQuality = "unknown"
		},
		"duplicate-index":    func(s *ServiceStartupSnapshot) { s.Rows[1].ServiceIndex = 0 },
		"out-of-range-index": func(s *ServiceStartupSnapshot) { s.Rows[1].ServiceIndex = 2 },
		"false-truncation":   func(s *ServiceStartupSnapshot) { s.Truncated = true },
		"missing-truncation": func(s *ServiceStartupSnapshot) { s.RequestedCount = 3 },
		"count-limit":        func(s *ServiceStartupSnapshot) { s.RequestedCount = 129; s.Truncated = true },
		"nil-rows":           func(s *ServiceStartupSnapshot) { s.Rows = nil; s.Truncated = true },
		"hash-case":          func(s *ServiceStartupSnapshot) { s.ServicesSHA256 = strings.ToUpper(s.ServicesSHA256) },
		"bad-grant":          func(s *ServiceStartupSnapshot) { s.GrantID = "a" },
	} {
		t.Run(name, func(t *testing.T) {
			s := startupTestSnapshot()
			mutate(&s)
			if ValidateServiceStartup(s) == nil {
				t.Fatal("accepted inconsistent snapshot")
			}
		})
	}
	for _, quality := range []string{"denied", "unavailable", "unknown"} {
		s := startupTestSnapshot()
		s.Rows[0] = serviceStartupFailure(quality)
		if err := ValidateServiceStartup(s); err != nil {
			t.Fatal(quality, err)
		}
		s = startupTestSnapshot()
		s.Rows[0].DelayedAutoQuality = quality
		s.Rows[0].DelayedAutoStart = nil
		if err := ValidateServiceStartup(s); err != nil {
			t.Fatal(quality, err)
		}
	}
}

func TestServiceStartupBudgetKeepsBindingAndAge(t *testing.T) {
	s := startupTestSnapshot()
	s.RequestedCount = 128
	s.Rows = []ServiceStartupRow{}
	for i := 0; i < 128; i++ {
		row := startupTestRow("automatic", new(bool))
		row.ServiceIndex = uint32(i)
		s.Rows = append(s.Rows, row)
	}
	fitted, err := FitServiceStartupBudget(s, ServiceStartupMaxBytes)
	if err != nil || ValidateServiceStartup(fitted) != nil || !fitted.Truncated || len(fitted.Rows) >= 128 {
		t.Fatal(len(fitted.Rows), err)
	}
	b, _ := json.Marshal(fitted)
	if len(b) > ServiceStartupMaxBytes || fitted.RequestedCount != 128 || fitted.ServicesSHA256 != s.ServicesSHA256 || fitted.CollectedAt != s.CollectedAt || fitted.GenerationID != s.GenerationID || fitted.GrantID != s.GrantID {
		t.Fatal("fitting changed original binding")
	}
	if len(s.Rows) != 128 || s.Truncated {
		t.Fatal("mutated input")
	}
	*fitted.Rows[0].StartupMode = "disabled"
	if *s.Rows[0].StartupMode != "automatic" {
		t.Fatal("shared pointer after fitting")
	}
	if _, err := FitServiceStartupBudget(s, 1); err == nil {
		t.Fatal("impossible budget accepted")
	}
}

func TestServiceStartupCollectionBoundsAndCancellation(t *testing.T) {
	services := startupTestServices()
	reads, clocks := 0, 0
	read := func(_ context.Context, name string) (ServiceStartupRow, error) {
		if name != services[reads].Name {
			t.Fatal("not exact base row")
		}
		reads++
		return startupTestRow("manual", nil), nil
	}
	clock := func() time.Time { clocks++; return startupTestAt.Add(time.Second) }
	s, err := CollectServiceStartupWithReaderAndClock(context.Background(), services, startupTestGeneration, startupTestGrant, startupTestAt, read, clock)
	if err != nil || reads != 2 || clocks != 1 || s.CollectedAt != startupTestAt.Add(time.Second) || s.RequestedCount != 2 || s.Rows[1].ServiceIndex != 1 {
		t.Fatal(s, err, reads, clocks)
	}
	for _, input := range [][]Service{nil, make([]Service, 129), {{Name: "bad\x00name", State: "running"}}} {
		if _, err := CollectServiceStartupWithReaderAndClock(context.Background(), input, startupTestGeneration, startupTestGrant, startupTestAt, read, clock); err == nil {
			t.Fatal("invalid input")
		}
	}
	if reads != 2 || clocks != 1 {
		t.Fatal("input validation performed reads or consulted clock")
	}
	if _, err := CollectServiceStartupWithReaderAndClock(context.Background(), services, startupTestGeneration, startupTestGrant, startupTestAt, read, func() time.Time { return startupTestAt.Add(-time.Second) }); err == nil || reads != 2 {
		t.Fatal("clock regression read or clamped")
	}
	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := CollectServiceStartupWithReaderAndClock(ctx, services, startupTestGeneration, startupTestGrant, startupTestAt, read, clock); !errors.Is(err, context.Canceled) {
		t.Fatal(err)
	}
	ctx, cancel = context.WithCancel(context.Background())
	defer cancel()
	if _, err := CollectServiceStartupWithReaderAndClock(ctx, services, startupTestGeneration, startupTestGrant, startupTestAt, func(context.Context, string) (ServiceStartupRow, error) {
		cancel()
		return startupTestRow("manual", nil), nil
	}, clock); !errors.Is(err, context.Canceled) {
		t.Fatal("caller cancellation lost", err)
	}
	factoryCalls := 0
	factory := func(context.Context) (ServiceStartupReader, func(), error) {
		factoryCalls++
		return read, func() {}, nil
	}
	s, err = collectServiceStartupUsing(context.Background(), services, startupTestGeneration, startupTestGrant, startupTestAt, factory, 0, clock)
	if err != nil || factoryCalls != 0 || len(s.Rows) != 2 || s.Rows[0].StartupQuality != "unavailable" {
		t.Fatal("expired budget queried native or lost row", s, err)
	}
	closed, attempts := 0, 0
	factory = func(context.Context) (ServiceStartupReader, func(), error) {
		return func(ctx context.Context, _ string) (ServiceStartupRow, error) {
			attempts++
			<-ctx.Done()
			return startupTestRow("manual", nil), nil
		}, func() { closed++ }, nil
	}
	s, err = collectServiceStartupUsing(context.Background(), services, startupTestGeneration, startupTestGrant, startupTestAt, factory, time.Millisecond, clock)
	if err != nil || closed != 1 || attempts != 1 || s.Rows[0].StartupQuality != "unavailable" || s.Rows[1].StartupQuality != "unavailable" {
		t.Fatal("cooperative exhaustion", s, err, closed, attempts)
	}
}

func TestServiceStartupFailuresAreFiniteAndEmptyDoesNotRead(t *testing.T) {
	clock := func() time.Time { return startupTestAt }
	for _, err := range []error{ErrServiceStartupDenied, ErrServiceStartupUnsupported, errors.New("private path C:\\secret; account password")} {
		s, e := CollectServiceStartupWithReaderAndClock(context.Background(), startupTestServices(), startupTestGeneration, startupTestGrant, startupTestAt, func(context.Context, string) (ServiceStartupRow, error) { return ServiceStartupRow{}, err }, clock)
		if e != nil || ValidateServiceStartup(s) != nil {
			t.Fatal(s, e)
		}
		want := "unavailable"
		if err == ErrServiceStartupDenied {
			want = "denied"
		}
		if s.Rows[0].StartupQuality != want {
			t.Fatal(s)
		}
		b, _ := json.Marshal(s)
		if bytes.Contains(b, []byte("secret")) || bytes.Contains(b, []byte("password")) {
			t.Fatal("unsanitized error")
		}
	}
	factory := func(context.Context) (ServiceStartupReader, func(), error) {
		t.Fatal("empty array invoked factory")
		return nil, nil, nil
	}
	s, err := collectServiceStartupUsing(context.Background(), []Service{}, startupTestGeneration, startupTestGrant, startupTestAt, factory, serviceStartupCollectionBudget, clock)
	if err != nil || s.RequestedCount != 0 || s.Rows == nil || s.Truncated || ValidateServiceStartup(s) != nil {
		t.Fatal(s, err)
	}
}

func FuzzDecodeServiceStartup(f *testing.F) {
	b, _ := EncodeServiceStartup(startupTestSnapshot())
	f.Add(b)
	f.Add([]byte(`{"schemaVersion":"tracebolt.windows-service-startup.v1"}`))
	f.Fuzz(func(t *testing.T, raw []byte) {
		s, err := DecodeServiceStartup(raw)
		if err != nil {
			return
		}
		if err := ValidateServiceStartup(s); err != nil {
			t.Fatal("decoded invalid snapshot", err)
		}
		encoded, err := EncodeServiceStartup(s)
		if err != nil || !bytes.Equal(encoded, raw) {
			t.Fatal("noncanonical bytes admitted", err)
		}
	})
}
