package setupgate

// RetentionFailureStages identify bounded controller checks; none is a success state.
var RetentionFailureStages = []string{
	"retention-baseline-owned",
	"retention-baseline-material",
	"retention-baseline-receipt",
	"retention-baseline-runtime",
	"retention-baseline-enrollment",
	"retention-baseline-identity",
	"retention-stopped-receipt",
	"retention-stopped-runtime",
	"retention-stopped-enrollment",
	"retention-stopped-identity",
	"verify-retention-receipt",
	"verify-retention-runtime",
	"verify-retention-enrollment",
	"verify-retention-identity",
	"retention-stopped-event-grant",
	"retention-stopped-volume-grant",
	"retention-stopped-process-grant",
	"retention-stopped-network-grant",
	"retention-stopped-sender",
	"verify-retention-event-grant",
	"verify-retention-volume-grant",
	"verify-retention-process-grant",
	"verify-retention-network-grant",
	"verify-retention-sender",
	"verify-retention-binary",
	"verify-retention-tree",
	"retention-baseline-immutable-unchanged",
	"retention-stopped-immutable-unchanged",
	"verify-retention-immutable-unchanged",
	"verify-retention-stopped-unchanged",
}
