/** Exact-source real-handler acceptance using invented loopback observations.
 * No native collection, APT, model calls, external catalog or TLS bypass.
 */
import {createRequire} from 'node:module';
import {spawn,execFileSync} from 'node:child_process';
import {createInterface} from 'node:readline';
import {randomBytes,createHash} from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const require=createRequire(path.join(root,'web/package.json'));
const {chromium,expect}=require('@playwright/test');
const out=path.join(root,'artifacts/review');await fs.mkdir(out,{recursive:true});
const temporary=await fs.mkdtemp(path.join(os.tmpdir(),'tracebolt-conditional-browser-'));
const sourceSha=process.env.TRACEBOLT_SOURCE_SHA||null;
const applicationBaselineArchiveSha256='b3acbd80ba33e173f6425256c75ed1f372c9ea7ff2c9e516e5e937aaf5937d9b';
const base=`http://127.0.0.1:${Number(process.env.CONDITIONAL_REVIEW_PORT||19892)}`;
const password='TRACEBOLT_CONDITIONAL_BROWSER_FIXTURE_NOT_A_REAL_PASSWORD';
const apiSmoke=process.argv.includes('--api-smoke');
const lifecycleRepeats=Number(process.env.TRACEBOLT_REVIEW_LIFECYCLE_REPEATS||1);
let collectDiagnostics=null;
async function diagnosticDetails(){if(!collectDiagnostics)return{};try{return{diagnostics:await collectDiagnostics()};}catch{return{diagnostics:{unavailable:true}};}}
const results=[],screenshots=[];let browser,server,context,pipe,waiting,devices,currentTest='',stage='setup',runtimeErrorCount=0,fatal=false;
const mark=value=>{stage=value;};
const rid=()=>`request_${randomBytes(16).toString('hex')}`;
const catalog=(synthetic=false,fixedVersion='2.0-1')=>({schema:'debian-tracker-normalized-1',synthetic,coveredSources:['qa-fixture-source'],rules:[{sourcePackage:'qa-fixture-source',advisoryId:'CVE-2099-99990001',release:'trixie',status:'resolved',fixedVersion,qualifications:['no-dsa'],archiveVersions:[]}]});
async function stop(){if(server&&server.exitCode===null){const end=new Promise(r=>server.once('exit',r));server.stdin.end();await Promise.race([end,new Promise(r=>setTimeout(r,1500))]);if(server.exitCode===null){server.kill('SIGTERM');await end;}}pipe?.close();server=null;waiting=null;}
async function control(action,extra={}){if(waiting)throw new Error('CONTROL_CONCURRENCY');const pending=new Promise((resolve,reject)=>waiting={resolve,reject});server.stdin.write(JSON.stringify({action,...extra})+'\n');const answer=await pending;expect(answer.ok).toBe(true);return answer;}
async function start(){const dir=await fs.mkdtemp(path.join(temporary,'state-'));server=spawn(path.join(temporary,'conditionalfixture'),['--listen',new URL(base).host,'--state',dir,'--web',path.join(root,'web/dist')],{cwd:root,stdio:['pipe','pipe','ignore']});pipe=createInterface({input:server.stdout});pipe.on('line',line=>{const cb=waiting;waiting=null;if(cb){try{cb.resolve(JSON.parse(line));}catch{cb.reject(new Error('CONTROL_RESPONSE'));}}});server.on('exit',()=>{waiting?.reject(new Error('FIXTURE_EXITED'));waiting=null;});devices=(await control('info')).devices;}
async function pageAt(route='/devices',{mobile=false,locale='en'}={}){context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},locale:'en-GB'});if(locale==='de')await context.addInitScript(()=>localStorage.setItem('tracebolt.locale','de'));const page=await context.newPage();page.on('pageerror',()=>runtimeErrorCount++);await page.goto(`${base}/#${route}`);await page.getByLabel(locale==='de'?'Operator-Passwort':'Operator password',{exact:true}).fill(password);await page.getByRole('button',{name:locale==='de'?'Anmelden':'Sign in',exact:true}).click();await expect(page.locator('.app-shell')).toBeVisible();return page;}
async function get(route){const response=await context.request.get(base+route);expect(response.status()).toBe(200);return response.json();}
async function post(route,data,extra={}){const auth=await get('/api/auth/session');return context.request.post(base+route,{headers:{Origin:base,'X-CSRF-Token':auth.csrfToken,...extra},data});}
async function importCatalog(value=catalog()){const before=await get('/api/security/catalog');const response=await post('/api/security/catalog',value,{'X-Tracebolt-Catalog-Revision':before.revision});expect(response.status()).toBe(200);return response.json();}
async function openDevice(page,label='alpha',tab='Inventory'){mark('open device panel');await page.goto(`${base}/#/devices/${devices[label]}`);await expect(page.getByRole('region',{name:`Device QA synthetic fixture ${label}`,exact:true})).toBeVisible();await expect(page.locator('.inventory-panel,.enrollment-panel')).toHaveCount(0);await page.getByRole('tab',{name:tab,exact:true}).click();if(tab==='Inventory')await page.getByRole('tablist',{name:'Inventory source',exact:true}).getByRole('tab',{name:'Bounded preview',exact:true}).click();}
async function packages(page){await page.getByRole('button',{name:'Release and source-package observations',exact:true}).click();await expect(page.locator('.package-observations')).toHaveAttribute('aria-busy','false');}
async function review(page){await page.getByRole('button',{name:'Conditional advisory review candidates',exact:true}).click();await expect(page.locator('.advisory-review')).toHaveAttribute('aria-busy','false');}
async function selectCatalog(page,value){const disclosure=page.locator('.security-import');if(await disclosure.getAttribute('open')===null)await disclosure.locator('summary').click();await page.getByLabel('Choose JSON file',{exact:true}).setInputFiles({name:'synthetic-qa-catalog.json',mimeType:'application/json',buffer:Buffer.from(typeof value==='string'?value:JSON.stringify(value))});}
async function expectCatalogSelectionCleared(page){const disclosure=page.locator('.security-import');await expect(disclosure).toBeVisible();if(await disclosure.getAttribute('open')===null)await disclosure.locator('summary').click();const replace=page.getByRole('button',{name:'Replace current catalog',exact:true});await expect(replace).toBeVisible();await expect(replace).toBeDisabled();await expect(page.getByLabel('Choose JSON file',{exact:true})).toHaveValue('');}
async function unknownCoverage(page){await expect(page.locator('.security-metric .security-unknown')).toHaveCount(2);await expect(page.locator('.security-metric .security-unknown').nth(0)).toHaveText('Unknown');await expect(page.locator('.security-metric .security-unknown').nth(1)).toHaveText('Unknown');}
async function shot(page,name){mark('safe synthetic viewport capture');await expect(page.locator('.enrollment-secret')).toHaveCount(0);await expect(page.getByLabel('Operator password',{exact:true})).toHaveCount(0);const text=await page.evaluate(()=>document.body.innerText+'\n'+[...document.querySelectorAll('input')].map(x=>x.value).join('\n'));expect(text.includes(password)).toBe(false);await page.screenshot({path:path.join(out,`${name}.png`),fullPage:false,animations:'disabled'});const bytes=await fs.readFile(path.join(out,`${name}.png`));screenshots.push({file:`${name}.png`,sha256:createHash('sha256').update(bytes).digest('hex'),sourceSha,applicationBaselineArchiveSha256,publicSafe:true,fullPage:false,viewport:page.viewportSize(),locale:await page.locator('html').getAttribute('lang'),fixtureDisclosure:'Entirely invented QA devices and metadata on loopback HTTP-test. A catalog declaring synthetic:false is an invented parser fixture, not real vendor data or verified provenance. No telemetry, invitation material or installed-service evidence.',test:currentTest});}
async function check(name,run){collectDiagnostics=null;currentTest=name;mark('fixture setup');const began=Date.now();try{await start();await run();results.push({name,status:'PASS',durationMs:Date.now()-began,...await diagnosticDetails()});console.log(`PASS ${name}`);}catch{results.push({name,status:'FAIL',stage,durationMs:Date.now()-began,error:'Bounded assertion failure; request bodies, credentials and private state withheld.',...await diagnosticDetails()});console.log(`FAIL ${name} (${stage})`);}finally{if(context)await context.close();context=null;await stop();}}
async function assertViewport(page){expect(await page.evaluate(()=>({x:scrollX,y:scrollY,w:document.documentElement.scrollWidth,h:document.documentElement.scrollHeight,vw:innerWidth,vh:innerHeight}))).toEqual(expect.objectContaining({x:0,y:0}));expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1&&document.body.scrollWidth<=innerWidth+1&&document.documentElement.scrollHeight<=innerHeight+1)).toBe(true);const main=page.locator('main.device-main');const box=await main.boundingBox();expect(box).not.toBeNull();expect(box.x>=0&&box.y>=0&&box.x+box.width<=page.viewportSize().width+1&&box.y+box.height<=page.viewportSize().height+1).toBe(true);const geometry=await page.locator('.device-page').evaluate(el=>{const main=el.closest('main'),style=getComputedStyle(main),box=el.getBoundingClientRect(),parent=main.getBoundingClientRect();return{left:box.left-parent.left,right:parent.right-box.right,width:box.width,available:main.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight)};});expect(geometry.left).toBeGreaterThanOrEqual(0);expect(geometry.right).toBeGreaterThanOrEqual(-1);expect(Math.abs(geometry.width-geometry.available)).toBeLessThanOrEqual(1);await expect(page.locator('.inventory-panel,.enrollment-panel')).toHaveCount(0);await expect(page.getByRole('dialog')).toHaveCount(0);}
try{
 if(!Number.isInteger(lifecycleRepeats)||lifecycleRepeats<1||lifecycleRepeats>10)throw new Error('LIFECYCLE_REPEAT_RANGE');
 mark('compile fixture');execFileSync(process.env.GO_BIN||'go',['build','-buildvcs=false','-o',path.join(temporary,'conditionalfixture'),'./tests/e2e-review/conditionalfixture'],{cwd:root,stdio:'ignore'});
 if(apiSmoke){
  await start();mark('real API smoke');let cookie='';const call=async(route,data,headers={})=>{if(data&&route!=='/api/auth/login'){const auth=await call('/api/auth/session');headers={'X-CSRF-Token':auth.csrfToken,...headers};}const response=await fetch(base+route,{method:data?'POST':'GET',headers:{...(cookie?{Cookie:cookie}:{}),...(data?{Origin:base,'Content-Type':'application/json'}:{}),...headers},body:data?JSON.stringify(data):undefined});const set=response.headers.get('set-cookie');if(set)cookie=set.split(';')[0];if(!response.ok)throw new Error('SMOKE_HTTP');return response.json();};
  await call('/api/auth/login',{password});const prefix=`/api/devices/${devices.alpha}`;const op=await call(prefix+'/operational'),pkg=await call(prefix+'/packages');expect(op.status).toBe('fresh');expect(pkg.snapshot.inventory.items[0].version).toBe('9.0-1');const before=await call('/api/security/catalog');const loaded=await call('/api/security/catalog',catalog(),{'X-Tracebolt-Catalog-Revision':before.revision});const result=await call(prefix+'/security/review');expect(result.review.candidates).toHaveLength(1);expect(result.review.candidates[0].reportedSourceVersion).toBe('1.0-1');expect(result.review.affectedCves).toBeNull();expect(result.review.revision).toBe(loaded.revision);await control('sample',{device:'alpha',mode:'unknown'});const retained=await call(prefix+'/operational');expect(retained.lastGood.services.items).toHaveLength(2);expect(retained.snapshot.sections.services.meta.quality).toBe('unknown');const unknown=await call(prefix+'/packages');expect(unknown.snapshot.inventory.observedCount).toBeNull();await control('sample',{device:'alpha',mode:'partial'});const partial=await call(prefix+'/security/review');expect(partial.review.status).toBe('partial');await control('advance',{seconds:121});const stale=await call(prefix+'/security/review');expect(stale.collectionStatus).toBe('stale');expect(stale.review).toBeNull();await control('revoke',{device:'alpha'});expect((await call(prefix+'/security/review')).collectionStatus).toBe('revoked');await control('advance',{seconds:86400});expect((await call(prefix+'/packages')).snapshot).toBeNull();results.push({name:'Real HTTP-test auth, durable synthetic operations/package state, retained/partial semantics, catalog CAS, source-version review, stale/revoked/retention boundaries',status:'PASS'});console.log('PASS conditional real-handler API smoke');
 }else{
  const launch={headless:true,args:['--no-sandbox'],env:{...process.env,HOME:temporary,XDG_CONFIG_HOME:temporary,XDG_CACHE_HOME:temporary}};if(process.env.CHROMIUM_PATH)launch.executablePath=process.env.CHROMIUM_PATH;mark('hosted Chromium launch');browser=await chromium.launch(launch);
  await check('Managed package-source enrollment requires explicit scope acknowledgement and never exports invitation material',async()=>{
   const page=await pageAt();mark('managed consent');const state=await get('/api/enrollment');expect(state.collectionProfile).toBe('managed-operations-v2');expect(state.collectionPrivacy).toBe('package_source_metadata_may_be_sensitive');const denied=await post('/api/enrollment/invitations',{requestId:rid(),platform:'linux'});expect(denied.status()).toBe(400);await page.getByRole('button',{name:'Add device',exact:true}).click();const consent=page.getByRole('checkbox',{name:'I acknowledge this operational and package-source collection for the new device.',exact:true});await expect(consent).not.toBeChecked();await expect(page.getByRole('button',{name:'Create invitation',exact:true})).toBeDisabled();await expect(page.getByRole('dialog').getByRole('note')).toContainText('Unencrypted LAN test');await expect(consent).toBeVisible();const disclosure=page.locator('.enrollment-consent details');await expect(disclosure).not.toHaveAttribute('open','');await disclosure.locator('summary').focus();await page.keyboard.press('Enter');await expect(page.locator('.enrollment-consent details')).toContainText('128');await expect(page.locator('.enrollment-consent details p').filter({hasText:'128'})).toBeVisible();await consent.check();await page.keyboard.press('Escape');await page.getByRole('button',{name:'Add device',exact:true}).click();await expect(consent).not.toBeChecked();await consent.check();const responsePending=page.waitForResponse(r=>r.url()===base+'/api/enrollment/invitations'&&r.request().method()==='POST');await page.getByRole('button',{name:'Create invitation',exact:true}).click();const response=await responsePending;expect(response.status()).toBe(201);expect(response.request().postDataJSON().collectionAcknowledged).toBe(true);await page.keyboard.press('Escape');await expect(page.locator('.enrollment-secret')).toHaveCount(0);expect((await get('/api/enrollment')).items.length).toBe(state.items.length+1);
  });
  await check('Device tabs and package/review disclosures issue only their lazy device-bound reads',async()=>{
   const page=await pageAt();mark('lazy reads');const requests=[];page.on('request',r=>requests.push(new URL(r.url()).pathname));await page.goto(`${base}/#/devices/${devices.alpha}`);await expect(page.getByRole('tab',{name:'Inventory',exact:true})).toBeVisible();expect(requests.some(p=>p.endsWith('/operational')||p===`/api/devices/${devices.alpha}/packages`||p.endsWith('/security/review'))).toBe(false);await page.getByRole('tab',{name:'Inventory',exact:true}).click();await expect(page.getByRole('tablist',{name:'Inventory source',exact:true}).getByRole('tab',{name:'Processes',exact:true})).toHaveAttribute('aria-selected','true');expect(requests.some(p=>p.endsWith('/operational'))).toBe(false);await page.getByRole('tablist',{name:'Inventory source',exact:true}).getByRole('tab',{name:'Bounded preview',exact:true}).click();await expect(page.locator('.operational-panel')).toBeVisible();await expect.poll(()=>requests.filter(p=>p.endsWith('/operational')).length).toBe(1);await page.getByRole('tab',{name:'Security coverage',exact:true}).click();await unknownCoverage(page);
   // Inject only the first coverage GET; the retry fetches the authenticated real handler.
   // This is deterministic fault injection, not evidence of native storage contention.
   const coverageURL=base+`/api/devices/${devices.alpha}/security`,coverage=page.locator('.security-panel'),refreshCoverage=page.getByRole('button',{name:'Refresh security coverage',exact:true});
   await expect(coverage.locator('.security-grid')).toBeVisible();await expect(coverage.locator('.security-status-line')).toBeVisible();await expect(coverage.locator('.security-facts')).toHaveCount(1);
   let coverageReads=0,mutations=0,upstream=null,routeFailed=false,holdExpired=false,releaseCoverage;const coverageStatuses=[],coverageGate=new Promise(resolve=>releaseCoverage=resolve),holdTimer=setTimeout(()=>{holdExpired=true;releaseCoverage();},8000);
   const countMutation=request=>{if(new URL(request.url()).pathname.startsWith('/api/')&&['POST','PUT','PATCH','DELETE'].includes(request.method()))mutations++;};
   const recordCoverage=response=>{if(response.url()===coverageURL&&response.request().method()==='GET')coverageStatuses.push(response.status());};
   const coverageHandler=async route=>{try{if(route.request().method()!=='GET'||++coverageReads>2){routeFailed=true;await route.abort('failed');return;}if(coverageReads===1){await route.fulfill({status:429,headers:{'Retry-After':'2'},contentType:'application/json',body:JSON.stringify({error:{code:'storage_busy',message:'controlled coverage read contention'}})});return;}upstream=await route.fetch({timeout:4000,maxRedirects:0,maxRetries:0});await coverageGate;await route.fulfill({response:upstream});}catch{routeFailed=true;try{await route.abort('failed');}catch{}}};
   const expectClearedCoverage=async()=>{await expect(coverage).toHaveAttribute('aria-busy','true');await expect(refreshCoverage).toBeDisabled();await expect(coverage.locator('.security-grid,.security-status-line,.security-gaps,.security-details')).toHaveCount(0);await expect(page.locator('.advisory-review,.package-observations')).toHaveCount(0);await expect(coverage.locator('.security-heading h2')).toHaveText('Security coverage');await expect(coverage.locator('.security-footer')).toContainText('Missing or partial evidence must not be read as zero vulnerabilities.');};
   page.on('request',countMutation);page.on('response',recordCoverage);await page.route(coverageURL,coverageHandler);
   try{
    mark('manual coverage refresh injects one storage_busy read');await refreshCoverage.click();await expect(coverage.locator('.security-loading')).toHaveText('Storage is busy. One automatic read retry in 2 seconds.');expect(coverageReads).toBe(1);expect(coverageStatuses).toEqual([429]);await expectClearedCoverage();
    mark('coverage retry reaches the real authenticated handler');await expect.poll(()=>upstream!==null,{timeout:7000}).toBe(true);expect(routeFailed).toBe(false);expect(coverageReads).toBe(2);expect(upstream.status()).toBe(200);expect(upstream.url()).toBe(coverageURL);
    const retriedCoverage=await upstream.json();expect(retriedCoverage.deviceId).toBe(devices.alpha);expect(retriedCoverage.offeredUpdates.offeredCount).toBeNull();expect(retriedCoverage.vulnerabilities.affectedCves).toBeNull();expect(retriedCoverage.vulnerabilities.reviewCandidates).toBeNull();
    mark('held real coverage response keeps prior facts cleared');await expectClearedCoverage();await expect(coverage.locator('.security-loading')).toHaveText('Checking the manager…');expect(coverageStatuses).toEqual([429]);expect(mutations).toBe(0);expect(holdExpired).toBe(false);releaseCoverage();
    mark('real coverage retry restores observations with unknown authority counts');await expect(coverage).toHaveAttribute('aria-busy','false');await expect(coverage.locator('.security-status-line')).toBeVisible();await unknownCoverage(page);await expect(refreshCoverage).toBeEnabled();expect(coverageReads).toBe(2);expect(coverageStatuses).toEqual([429,200]);expect(routeFailed).toBe(false);expect(holdExpired).toBe(false);expect(mutations).toBe(0);
   }finally{clearTimeout(holdTimer);releaseCoverage();await page.unroute(coverageURL,coverageHandler);page.off('request',countMutation);page.off('response',recordCoverage);}
   expect(requests.some(p=>p===`/api/devices/${devices.alpha}/packages`||p.endsWith('/security/review'))).toBe(false);await packages(page);expect(requests.filter(p=>p===`/api/devices/${devices.alpha}/packages`).length).toBe(1);await review(page);expect(requests.filter(p=>p.endsWith('/security/review')).length).toBe(1);await page.getByRole('tab',{name:'Overview',exact:true}).focus();await page.keyboard.press('ArrowRight');await expect(page.getByRole('tab',{name:'Inventory',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(page.locator('.device-page')).toHaveCount(0);await expect(page).toHaveURL(base+'/#/devices');await expect(page.locator('main')).toBeFocused();
  });
  await check('Operational observations preserve section scope, sample filtering, unavailable data and unknown assessment',async()=>{
   const page=await pageAt();await openDevice(page);mark('operational scope');await page.getByRole('button',{name:/^Services ·/}).click();await expect(page.locator('.operational-table tbody tr')).toHaveCount(2);await page.getByRole('searchbox',{name:'Filter received records'}).fill('alpha');await expect(page.locator('.operational-table tbody tr')).toHaveCount(1);await page.getByRole('button',{name:/^Processes ·/}).click();await expect(page.getByRole('searchbox',{name:'Filter received records'})).toHaveValue('');await expect(page.locator('.operational-panel')).toContainText('CPU time is cumulative');await page.getByRole('button',{name:/^Network ·/}).click();await expect(page.locator('.operational-panel')).toContainText('IP and MAC addresses are excluded');await page.getByRole('button',{name:/^Volumes ·/}).click();await expect(page.locator('.operational-section-detail')).toContainText('Unknown');await expect(page.locator('.operational-assessments')).toContainText('Unknown · Not assessed');await page.getByRole('button',{name:/^Services ·/}).click();await shot(page,'synthetic-conditional-inventory-desktop-en');
  });
  await check('Failed latest collection retains labelled older operational rows while package facts become unknown',async()=>{
   const page=await pageAt();const prior=await get(`/api/devices/${devices.alpha}/operational`);await control('sample',{device:'alpha',mode:'unknown'});await openDevice(page);mark('retained observation');await page.getByRole('button',{name:/^Services ·/}).click();await expect(page.locator('.operational-section-detail')).toContainText('last successful observation');await expect(page.locator('.operational-section-detail')).toContainText('not describe the current state');await expect(page.locator('.operational-table tbody tr')).toHaveCount(2);const current=await get(`/api/devices/${devices.alpha}/operational`);expect(current.lastGood.services.meta.generationId).toBe(prior.snapshot.generationId);expect(current.snapshot.generationId===prior.snapshot.generationId).toBe(false);await page.getByRole('tab',{name:'Security coverage',exact:true}).click();await packages(page);await expect(page.locator('.package-table-scroll')).toHaveCount(0);await expect(page.locator('.package-observations')).toContainText('Unknown');await unknownCoverage(page);
  });
  await check('Partial package-source inventory preserves exact binary/source versions without claiming a complete total',async()=>{
   const page=await pageAt();await control('sample',{device:'alpha',mode:'partial'});await openDevice(page,'alpha','Security coverage');await packages(page);mark('partial package facts');await expect(page.locator('.package-observations')).toContainText('Partial');const row=page.locator('.package-table-scroll tbody tr').filter({hasText:'qa-fixture-binary'});await expect(row).toContainText('9.0-1');await expect(row).toContainText('1.0-1');await expect(row).toContainText('Explicit Source');const value=await get(`/api/devices/${devices.alpha}/packages`);expect(value.snapshot.inventory.observedCount).toBe(20);expect(value.snapshot.inventory.items).toHaveLength(2);await unknownCoverage(page);
  });
  await check('Unconfigured and declared-synthetic catalogs never produce live review candidates or zero-CVE claims',async()=>{
   const page=await pageAt();await openDevice(page,'alpha','Security coverage');await review(page);mark('unavailable and synthetic catalog');await expect(page.locator('.advisory-review')).toContainText('No offline catalog');await expect(page.locator('.advisory-review article')).toHaveCount(0);await importCatalog(catalog(true));await page.getByRole('button',{name:'Refresh review candidates'}).click();await expect(page.locator('.advisory-review')).toContainText('Synthetic catalog');await expect(page.locator('.advisory-review article')).toHaveCount(0);await expect(page.locator('.advisory-review')).toContainText('not evidence of zero affected CVEs');await unknownCoverage(page);
  });
  await check('Conditional candidates use reported source version, immutable lineage and unknown authority counts',async()=>{
   const page=await pageAt();const imported=await importCatalog();await openDevice(page,'alpha','Security coverage');await review(page);mark('source-bound conditional candidate');const article=page.getByRole('article',{name:'Review candidate: qa-fixture-binary / CVE-2099-99990001',exact:true});await expect(article).toBeVisible();await expect(article).toContainText('1.0-1');await expect(article).toContainText('2.0-1');await expect(article).not.toContainText('9.0-1');await expect(page.locator('.advisory-review')).toContainText(imported.revision);await expect(page.locator('.advisory-review')).toContainText(imported.catalog.sha256);const value=await get(`/api/devices/${devices.alpha}/security/review`);expect(value.review.affectedCves).toBeNull();expect(value.review.offeredUpdates).toBeNull();expect(value.review.candidates).toHaveLength(1);await expect(page.locator('.advisory-review')).toContainText(value.review.snapshot.generationId);await expect(page.locator('.advisory-review a')).toHaveCount(0);await unknownCoverage(page);await article.scrollIntoViewIfNeeded();await shot(page,'synthetic-conditional-candidate-desktop-en');
  });
  await check('Missing source coverage and unsupported Ubuntu release remain partial or unavailable without binary-name fallback',async()=>{
   const page=await pageAt();await importCatalog();await control('sample',{device:'alpha',mode:'source-mismatch'});await openDevice(page,'alpha','Security coverage');await review(page);mark('source mismatch');await expect(page.locator('.advisory-review')).toContainText('outside declared catalog coverage');await expect(page.locator('.advisory-review article')).toHaveCount(0);await control('sample',{device:'alpha',mode:'unsupported'});await page.getByRole('button',{name:'Refresh review candidates'}).click();await expect(page.locator('.advisory-review')).toContainText('outside the supported review scope');await expect(page.locator('.advisory-review article')).toHaveCount(0);await unknownCoverage(page);
  });
  await check('Unsupported comparison stays a visible conditional row with unavailable comparison rather than an equal or fixed verdict',async()=>{
   const page=await pageAt();await importCatalog();await control('sample',{device:'alpha',mode:'comparison-unavailable'});await openDevice(page,'alpha','Security coverage');await review(page);mark('comparison unavailable');await expect(page.locator('.advisory-review article')).toHaveCount(1);await expect(page.locator('.advisory-review article')).toContainText('Version comparison unavailable');await expect(page.locator('.advisory-review article')).toContainText('2147483648:1');await expect(page.locator('.advisory-review')).toContainText('Partial selected-scope');await unknownCoverage(page);
  });
  await check('Real current-state stale, revoked and retention expiry suppress candidates without refreshing old observation times',async()=>{
   const page=await pageAt();await importCatalog();const before=await get(`/api/devices/${devices.alpha}/packages`);await control('advance',{seconds:121});await openDevice(page,'alpha','Security coverage');await review(page);mark('stale identity-bound evidence');await expect(page.locator('.advisory-review')).toContainText('Package observations stale');await expect(page.locator('.advisory-review article')).toHaveCount(0);const stale=await get(`/api/devices/${devices.alpha}/packages`);expect(stale.receivedAt).toBe(before.receivedAt);expect(stale.sequence).toBe(before.sequence);await control('revoke',{device:'alpha'});await page.getByRole('button',{name:'Refresh review candidates'}).click();await expect(page.locator('.advisory-review')).toContainText('Device identity revoked');await control('advance',{seconds:86400});await packages(page);await expect(page.locator('.package-table-scroll')).toHaveCount(0);expect((await get(`/api/devices/${devices.alpha}/packages`)).snapshot).toBeNull();
  });
  await check('Catalog file selection is local, import is revision-bound, and explicit clear returns to empty memory-only state',async()=>{
   const page=await pageAt('/settings');mark('catalog file selection');await expect(page.getByRole('heading',{name:'Offline advisory catalog',exact:true})).toBeVisible();let writes=0;page.on('request',r=>{if(r.url()===base+'/api/security/catalog'&&r.method()==='POST')writes++;});await selectCatalog(page,catalog());expect(writes).toBe(0);await page.getByRole('button',{name:'Cancel file selection',exact:true}).click();await expect(page.getByRole('button',{name:'Import catalog',exact:true})).toBeDisabled();await selectCatalog(page,catalog());const before=await get('/api/security/catalog');const pending=page.waitForResponse(r=>r.url()===base+'/api/security/catalog'&&r.request().method()==='POST');await page.getByRole('button',{name:'Import catalog',exact:true}).click();const response=await pending;expect(response.status()).toBe(200);expect((await response.request().allHeaders())['x-tracebolt-catalog-revision']).toBe(before.revision);expect(response.request().postData().includes('synthetic-qa-catalog.json')).toBe(false);await expect(page.locator('.security-catalog')).toContainText('origin and freshness remain unverified');await page.locator('.security-catalog').scrollIntoViewIfNeeded();await shot(page,'synthetic-conditional-catalog-desktop-en');await page.getByRole('button',{name:'Clear catalog',exact:true}).click();await page.getByRole('button',{name:'Keep catalog',exact:true}).click();expect((await get('/api/security/catalog')).catalog).not.toBeNull();await page.getByRole('button',{name:'Clear catalog',exact:true}).click();const clearing=page.waitForResponse(r=>r.url()===base+'/api/security/catalog/clear');await page.getByRole('button',{name:'Confirm clear',exact:true}).click();expect((await clearing).status()).toBe(200);await expect(page.locator('.security-catalog')).toContainText('Catalog cleared');expect((await get('/api/security/catalog')).catalog).toBeNull();
  });
  await check('Stale catalog CAS rejects replacement and requires a fresh status and file selection',async()=>{
   const page=await pageAt('/settings');await expect(page.getByRole('button',{name:'Refresh catalog status'})).toBeEnabled();await selectCatalog(page,catalog());await importCatalog(catalog(true));mark('real catalog revision conflict');const pending=page.waitForResponse(r=>r.url()===base+'/api/security/catalog'&&r.request().method()==='POST');await page.getByRole('button',{name:'Import catalog',exact:true}).click();expect((await pending).status()).toBe(409);mark('catalog conflict is explained');await expect(page.locator('.security-catalog [role=alert]')).toContainText('changed');await page.getByRole('button',{name:'Refresh catalog status'}).click();mark('refreshed catalog requires a new file selection');await expectCatalogSelectionCleared(page);expect((await get('/api/security/catalog')).catalog.synthetic).toBe(true);
  });
  await check('Invalid catalog content and a lost committed import preserve honest status without replay or stored file content',async()=>{
   const page=await pageAt('/settings');await selectCatalog(page,'{"schema":"not-the-supported-contract"}');mark('invalid catalog rejection');const rejected=page.waitForResponse(r=>r.url()===base+'/api/security/catalog'&&r.request().method()==='POST');await page.getByRole('button',{name:'Import catalog',exact:true}).click();expect((await rejected).status()).toBe(400);expect((await get('/api/security/catalog')).catalog).toBeNull();await page.getByRole('button',{name:'Refresh catalog status'}).click();await selectCatalog(page,catalog());let writes=0;await page.route('**/api/security/catalog',async route=>{if(route.request().method()!=='POST')return route.continue();writes++;await route.fetch();await route.abort('failed');});mark('lost committed catalog import');await page.getByRole('button',{name:'Import catalog',exact:true}).click();mark('lost import remains explicitly unconfirmed');await expect(page.locator('.security-catalog')).toContainText('not confirmed');expect(writes).toBe(1);await page.unroute('**/api/security/catalog');await page.getByRole('button',{name:'Refresh catalog status'}).click();mark('refreshed catalog requires a new file selection');await expectCatalogSelectionCleared(page);expect((await get('/api/security/catalog')).catalog).not.toBeNull();expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}).includes('qa-fixture-source'))).toBe(false);
  });
  await check('Review identity mismatch, invented authoritative counts and changed-input errors discard prior candidates',async()=>{
   const page=await pageAt();await importCatalog();await openDevice(page,'alpha','Security coverage');await review(page);await expect(page.locator('.advisory-review article')).toHaveCount(1);mark('wrong device response');await page.route('**/security/review',async route=>{const response=await route.fetch();const body=await response.json();body.deviceId=devices.beta;await route.fulfill({response,body:JSON.stringify(body)});});await page.getByRole('button',{name:'Refresh review candidates'}).click();await expect(page.locator('.advisory-review [role=alert]')).toContainText('inconsistent');await expect(page.locator('.advisory-review article')).toHaveCount(0);await page.unroute('**/security/review');await page.route('**/security/review',async route=>{const response=await route.fetch();const body=await response.json();body.review.affectedCves=0;await route.fulfill({response,body:JSON.stringify(body)});});await page.getByRole('button',{name:'Refresh review candidates'}).click();await expect(page.locator('.advisory-review article')).toHaveCount(0);await expect(page.locator('.advisory-review [role=alert]')).toContainText('inconsistent');await page.unroute('**/security/review');await page.route('**/security/review',route=>route.fulfill({status:409,contentType:'application/json',body:JSON.stringify({error:{code:'review_changed',message:'controlled changed source'}})}));await page.getByRole('button',{name:'Refresh review candidates'}).click();await expect(page.locator('.advisory-review [role=alert]')).toContainText('snapshot or catalog changed');await expect(page.locator('.advisory-review article')).toHaveCount(0);
  });
  await check('Late review response cannot survive device navigation or a closed disclosure',async()=>{
   const page=await pageAt();await importCatalog();await openDevice(page,'alpha','Security coverage');let release,entered,finished;const gate=new Promise(r=>release=r),seen=new Promise(r=>entered=r),done=new Promise(r=>finished=r);await page.route(`**/devices/${devices.alpha}/security/review`,async route=>{const response=await route.fetch();entered();await gate;try{await route.fulfill({response});}catch{}finally{finished();}});await page.getByRole('button',{name:'Conditional advisory review candidates'}).click();await seen;mark('device switch during review');await page.goto(`${base}/#/devices/${devices.beta}`);await expect(page.getByRole('region',{name:'Device QA synthetic fixture beta',exact:true})).toBeVisible();release();await done;await expect(page.locator('.advisory-review article')).toHaveCount(0);await expect(page.getByRole('tab',{name:'Overview',exact:true})).toHaveAttribute('aria-selected','true');await page.getByRole('tab',{name:'Security coverage',exact:true}).click();await review(page);await expect(page.locator('.advisory-review article')).toHaveCount(1);let releaseClose,enteredClose,finishedClose;const closeGate=new Promise(r=>releaseClose=r),closeSeen=new Promise(r=>enteredClose=r),closeDone=new Promise(r=>finishedClose=r);await page.route(`**/devices/${devices.beta}/security/review`,async route=>{const response=await route.fetch();enteredClose();await closeGate;try{await route.fulfill({response});}catch{}finally{finishedClose();}});await page.getByRole('button',{name:'Refresh review candidates'}).click();await closeSeen;await page.getByRole('button',{name:'Conditional advisory review candidates'}).click();releaseClose();await closeDone;await expect(page.locator('.advisory-review')).toHaveCount(0);await page.keyboard.press('Escape');await expect(page.locator('.device-page')).toHaveCount(0);await expect(page).toHaveURL(base+'/#/devices');await expect(page.locator('main')).toBeFocused();
  });
  await check('Protected 401 clears the private review UI without persisting source data in script storage',async()=>{
   const page=await pageAt();await importCatalog();await openDevice(page,'alpha','Security coverage');await review(page);await expect(page.locator('.advisory-review article')).toHaveCount(1);await page.route('**/security/review',route=>route.fulfill({status:401,contentType:'application/json',body:JSON.stringify({error:{code:'authentication_required',message:'controlled session expiry'}})}));mark('protected authorization loss');await page.getByRole('button',{name:'Refresh review candidates'}).click();await expect(page.getByRole('heading',{name:'Sign in',exact:true})).toBeVisible();await expect(page.locator('.app-shell')).toHaveCount(0);await expect(page.locator('.advisory-review article')).toHaveCount(0);expect(await page.evaluate(()=>JSON.stringify({...localStorage,...sessionStorage}).includes('qa-fixture-source'))).toBe(false);
  });
  await check('Persisted-page suspension clears review data until fresh automatic revalidation completes',async()=>{
   const page=await pageAt();await importCatalog();await openDevice(page,'alpha','Security coverage');await review(page);await expect(page.locator('.advisory-review article')).toHaveCount(1);
   const diagnostics={repeatCount:lifecycleRepeats,attempts:[],network:[]};let attempt=0;
   const record=(route,phase,status)=>{if(diagnostics.network.length<80)diagnostics.network.push({attempt,route,phase,...(status===undefined?{}:{status})});};
   const endpoint=url=>{const p=new URL(url).pathname;return p==='/api/auth/session'?'auth':p===`/api/devices/${devices.alpha}/security`?'coverage':p===`/api/devices/${devices.alpha}/security/review`?'review':null;};
   page.on('request',r=>{const route=endpoint(r.url());if(route)record(route,'request');});
   page.on('response',r=>{const route=endpoint(r.url());if(route)record(route,'response',r.status());});
   page.on('requestfailed',r=>{const route=endpoint(r.url());if(route)record(route,'failed');});
   await page.evaluate(()=>{const counts={pagehide:0,pageshow:0,focus:0,blur:0,visibilitychange:0};window.__traceboltLifecycleCounts=counts;for(const type of ['pagehide','pageshow','focus','blur'])window.addEventListener(type,()=>{counts[type]=Math.min(100,counts[type]+1);});document.addEventListener('visibilitychange',()=>{counts.visibilitychange=Math.min(100,counts.visibilitychange+1);});});
   const snapshot=()=>page.evaluate(()=>{const privateView=document.querySelector('.auth-private-view'),panel=document.querySelector('.advisory-review'),counts=window.__traceboltLifecycleCounts??{};const count=key=>Number.isInteger(counts[key])?Math.max(0,Math.min(100,counts[key])):0;return{documentVisible:document.visibilityState==='visible',privateViewPresent:Boolean(privateView),privateInert:privateView?.hasAttribute('inert')??false,privateAriaHidden:privateView?.getAttribute('aria-hidden')==='true',privateVisible:privateView?getComputedStyle(privateView).visibility==='visible':false,appShellPresent:Boolean(document.querySelector('.app-shell')),reviewPresent:Boolean(panel),reviewBusy:panel?.getAttribute('aria-busy')==='true',reviewAlertPresent:Boolean(panel?.querySelector('[role=alert]')),articleCount:Math.min(128,document.querySelectorAll('.advisory-review article').length),events:{pagehide:count('pagehide'),pageshow:count('pageshow'),focus:count('focus'),blur:count('blur'),visibilitychange:count('visibilitychange')}};});
   collectDiagnostics=async()=>({...diagnostics,finalState:await snapshot()});
   for(attempt=1;attempt<=lifecycleRepeats;attempt++){
    const observed={attempt,upstream:[]};diagnostics.attempts.push(observed);let release,arrived=0;const gate=new Promise(r=>release=r);
    const handler=async route=>{const response=await route.fetch();let errorCode='none';if(response.status()!==200){try{const body=await response.json();errorCode=['storage_busy','review_busy','review_changed','authentication_required'].includes(body?.error?.code)?body.error.code:'other';}catch{errorCode='non_json';}}if(observed.upstream.length<8)observed.upstream.push({status:response.status(),errorCode});arrived++;await gate;try{await route.fulfill({response});}catch{observed.fulfillFailed=true;}};
    try{
     mark('persisted pagehide removes review rows');await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true})));await expect(page.locator('.advisory-review article')).toHaveCount(0);
     await page.route('**/security/review',handler);mark('persisted pageshow starts automatic review read');await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true})));await expect.poll(()=>arrived).toBeGreaterThan(0);
     mark('held resumed review keeps rows absent');await expect(page.locator('.advisory-review article')).toHaveCount(0);release();
     mark('persisted auth resume restores visible shell');await expect(page.locator('.app-shell')).toBeVisible();
     mark('fresh resumed review restores exactly one row');await expect(page.locator('.advisory-review article')).toHaveCount(1);
    }finally{observed.state=await snapshot();release();await page.unroute('**/security/review',handler);}
   }
  });
  await check('Mobile package tables remain keyboard-scrollable within the viewport, and German review preserves unknown-count warnings',async()=>{
   const page=await pageAt('/devices',{mobile:true});await importCatalog();await openDevice(page,'alpha','Security coverage');await packages(page);mark('mobile package viewport');const region=page.locator('.package-table-scroll');await region.scrollIntoViewIfNeeded();await region.focus();await page.keyboard.press('ArrowRight');await expect.poll(()=>region.evaluate(el=>el.scrollLeft)).toBeGreaterThan(0);await assertViewport(page);await region.evaluate(el=>{el.scrollLeft=0;});await shot(page,'synthetic-conditional-packages-mobile-en');await page.keyboard.press('Escape');await expect(page.locator('.device-page')).toHaveCount(0);await expect(page).toHaveURL(base+'/#/devices');await page.getByLabel('Language').selectOption('de');await page.goto(`${base}/#/devices/${devices.alpha}`);await page.getByRole('tab',{name:'Sicherheitsabdeckung',exact:true}).click();await page.getByRole('button',{name:'Bedingte Hinweis-Prüfkandidaten',exact:true}).click();await expect(page.locator('.advisory-review article')).toHaveCount(1);await expect(page.locator('.advisory-review')).toContainText('Betroffene CVEs: unbekannt');await page.locator('.advisory-review article').scrollIntoViewIfNeeded();await assertViewport(page);await shot(page,'synthetic-conditional-review-mobile-de');
  });
 }
}catch{fatal=true;console.log(`Conditional setup failed (${stage}); raw diagnostics withheld.`);}
finally{if(context)await context.close();await stop();if(browser)await browser.close();const report={sourceSha,applicationBaselineArchiveSha256,createdAt:new Date().toISOString(),scope:apiSmoke?'Real-handler synthetic API smoke only; no browser executed':'Built React and real authenticated loopback HTTP-test operator, operational/package store, catalog CAS and conditional review handlers',fixture:'Three generated disposable identities; every observation and catalog is invented. Direct synthetic admission to the real enrolled store is not transport, collector, native installer or production-fleet validation.',catalogDisclosure:'Invented normalized files may declare synthetic:false solely to exercise unverified interchange semantics; never real vendor data.',faultInjection:'Explicit malformed/identity/count/401/409 responses, lost import, held response, persisted-page events and service-only fixture-clock advances (auth clock stays real); no actual OS/BFCache or real waiting-age claim',existingEnrollmentQuarantine:'Unaffected: 10 enabled, three explicitly skipped; no full enrollment acceptance',runtimeErrorCount,secretsExported:false,realTelemetryExported:false,results,summary:{passed:results.filter(r=>r.status==='PASS').length,failed:results.filter(r=>r.status==='FAIL').length,setupFailure:fatal}};await fs.writeFile(path.join(out,apiSmoke?'conditional-api-smoke.json':'conditional-browser-results.json'),JSON.stringify(report,null,2));if(!apiSmoke)await fs.writeFile(path.join(out,'conditional-browser-manifest.json'),JSON.stringify({sourceSha,applicationBaselineArchiveSha256,screenshots},null,2));await fs.rm(temporary,{recursive:true,force:true});process.exitCode=fatal||runtimeErrorCount||results.some(r=>r.status==='FAIL')?1:0;}
