import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createJournalAIFixture,journalAIWireFixture,journalAICaseName,journalAIFixtureDisclosure} from './journal-ai-browser.mjs';
const read=path=>fs.readFileSync(new URL(path,import.meta.url),'utf8');
function approval(f){return {dataScope:'service-journal-ai-v1',expectedRevision:f.settings.revision,configRevision:f.settings.configRevision,enabled:true,baseURL:f.settings.baseURL,model:f.settings.model,targets:[{deviceId:f.device,unit:f.unit,generation:f.source.generation.policyGeneration}],lookbackMinutes:f.source.generation.schemaVersion==='tracebolt.journal-generation-view.v3'?15:5,acknowledgeCapture:true,acknowledgeExport:true,acknowledgePlaintext:true};}
test('exact invented service-log receiver requires separate destination and three acknowledgements',()=>{const f=createJournalAIFixture();assert.equal(f.writes,0);assert.equal(f.settings.enabled,false);for(const field of ['acknowledgeCapture','acknowledgeExport','acknowledgePlaintext'])assert.throws(()=>f.handle('POST','/api/ai/journal',{...approval(f),[field]:false}));for(const patch of [{dataScope:'health-summary-v1'},{lookbackMinutes:60},{baseURL:'https://other.invalid/'},{extra:true}])assert.throws(()=>f.handle('POST','/api/ai/journal',{...approval(f),...patch}));const body=approval(f);assert.equal(f.handle('POST','/api/ai/journal',body).saved,true);assert.equal(f.writes,1);assert.equal(f.settings.enabled,true);assert.throws(()=>f.handle('POST','/api/ai/journal',body));});
test('v3 retained policy never transfers a v2 AI approval and reapproval remains bounded',()=>{
 const f=createJournalAIFixture();f.handle('POST','/api/ai/journal',approval(f));const prior=f.settings;
 f.useRetainedPolicy();assert.equal(f.writes,1);assert.equal(f.settings.ready,false);assert.deepEqual(f.settings.targets,prior.targets);assert.equal(f.settings.lookbackMinutes,5);
 const source=f.handle('GET',`/api/ai/journal/source/${f.device}`,null);assert.equal(source.generation.schemaVersion,'tracebolt.journal-generation-view.v3');assert.equal(source.generation.browsingContract,'tracebolt.journal-browse.v1');assert.equal(source.generation.serviceAuthorization,'all-system-services');assert.deepEqual(source.generation.allowedUnits,[]);assert.notDeepEqual(source.generation.policyGeneration,prior.targets[0].generation);
 for(const patch of [{targets:prior.targets},{lookbackMinutes:60},{browseMode:'retained-v1'},{search:'older failure'},{cursor:'s=1'},{acknowledgeCapture:false},{acknowledgeExport:false},{acknowledgePlaintext:false},{configRevision:'changed-config'},{model:'other-model'}])assert.throws(()=>f.handle('POST','/api/ai/journal',{...approval(f),...patch}));
 assert.equal(f.handle('POST','/api/ai/journal',approval(f)).saved,true);assert.equal(f.writes,2);assert.equal(f.settings.lookbackMinutes,15);assert.equal(f.settings.ready,true);assert.deepEqual(f.settings.targets[0].generation,source.generation.policyGeneration);
});
test('retained local policy alone leaves synthetic AI disabled and sends nothing',()=>{const f=createJournalAIFixture();f.useRetainedPolicy();f.handle('GET',`/api/ai/journal/source/${f.device}`,null);assert.equal(f.writes,0);assert.equal(f.settings.enabled,false);assert.deepEqual(f.settings.targets,[]);});
test('Go wire fixture contains only explicit new scope with bounded cited rows',()=>{const v=journalAIWireFixture();assert.deepEqual(Object.keys(v).sort(),['investigations','offSettings','result','settings','source']);assert.equal(v.result.result.packet.dataScope,'service-journal-ai-v1');assert.equal(v.result.result.packet.evidence.length,13);assert.equal(v.result.result.rootCauseConfirmed,false);assert.equal(v.settings.retention,'original-capture-expiry-memory-only');assert.ok(!JSON.stringify(v).includes('synthetic-log-secret'));assert.ok(v.result.result.ai.findings.hypotheses.every(c=>c.evidenceIDs.every(id=>v.result.result.packet.evidence.some(e=>e.id===id))));});
test('hosted case is additive, diagnostic and explicitly synthetic',()=>{const runner=read('./lan-browser.mjs'),source=read('./journal-ai-browser.mjs');assert.equal((runner.match(/await check\(/g)||[]).length,26);assert.equal((runner.match(/await check\(journalAICaseName/g)||[]).length,1);assert.match(runner,/name===journalAICaseName\?\{stage:journalAIFailureStage\(\)\}/);assert.match(journalAICaseName,/Synthetic/);assert.match(journalAIFixtureDisclosure,/No journal collection, real provider request, key entry, persistent grant or host action/);for(const name of ['review-desktop-en','scope-mobile-de','consent-unchecked-mobile-de','consent-checked-mobile-de','saved-mobile-de','finding-mobile-en'])assert.ok(source.includes('synthetic-service-log-ai-'+name));assert.match(source,/headers\['x-csrf-token'\]===csrf/);assert.match(source,/external\).toEqual\(\[\]\)/);assert.ok(!source.includes('ignoreHTTPSErrors'));assert.match(read('../../.github/workflows/validate.yml'),/node --test .*journal-ai-fixtures.test.mjs/);});

test('hosted finding uses the supported investigations page route',()=>{const source=read('./journal-ai-browser.mjs');assert.match(source,/location\.hash='\/cases'/);assert.doesNotMatch(source,/location\.hash='\/investigations'/);});

test('German mobile review is captured before the first save with stable centered consent controls',()=>{
 const source=read('./journal-ai-browser.mjs'),save=source.indexOf("mark('save');await approve.click();");assert.ok(save>0);
 for(const name of ['scope-mobile-de','consent-unchecked-mobile-de','consent-checked-mobile-de'])assert.ok(source.indexOf('synthetic-service-log-ai-'+name)<save);
 assert.ok(source.indexOf('synthetic-service-log-ai-saved-mobile-de')>save);assert.ok(!source.includes('synthetic-service-log-ai-review-mobile-de'));
 assert.equal((source.match(/await approve\.click\(\)/g)||[]).length,2);
 assert.match(source,/await element\.scrollIntoViewIfNeeded\(\);await element\.evaluate\(el=>el\.scrollIntoView\(\{block:'center',inline:'nearest',behavior:'instant'\}\)\)/);
 assert.match(source,/expect\(labels\.nth\(i\)\)\.toBeInViewport\(\{ratio:1\}\)/);
 assert.match(source,/expect\(fixture\.writes\)\.toBe\(0\);expect\(fixture\.settings\.enabled\)\.toBe\(false\)/);
 assert.match(source,/expect\(mobileBoxes\.nth\(i\)\)\.not\.toBeChecked\(\)/);
 assert.match(source,/expect\(boxes\.nth\(i\)\)\.toBeChecked\(\)/);
 assert.doesNotMatch(source,/waitForTimeout|setDefaultTimeout|ignoreHTTPSErrors/);
});

test('new generation needs its second exact approval after the published pre-save captures',()=>{const source=read('./journal-ai-browser.mjs');const first=source.indexOf("mark('save');await approve.click();"), change=source.indexOf('fixture.useRetainedPolicy();',first), second=source.indexOf("mark('save');await approve.click();",first+1);assert.ok(first<change&&change<second);assert.ok(source.indexOf('synthetic-service-log-ai-consent-checked-mobile-de')<first);assert.match(source,/expect\(fixture\.writes\)\.toBe\(2\)/);for(const name of ['v3-review-desktop-en','v3-saved-mobile-de'])assert.ok(source.includes('synthetic-service-log-ai-'+name));});
