import assert from 'node:assert/strict';import test from 'node:test';import fs from 'node:fs';
import {createJournalBrowseFixture,journalBrowseCaseName,journalBrowseDisclosure,journalBrowseDiagnostic,journalFixtureAuthenticated} from './journal-browse-browser.mjs';
const body=f=>({expectedFloor:f.view().expectedFloor,query:{unit:'future.service',start:'1970-01-01T00:00:00Z',end:f.view().serverNow,maxPriority:7,browseMode:'retained-v1'},acknowledgeLogContent:false,acknowledgePlaintext:false,expectedPolicyGeneration:f.view().generation.policyGeneration});
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
test('synthetic receiver admits only current explicit grant and exact bounded queries',()=>{const f=createJournalBrowseFixture();assert.equal(f.view().generation.serviceAuthorization,'all-system-services');const input=body(f);f.handle('POST',f.prefix+'/create',input);assert.equal(f.counts.creates,1);assert.equal(f.page().coverage,'partial');assert.equal(f.page().rows.length,1);assert.equal(f.latestQuery.start,'1970-01-01T00:00:00Z');for(const mutate of [v=>v.expectedFloor='0',v=>v.acknowledgeLogContent=true,v=>v.query.unit='*.service',v=>v.query.cursor='s=unrelated;i=1',v=>v.query.search='x'.repeat(201),v=>v.expectedPolicyGeneration.generation='c'.repeat(64)]){const v=body(f);mutate(v);assert.throws(()=>f.handle('POST',f.prefix+'/create',v));}assert.equal(f.counts.creates,1)});
test('sparse source pages continue exact search and never accumulate previous rows or refresh expiry',()=>{const f=createJournalBrowseFixture(),input=body(f);input.query.search='rare';f.handle('POST',f.prefix+'/create',input);assert.equal(f.page().rows.length,0);assert.equal(f.page().exhausted,undefined);const query=f.latestQuery;const continuation=body(f);continuation.query={...query,cursor:f.page().nextCursor};f.handle('POST',f.prefix+'/create',continuation);assert.equal(f.page().rows.length,1);assert.equal(f.page().exhausted,true);assert.equal(f.latestQuery.end,query.end);f.expire();assert.equal(f.view().contentStatus,'unavailable');assert.throws(()=>f.page());assert.equal(f.counts.creates,2)});
test('AI, source, arbitrary writes and malformed requests never enter the synthetic receiver',()=>{const f=createJournalBrowseFixture();for(const [m,p,b] of [['POST','/api/ai/journal',{}],['POST',f.prefix+'/create',{...body(f),shell:'anything'}],['GET',f.prefix,{unexpected:'body'}],['POST',f.prefix+'/query',{}]])assert.throws(()=>f.handle(m,p,b));assert.equal(f.counts.creates,0)});
test('one additive hosted case is registered in existing CI with explicit synthetic disclosure',()=>{const runner=read('./lan-browser.mjs'),source=read('./journal-browse-browser.mjs');assert.equal((runner.match(/await check\(/g)||[]).length,26);assert.equal((runner.match(/await check\(journalBrowseCaseName/g)||[]).length,1);assert.match(runner,/name===journalBrowseCaseName\?\{stage:journalBrowseFailureStage\(\),journalDiagnostics:journalBrowseFailureDetails\(\)\}/);assert.match(journalBrowseCaseName,/Synthetic retained journal/);assert.match(journalBrowseDisclosure,/No host journal read, helper, installation, permission grant, AI provider/);assert.doesNotMatch(source,/chromium\.launch|newContext\(|setDefaultTimeout|waitForTimeout|ignoreHTTPSErrors|execFile|spawn\(/);assert.match(source,/headers\['x-csrf-token'\]===csrf/);assert.match(source,/sessionSequence>consumedSession/);assert.match(source,/url.origin!==base/);assert.match(source,/expect\(unexpected\)\.toEqual\(\[\]\)/);assert.match(source,/expect\(external\)\.toEqual\(\[\]\)/);assert.ok(source.includes('synthetic-retained-journal-desktop-en'));assert.ok(source.includes('synthetic-retained-journal-mobile-de'));assert.match(read('../../.github/workflows/validate.yml'),/node --test .*journal-browse-fixtures.test.mjs/)});

test('failure diagnostics keep only finite counts and closed state classifications',()=>{
 assert.deepEqual(journalBrowseDiagnostic({counts:{reads:3,creates:1,pages:0,cancels:0},rejected:'csrf',state:'failure'}),{reads:3,creates:1,pages:0,cancels:0,rejected:'csrf',state:'failure'});
 const result=journalBrowseDiagnostic({counts:{reads:Infinity,creates:-1,pages:'secret',cancels:101,raw:'secret'},rejected:'secret token',state:'raw DOM'});
 assert.deepEqual(result,{reads:null,creates:null,pages:null,cancels:null,rejected:'unknown',state:'unknown'});
 const source=read('./journal-browse-browser.mjs');assert.match(source,/throw error/);assert.match(source,/input\[type="password"\]/);assert.match(source,/synthetic-retained-journal-direct-read-failure/);
});

test('real login response authorizes immediate device read without requiring a second session GET',()=>{
 const v={mode:'lan',authenticationRequired:true,authenticated:true,insecureTestMode:true,serverNow:'2026-10-07T12:00:00Z',expiresAt:'2026-10-07T12:30:00Z'};
 assert.equal(journalFixtureAuthenticated(200,v),true);
 for(const body of [null,{}, {...v,authenticated:false},{...v,authenticationRequired:false},{...v,mode:'development'},{...v,insecureTestMode:false},{...v,expiresAt:v.serverNow},{...v,serverNow:'invalid'}])assert.equal(journalFixtureAuthenticated(200,body),false);
 for(const status of [401,403,500])assert.equal(journalFixtureAuthenticated(status,v),false);
 const source=read('./journal-browse-browser.mjs');
 assert.match(source,/method==='POST'&&url.pathname==='\/api\/auth\/login'/);
 assert.match(source,/authenticated=journalFixtureAuthenticated\(response.status\(\)/);
 assert.match(source,/if\(!authenticated\|\|request.postData\(\)!==null\)return fail\('device'\)/);
});
