import test from 'node:test';
import assert from 'node:assert/strict';
import {serviceActionDisplayFixtures,serviceActionDisplayRoute,serviceActionDisplayDisclosure} from './service-action-display-browser.mjs';
const base='http://127.0.0.1:19886';
function setup(){const fixture=serviceActionDisplayFixtures(),state={forbidden:[],external:[],phase:'ready',previewReads:0,inventoryReads:0};return {fixture,state,handle:serviceActionDisplayRoute({base,fixture,state})};}
async function route(handle,path,{method='GET',body=null}={}){const calls=[];await handle({request:()=>({url:()=>path.startsWith('http')?path:base+path,method:()=>method,postData:()=>body}),fulfill:async result=>calls.push({kind:'fulfill',...result}),abort:async reason=>calls.push({kind:'abort',reason}),continue:async()=>calls.push({kind:'continue'})});return calls;}
test('the public display fixture is validated and makes no native acceptance claim',()=>{const {fixture}=setup();assert.equal(fixture.session.transport,'http');assert.equal(fixture.session.insecureTestMode,true);assert.match(fixture.device.name,/SYNTHETIC DISPLAY ONLY/);assert.match(serviceActionDisplayDisclosure,/no real login, permission, approval/);assert.match(serviceActionDisplayDisclosure,/no.*native action acceptance/);assert.equal(fixture.unknown.job.result.outcome,'unknown');assert.equal(fixture.stale.available,false);});
test('all approval, execution and mutation paths abort without reaching the server',async()=>{const {handle,state,fixture}=setup(),prefix='/api/devices/'+fixture.device.id;for(const path of [prefix+'/service-actions/approve',prefix+'/service-actions/execute',prefix+'/health/maintenance','/api/auth/login','/api/auth/logout']){const calls=await route(handle,path,{method:'POST',body:'{}'});assert.equal(calls[0].kind,'abort');}assert.equal(state.forbidden.length,5);assert.equal(state.previewReads,0);assert.equal(state.inventoryReads,0);});
test('preview only returns fixed invented DTOs, requires the exact public fixture unit, and never creates a job',async()=>{const {handle,state,fixture}=setup(),path='/api/devices/'+fixture.device.id+'/service-actions/preview';const read=await route(handle,path,{method:'POST',body:JSON.stringify({unit:'fixture.service'})});assert.equal(read[0].kind,'fulfill');assert.deepEqual(JSON.parse(read[0].body),fixture.preview);assert.equal(fixture.preview.job,null);assert.equal(state.previewReads,1);assert.equal((await route(handle,path,{method:'POST',body:JSON.stringify({unit:'other.service'})}))[0].kind,'abort');assert.equal(state.forbidden.length,1);});
test('all API reads are fulfilled or unavailable in memory; only same-origin static GETs continue',async()=>{const {handle,fixture}=setup();for(const path of ['/api/auth/session','/api/session','/api/overview','/api/investigations','/api/devices/'+fixture.device.id,'/api/devices/'+fixture.device.id+'/inventory/system','/api/devices/'+fixture.device.id+'/service-actions','/api/unrecognized'])assert.equal((await route(handle,path))[0].kind,'fulfill');assert.equal((await route(handle,'/assets/index.js'))[0].kind,'continue');assert.equal((await route(handle,'https://example.com/api/approve'))[0].kind,'abort');});
test('the only inventory POST is a strictly bounded public synthetic read',async()=>{const {handle,state,fixture}=setup(),path='/api/devices/'+fixture.device.id+'/inventory/system/query';const query={section:'services',generationId:fixture.inventory.latest.generationId,cursor:'',search:'',filter:'all',limit:100};const reply=await route(handle,path,{method:'POST',body:JSON.stringify(query)});assert.equal(reply[0].kind,'fulfill');assert.equal(JSON.parse(reply[0].body).services[0].name,'fixture.service');assert.equal(state.inventoryReads,1);for(const body of ['invalid',JSON.stringify({...query,limit:1000}),JSON.stringify({...query,extra:true})])assert.equal((await route(handle,path,{method:'POST',body}))[0].kind,'abort');assert.equal(state.forbidden.length,3);});
