import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import fs from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';
import {v3DiagnosticStage,checkFreshV3Consent,checkMobileSocketViewport,createV3FailureDiagnostics,sanitizeV3MobileSnapshot,readV3MobileSnapshot,sanitizeV3PrimarySnapshot} from './v3-failure-diagnostics.mjs';
const privateValue='PRIVATE_RESPONSE_ERROR_URL_IDENTIFIER_AND_SECRET';
const fresh=['read capability','capability status','capability response bytes','capability JSON decode','collection profile','collection privacy','open dialog','consent unchecked','creation disabled','acknowledge consent','arm primary reader','register creation response','submit creation','await creation response','creation status','request consent','await primary reader','primary reader snapshot','primary reader complete','primary reader validity','primary response binding','creation schema','secret type','masked field','masked value'];
const mobile=['table ARIA','scroll table into view','focus table','press ArrowRight','horizontal scroll response','document offsets','document bounds','main box presence','main viewport bounds','device geometry read','device left inset','device right inset','device width','no legacy panels','no dialogs'];
function fixture(failAt,options={}){
 const stages=[],events=[];let writes=0,capReads=0,creationReads=0,gets=0;
 const fail=phase=>{if(failAt===phase)throw new Error(privateValue);};
 const expected=value=>({toBe(want){fail(stages.at(-1)?.replace('fresh consent / ',''));assert.equal(value,want);},toEqual(want){for(const key of Object.keys(want))assert.deepEqual(value[key],want[key]);},toBeGreaterThan(want){assert.ok(value>want);},toBeGreaterThanOrEqual(want){assert.ok(value>=want);},toBeLessThanOrEqual(want){assert.ok(value<=want);},async toBeDisabled(){fail('creation disabled');},async toHaveAttribute(key,want){if(key==='type'){assert.equal(want,'password');fail('masked field');return;}assert.equal(key,'aria-label');assert.equal(want,'Local sockets and connections');fail('table ARIA');},async toHaveCount(want){assert.equal(want,0);fail(value.kind==='legacy'?'no legacy panels':'no dialogs');},not:{async toBeChecked(){fail('consent unchecked');},toBeNull(){assert.notEqual(value,null);}}});
 expected.objectContaining=value=>value;expected.poll=fn=>({async toBeGreaterThan(want){assert.ok(await fn()>want);},not:{async toMatch(pattern){fail('await primary reader');assert.doesNotMatch(await fn(),pattern);}}});
 const cap={status:()=>failAt==='capability status'?403:200,async body(){capReads++;fail('capability response bytes');return Buffer.from(failAt==='capability JSON decode'?privateValue:JSON.stringify({collectionProfile:failAt==='collection profile'?privateValue:'managed-operations-v3',collectionPrivacy:failAt==='collection privacy'?privateValue:'complete_system_inventory_metadata_may_be_sensitive'}));}};
 const requestBody='{"collectionAcknowledged":true,"requestId":"fixture"}';
 const created={schemaVersion:'tracebolt.enrollment-invitation.v2',invitationSecret:privateValue};
 const creation={status:()=>failAt==='creation status'?403:201,request:()=>({postDataJSON:()=>({collectionAcknowledged:failAt!=='request consent'}),postData:()=>requestBody}),async body(){creationReads++;throw new Error('Secondary body reader must not be used');}};
 const observer={arm(){events.push('arm');fail('arm primary reader');return 1;},state(){return options.phase??'complete';},snapshot(){fail('primary reader snapshot');return {phase:options.phase??'complete',status:201,bytes:100,eof:true,signalAborted:false,requests:1,...options.snapshot};},take(){events.push('take');fail('primary response binding');return options.takeNull?null:{status:201,requestBody,body:created,...options.consumed};},clear(){events.push('clear');}};
 const region={async scrollIntoViewIfNeeded(){events.push('scroll');fail('scroll table into view');},async focus(){events.push('focus');fail('focus table');},async evaluate(){return failAt==='horizontal scroll response'?0:12;}};
 const page={
  getByRole(role,{name}={}){if(role==='dialog')return {kind:'dialog'};if(role==='checkbox')return {async check(){events.push('consent');fail('acknowledge consent');}};return {async click(){if(name==='Add device'){events.push('open');fail('open dialog');}else{assert.equal(name,'Create invitation');writes++;events.push('submit');fail('submit creation');}}};},
  waitForResponse(predicate){events.push('register');fail('register creation response');const r=(url,method)=>({url:()=>url,request:()=>({method:()=>method})});assert.equal(predicate(r('http://127.0.0.1:19894/api/enrollment/invitations','POST')),true);assert.equal(predicate(r('http://other.invalid/api/enrollment/invitations','POST')),false);assert.equal(predicate(r('http://127.0.0.1:19894/api/enrollment/invitations','GET')),false);return failAt==='await creation response'?new Promise((resolve,reject)=>setImmediate(()=>reject(new Error(privateValue)))):Promise.resolve(creation);},
  keyboard:{async press(key){assert.equal(key,'ArrowRight');events.push('key');fail('press ArrowRight');}},
  async evaluate(fn,arg){if(fn.toString().includes('__traceboltEnrollmentBody'))return vm.runInNewContext('('+fn.toString()+')(token)',{window:{__traceboltEnrollmentBody:observer},token:arg});return stages.at(-1).endsWith('document offsets')?{x:failAt==='document offsets'?1:0,y:0}:failAt!=='document bounds';},
  getByLabel(name,{exact}){assert.equal(name,'One-time invitation secret');assert.equal(exact,true);return {async inputValue(){fail('masked value');return options.maskedValue??privateValue;}};},
  viewportSize:()=>({width:390,height:844}),
  locator(selector){if(selector==='.system-inventory .package-table-scroll')return region;if(selector==='main.device-main')return {async boundingBox(){return failAt==='main box presence'?null:{x:failAt==='main viewport bounds'?-2:0,y:0,width:390,height:844};}};if(selector==='.device-page')return {async evaluate(){fail('device geometry read');return {left:failAt==='device left inset'?-1:0,right:failAt==='device right inset'?-2:0,width:390,available:failAt==='device width'?380:390};}};assert.equal(selector,'.inventory-panel,.enrollment-panel');return {kind:'legacy'};},
 };
 const mark=value=>stages.push(value),context={request:{async get(url){gets++;assert.equal(url,'http://127.0.0.1:19894/api/enrollment');fail('read capability');return cap;}}};
 return {stages,events,runFresh:()=>checkFreshV3Consent(page,{base:'http://127.0.0.1:19894',context,expect:expected,mark}),runMobile:()=>checkMobileSocketViewport(page,{expect:expected,mark}),writes:()=>writes,gets:()=>gets,capReads:()=>capReads,creationReads:()=>creationReads};
}
test('fixed stage vocabularies never coerce or echo unknown values',()=>{const hostile={toString(){throw new Error(privateValue);}};for(const [scope,steps]of [['fresh',fresh],['mobile',mobile]])for(const step of steps)assert.notEqual(v3DiagnosticStage(scope,step),'v3 diagnostic / unknown');for(const scope of [privateValue,hostile,null])for(const step of [privateValue,hostile,null])assert.equal(v3DiagnosticStage(scope,step),'v3 diagnostic / unknown');});
test('successful consent preserves consent/write order, primary binding and avoids a secondary creation body read',async()=>{const f=fixture();assert.deepEqual(await f.runFresh(),{schemaVersion:'tracebolt.enrollment-invitation.v2',invitationSecret:privateValue});assert.deepEqual(f.stages,fresh.map(phase=>v3DiagnosticStage('fresh',phase)));assert.deepEqual(f.events,['open','consent','arm','register','submit','take','clear']);assert.equal(f.gets(),1);assert.equal(f.writes(),1);assert.equal(f.capReads(),1);assert.equal(f.creationReads(),0);});
for(const phase of fresh)test(`fresh failure localizes ${phase} and cannot pass or replay`,async()=>{const f=fixture(phase);await assert.rejects(f.runFresh());assert.equal(f.stages.at(-1),v3DiagnosticStage('fresh',phase));assert.deepEqual(f.stages,fresh.slice(0,fresh.indexOf(phase)+1).map(p=>v3DiagnosticStage('fresh',p)));assert.equal(f.gets(),1);assert.equal(f.writes(),fresh.indexOf(phase)>=fresh.indexOf('submit creation')?1:0);assert.ok(f.capReads()<=1&&f.creationReads()<=1);assert.equal(JSON.stringify(f.stages).includes(privateValue),false);});
test('successful mobile helper preserves action and viewport assertion order',async()=>{const f=fixture();await f.runMobile();assert.deepEqual(f.stages,mobile.map(phase=>v3DiagnosticStage('mobile',phase)));assert.deepEqual(f.events,['scroll','focus','key']);assert.equal(f.writes(),0);});
for(const phase of mobile)test(`mobile failure localizes ${phase} and remains a failure`,async()=>{const f=fixture(phase);await assert.rejects(f.runMobile());assert.equal(f.stages.at(-1),v3DiagnosticStage('mobile',phase));assert.deepEqual(f.stages,mobile.slice(0,mobile.indexOf(phase)+1).map(p=>v3DiagnosticStage('mobile',p)));assert.equal(f.writes(),0);assert.equal(JSON.stringify(f.stages).includes(privateValue),false);});
function observed(){const page=new EventEmitter(),context=new EventEmitter(),browser=new EventEmitter();Object.assign(page,{context:()=>context,isClosed:()=>false,viewportSize:()=>({width:390,height:844})});Object.assign(browser,{isConnected:()=>true,version:()=> '145.0.7632.6'});return {page,context,browser,diagnostics:createV3FailureDiagnostics(page,browser)};}
test('body failure captures vetted category and exact request state without payload',()=>{const f=observed(),request={url:()=>`http://localhost/api/enrollment/invitations?${privateValue}`,method:()=> 'POST',failure:()=>({errorText:'net::ERR_ABORTED'})};const response={request:()=>request,status:()=>201};f.page.emit('requestfailed',request);f.diagnostics.response(response);f.diagnostics.operation('response-body');const value=f.diagnostics.capture(new Error('Protocol error (Network.getResponseBody): No data found for resource with given identifier\n'+privateValue));assert.equal(value.transport.category,'body-data-missing');assert.equal(value.transport.requestState,'failed');assert.equal(value.transport.requestFailure,'aborted');assert.equal(value.responseStatus,201);assert.equal(JSON.stringify(value).includes(privateValue),false);f.diagnostics.dispose();assert.equal(value.transport.pageClosed,false);assert.equal(value.events.length,1);});
test('events are closed, bounded, request-scoped and detached from cleanup',()=>{const f=observed();for(let n=0;n<50;n++)f.page.emit('response',{request:()=>({url:()=>`http://localhost/api/devices/agent_${'a'.repeat(32)}/inventory/system/query`,method:()=> 'POST'}),status:()=>200});f.page.emit('request',{url:()=>privateValue,method:()=> 'GET'});f.diagnostics.response({status:()=>privateValue});f.diagnostics.operation(privateValue);const value=f.diagnostics.capture(new Error(privateValue));assert.equal(value.events.length,32);assert.equal(value.responseStatus,null);assert.equal(value.transport.operation,'other');assert.equal(JSON.stringify(value).includes(privateValue),false);f.diagnostics.dispose();for(const emitter of [f.page,f.context,f.browser])assert.deepEqual(emitter.eventNames(),[]);assert.equal(value.events.length,32);});
test('mobile snapshot only permits finite bounded numeric and boolean fields',()=>{assert.deepEqual(sanitizeV3MobileSnapshot({scrollLeft:1.23456,scrollWidth:Infinity,clientWidth:privateValue,rowCount:100001,tableFocused:true,systemBusy:privateValue,bodyText:privateValue}),{scrollLeft:1.235,tableFocused:true});for(const input of [null,undefined,[],privateValue])assert.deepEqual(sanitizeV3MobileSnapshot(input),{});});
test('actual fixed-selector collector never reads private DOM text or input values',()=>{
 const keys=['document','getComputedStyle','scrollX','scrollY','innerWidth','innerHeight'],saved=Object.fromEntries(keys.map(key=>[key,globalThis[key]]));
 const box={left:0,top:0,right:390,width:390,height:844},table={scrollLeft:15,scrollTop:0,scrollWidth:1200,clientWidth:350,clientHeight:600,getBoundingClientRect:()=>box};const main={clientWidth:390,scrollTop:10,getBoundingClientRect:()=>box};const system={getAttribute:()=> 'false',querySelector:()=>null,querySelectorAll:()=>Array(100)};const device={getBoundingClientRect:()=>box};
 for(const node of [table,main,system,device])for(const key of ['innerText','textContent','value','innerHTML'])Object.defineProperty(node,key,{get(){throw new Error(privateValue);}});
 try{Object.assign(globalThis,{document:{activeElement:table,visibilityState:'visible',documentElement:{scrollWidth:390,scrollHeight:844},body:{scrollWidth:390,scrollHeight:844},querySelector:selector=>({'.system-inventory':system,'main.device-main':main,'.device-page':device})[selector]??null,querySelectorAll:()=>[table]},getComputedStyle:()=>({paddingLeft:'0px',paddingRight:'0px'}),scrollX:0,scrollY:0,innerWidth:390,innerHeight:844});const value=sanitizeV3MobileSnapshot(readV3MobileSnapshot());assert.equal(value.tableFocused,true);assert.equal(value.rowCount,100);assert.equal(value.scrollLeft,15);assert.equal(value.deviceAvailable,390);assert.equal(JSON.stringify(value).includes(privateValue),false);}finally{for(const [key,value]of Object.entries(saved)){if(value===undefined)delete globalThis[key];else globalThis[key]=value;}}
});
test('runner retains fail-closed redaction, cleanup and diagnostic budget; no browser is imported here',()=>{const source=fs.readFileSync(new URL('./v3-mvp-browser.mjs',import.meta.url),'utf8');assert.match(source,/checkFreshV3Consent\(page,\{base,context,expect,mark,diagnostics:failureDiagnostics\}\)/);assert.match(source,/checkMobileSocketViewport\(page,\{expect,mark\}\)/);assert.match(source,/finally\{failureDiagnostics\?\.dispose\(\);failureDiagnostics=null;if\(context\)await context.close/);assert.match(source,/setTimeout\(\(\)=>resolve\(\{unavailable:true\}\),1000\)/);assert.match(source,/process.exitCode=fatal\|\|runtimeErrorCount\|\|results.some\(r=>r.status==='FAIL'\)\?1:0/);const helper=fs.readFileSync(new URL('./v3-failure-diagnostics.mjs',import.meta.url),'utf8');assert.doesNotMatch(helper,/setTimeout|setInterval|console\.|\.reload\(|\.clone\(/);assert.equal((helper.match(/await page.keyboard.press\('ArrowRight'\)/g)||[]).length,1);});

test('actual runner failure formatter suppresses diagnostic exceptions and raw failure details',async()=>{
 const source=fs.readFileSync(new URL('./v3-mvp-browser.mjs',import.meta.url),'utf8');
 const start=source.indexOf('async function boundedFailure(caught){'),end=source.indexOf('// Fixed route categories',start);
 for(const mode of ['normal','snapshot-fails','capture-fails']){
  const sandbox={stage:'mobile socket / document bounds',failureSnapshot:null,failureEvents:null,setTimeout,clearTimeout,failureDiagnostics:{capture(){if(mode==='capture-fails')throw new Error(privateValue);return {responseStatus:201,events:[]};},async mobile(){if(mode==='snapshot-fails')throw new Error(privateValue);return {tablePresent:true,clientWidth:350,scrollWidth:1200};}}};
  vm.runInNewContext(source.slice(start,end)+';globalThis.format=boundedFailure;',sandbox);
  const output=await sandbox.format(new Error(privateValue)),parsed=JSON.parse(output);assert.equal(parsed.kind,'Error');assert.equal(output.includes(privateValue),false);
  if(mode==='snapshot-fails')assert.equal(parsed.unavailable,true);else assert.equal(parsed.mobile.tablePresent,true);
 }
});

for(const phase of ['aborted','failed','invalid','cancelled','oversized','invalidated','duplicate','missing','missing-body','invalid-request'])test('primary '+phase+' remains a failure without body fallback or POST replay',async()=>{const f=fixture(undefined,{phase});await assert.rejects(f.runFresh());assert.equal(f.writes(),1);assert.equal(f.creationReads(),0);assert.equal(f.events.at(-1),'clear');});
for(const [name,options]of [['missing EOF',{snapshot:{eof:false}}],['actual signal abort',{snapshot:{signalAborted:true}}],['duplicate request',{snapshot:{requests:2}}],['missing take',{takeNull:true}],['wrong primary status',{consumed:{status:200}}],['different request',{consumed:{requestBody:'different'}}],['invalid schema',{consumed:{body:{schemaVersion:'wrong',invitationSecret:privateValue}}}],['invalid secret type',{consumed:{body:{schemaVersion:'tracebolt.enrollment-invitation.v2',invitationSecret:null}}}],['UI mismatch',{maskedValue:'different'}]])test(name+' cannot satisfy primary/UI acceptance',async()=>{const f=fixture(undefined,options);await assert.rejects(f.runFresh());assert.equal(f.writes(),1);assert.equal(f.creationReads(),0);assert.equal(f.events.at(-1),'clear');});
test('primary projection exports only closed finite lifecycle fields',()=>{const value=sanitizeV3PrimarySnapshot({phase:privateValue,requests:3,status:Infinity,bytes:262146,eof:true,signalAborted:false,body:privateValue,requestBody:privateValue});assert.deepEqual(value,{phase:'unknown',eof:true,signalAborted:false});assert.equal(JSON.stringify(value).includes(privateValue),false);const f=observed();f.diagnostics.primary({phase:'aborted',requests:1,status:201,bytes:17,eof:false,signalAborted:true,body:privateValue});const report=f.diagnostics.capture(new Error(privateValue));assert.equal(report.primary.phase,'aborted');assert.equal(JSON.stringify(report).includes(privateValue),false);f.diagnostics.dispose();});
test('V3 installs the scoped observer only for fresh consent before first page navigation',()=>{const source=fs.readFileSync(new URL('./v3-mvp-browser.mjs',import.meta.url),'utf8');assert.ok(source.includes("context.addInitScript(installEnrollmentPrimaryBody,{url:base+'/api/enrollment/invitations'})"));assert.ok(source.includes('if(observeEnrollment)await context.addInitScript'));assert.equal((source.match(/observeEnrollment:true/g)||[]).length,1);const start=source.indexOf('async function pageAt(');assert.ok(source.indexOf('context.addInitScript(installEnrollmentPrimaryBody',start)<source.indexOf('await page.goto(',start));const helper=fs.readFileSync(new URL('./v3-failure-diagnostics.mjs',import.meta.url),'utf8');assert.doesNotMatch(helper,/await response\.body\(/);assert.match(helper,/consumed.requestBody===response.request\(\).postData\(\)/);assert.match(helper,/input.inputValue\(\)===created.invitationSecret/);});
