import { useEffect, useRef } from 'react';
import type { ReactNode } from 'react';
import { ArrowRight, ArrowUpRight, Check, CheckCircle2, ChevronRight, CircleHelp, Clock3, Database, HardDrive, LoaderCircle, Monitor, Server, ShieldCheck, Terminal, TriangleAlert, X } from 'lucide-react';
import type { Activity, Case, Device, DeviceStatus, Evidence, Metric, Platform } from './types';
import { caseStatusLabels, fullDate, platformLabels, qualityLabels, relativeTime, statusLabels } from './utils';
export function Logo() { return <span className="logo-mark" aria-hidden="true"><i/><i/><i/><i/></span>; }
export function OSIcon({platform, small = false}: {platform: Platform; small?: boolean}) { return <span className={`os-icon ${platform} ${small ? 'small' : ''}`} title={platformLabels[platform]} aria-label={platformLabels[platform]}>{platform === 'windows' ? <span className="windows-mark"><i/><i/><i/><i/></span> : platform === 'linux' ? <Terminal size={small ? 15 : 19} strokeWidth={1.8}/> : <Monitor size={small ? 15 : 19} strokeWidth={1.8}/>}</span>; }
export function Status({status}: {status: DeviceStatus}) { return <span className={`status status-${status}`}><span className="status-dot"/>{statusLabels[status]}</span>; }
export function Source({synthetic, compact = false}: {synthetic: boolean; compact?: boolean}) { return <span className={`source ${synthetic ? 'demo' : 'real'}`}>{synthetic ? <Database size={11}/> : <ShieldCheck size={11}/>} {synthetic ? 'Demo' : compact ? 'Lokal' : 'Lokale Quelle'}</span>; }
export function Severity({value}: {value: Case['severity']}) { const labels = { critical: 'Kritisch', warning: 'Warnung', info: 'Hinweis' }; return <span className={`severity severity-${value}`}>{value === 'info' ? <CircleHelp size={13}/> : <TriangleAlert size={13}/>} {labels[value]}</span>; }
export function SectionHead({title, count, action}: {title: string; count?: number; action?: ReactNode}) { return <div className="section-head"><h2>{title}{count !== undefined && <span className="count">{count}</span>}</h2>{action}</div>; }
export function EmptyState({title, detail, action}: {title: string; detail: string; action?: ReactNode}) { return <div className="empty-state"><span><CheckCircle2 size={25}/></span><h3>{title}</h3><p>{detail}</p>{action}</div>; }
export function Loading({label = 'Lokale Daten werden geladen …'}: {label?: string}) { return <div className="loading" role="status"><LoaderCircle size={21} className="spin"/><span>{label}</span></div>; }
export function MetricValue({metric, compact = false}: {metric: Metric; compact?: boolean}) {
  const valid = metric.value !== null && Number.isFinite(metric.value);
  return <div className={`metric ${compact ? 'compact' : ''}`} title={`${qualityLabels[metric.quality]} · ${metric.source} · ${fullDate(metric.collectedAt)}`}><div className="metric-value">{valid ? <>{Math.round(metric.value!)}<span>{metric.unit}</span></> : <span className="unavailable">—</span>}{!compact && <span className={`metric-quality quality-${metric.quality}`}>{qualityLabels[metric.quality]}</span>}</div>{valid && <div className="meter-track"><span className={metric.quality !== 'healthy' ? 'muted' : metric.value! >= 90 ? 'danger' : metric.value! >= 75 ? 'warning' : ''} style={{width: `${Math.max(0, Math.min(100, metric.value!))}%`}}/></div>}{compact && metric.quality !== 'healthy' && <small className="metric-note">{qualityLabels[metric.quality]}</small>}</div>;
}
export function DeviceTable({devices, onSelect, overview = false}: {devices: Device[]; onSelect: (device: Device) => void; overview?: boolean}) { return <div className="table-scroll"><table className={`device-table ${overview ? 'overview-table' : ''}`}><thead><tr><th>Gerät</th><th>Status</th><th className="hide-medium">Betriebssystem</th>{!overview && <th className="hide-medium">CPU</th>}<th className="hide-small">Arbeitsspeicher</th><th className="hide-small">Datenträger</th><th className="hide-mobile">Zuletzt gesehen</th><th className="row-arrow"><span className="sr-only">Details</span></th></tr></thead><tbody>{devices.map(device => <tr key={device.id}><td><button className="device-name-button" onClick={() => onSelect(device)}><OSIcon platform={device.platform}/><span><strong>{device.name}</strong><span className="device-subline"><span>{device.group}</span><Source synthetic={device.synthetic} compact/></span></span></button></td><td><Status status={device.status}/></td><td className="hide-medium"><span className="os-label">{device.os}</span></td>{!overview && <td className="hide-medium"><MetricValue metric={device.cpu} compact/></td>}<td className="hide-small"><MetricValue metric={device.memory} compact/></td><td className="hide-small"><MetricValue metric={device.disk} compact/></td><td className="hide-mobile"><time dateTime={device.lastSeen} title={fullDate(device.lastSeen)} className={device.status === 'stale' ? 'text-warning' : 'text-secondary'}>{relativeTime(device.lastSeen)}</time></td><td className="row-arrow"><button className="icon-button row-open" aria-label={`${device.name}: Details öffnen`} onClick={() => onSelect(device)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table></div>; }
export function CaseList({cases, onSelect, concise = false}: {cases: Case[]; onSelect: (item: Case) => void; concise?: boolean}) { return <div className={`case-list ${concise ? 'concise' : ''}`}>{cases.map(item => <button className="case-row" onClick={() => onSelect(item)} key={item.id}><span className={`case-symbol ${item.severity}`}>{item.category === 'storage' ? <HardDrive size={19}/> : item.category === 'service' ? <Server size={19}/> : <Monitor size={19}/>}</span><span className="case-row-main"><span className="case-row-title">{item.title}</span><span className="case-row-meta"><span className="mono">{item.deviceName}</span><span className="separator-dot">·</span><Source synthetic={item.synthetic}/></span></span><span className="case-row-end"><Severity value={item.severity}/><span className="case-age">{relativeTime(item.createdAt)}</span></span><ChevronRight className="case-chevron" size={17}/></button>)}</div>; }
export function ActivityList({items, onNavigate}: {items: Activity[]; onNavigate?: (item: Activity) => void}) { return <ol className="activity-list">{items.map(item => <li key={item.id}><span className={`activity-marker ${item.type}`}>{item.type === 'status' ? <Check size={11}/> : item.type === 'case' ? <TriangleAlert size={11}/> : item.type === 'note' ? <Database size={11}/> : <span/>}</span><div><time dateTime={item.time} title={fullDate(item.time)}>{relativeTime(item.time)}</time>{onNavigate && (item.caseId || item.deviceId) ? <button className="activity-link" onClick={() => onNavigate(item)}>{item.title}<ArrowUpRight size={12}/></button> : <strong>{item.title}</strong>}<p>{item.detail}</p></div></li>)}</ol>; }
export function EvidenceCard({evidence, index}: {evidence: Evidence; index: number}) { return <details className="evidence-card" id={`evidence-${evidence.id}`}><summary><span className="evidence-index">{String(index + 1).padStart(2, '0')}</span><span className="evidence-heading"><strong>{evidence.title}</strong><span>{evidence.source}</span></span><span className={`quality-pill quality-${evidence.quality}`}>{qualityLabels[evidence.quality]}</span><ChevronRight size={16}/></summary><div className="evidence-content"><div className="evidence-value"><code>{evidence.value || 'Kein Wert vorhanden'}</code><Source synthetic={evidence.synthetic}/></div><p>{evidence.detail}</p><div className="evidence-foot"><span><Clock3 size={12}/> {fullDate(evidence.collectedAt)}</span><code>{evidence.id}</code></div></div></details>; }
export function Dialog({children, title, onClose, className = ''}: {children: ReactNode; title: string; onClose: () => void; className?: string}) {
  const ref = useRef<HTMLDivElement>(null); const closeRef = useRef(onClose); closeRef.current = onClose;
  useEffect(() => { const previous = document.activeElement as HTMLElement | null; const modal = ref.current; const originalOverflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; modal?.focus(); const key = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); closeRef.current(); } if (event.key === 'Tab' && modal) { const focusable = Array.from(modal.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),summary,[tabindex="0"]')); const first = focusable[0]; const last = focusable.at(-1); if (event.shiftKey && (document.activeElement === first || document.activeElement === modal)) { event.preventDefault(); last?.focus(); } else if (!event.shiftKey && (document.activeElement === last || document.activeElement === modal)) { event.preventDefault(); first?.focus(); } } }; document.addEventListener('keydown', key); return () => { document.removeEventListener('keydown', key); document.body.style.overflow = originalOverflow; previous?.focus(); }; }, []);
  return <div className={`dialog-backdrop ${className}`} onMouseDown={event => { if (event.target === event.currentTarget) onClose(); }}><div className="dialog" ref={ref} role="dialog" aria-modal="true" aria-label={title} tabIndex={-1}><button className="icon-button dialog-close" aria-label="Schließen" onClick={onClose}><X size={20}/></button>{children}</div></div>;
}
export function NextArrow() { return <ArrowRight size={15}/>; }
export function CaseStatus({status}: {status: Case['status']}) { return <span className={`case-status case-status-${status}`}><span className="status-dot"/>{caseStatusLabels[status]}</span>; }
