import { Fragment, useId } from 'react';
import { Info, LoaderCircle, RefreshCw, Search, TriangleAlert } from 'lucide-react';
import { useOperator } from './auth';
import { useLocale } from './i18n';
import { inventoryAge } from './complete-packages-types';
import { useCompleteOverview } from './complete-overview-resource';
import { overviewOutcomes, overviewSectionVisible, volumeGroup } from './complete-overview-types';
import type { OverviewSection, ProcessRow, VolumeRow, Observation } from './complete-overview-types';
import './package-observations.css';
import './complete-packages.css';
import './complete-overview.css';

type Translate = (en: string, de: string) => string;
function outcome(o: Observation, t: Translate): string {
    const labels: Record<string, string> = { observed: t('Observed', 'Beobachtet'), denied: t('Permission denied', 'Zugriff verweigert'), exited: t('Exited during capture', 'Während Erfassung beendet'), invalid: t('Invalid observation', 'Ungültige Beobachtung'), unsupported: t('Unsupported', 'Nicht unterstützt'), unavailable: t('Unavailable', 'Nicht verfügbar'), not_applicable: t('Not applicable', 'Nicht anwendbar') };
    return labels[o.status];
}
function reason(value: string, t: Translate): string {
    const reasons: Record<string, string> = { none: '', source_missing: t('Source missing', 'Quelle fehlt'), permission_denied: t('Permission denied', 'Zugriff verweigert'), not_supported: t('Not supported', 'Nicht unterstützt'), timeout: t('Collection timed out', 'Erfassungszeitlimit erreicht'), invalid_source: t('Invalid source', 'Ungültige Quelle'), read_failed: t('Read failed', 'Lesen fehlgeschlagen'), item_limit: t('Row limit rejected capture', 'Erfassung wegen Zeilengrenze abgelehnt'), byte_limit: t('Byte limit rejected capture', 'Erfassung wegen Bytegrenze abgelehnt'), collector_busy: t('Collector busy', 'Collector ausgelastet'), not_collected: t('Not collected', 'Nicht erfasst'), mount_changed: t('Mount changed during capture', 'Mount während Erfassung geändert'), process_gone: t('Process no longer available', 'Prozess nicht mehr verfügbar'), remote_filesystem_skipped: t('Remote filesystem not measured', 'Entferntes Dateisystem nicht gemessen'), not_applicable: t('Not applicable', 'Nicht anwendbar'), source_invalid: t('Invalid source', 'Ungültige Quelle'), source_changed: t('Source changed', 'Quelle geändert'), resource_limit: t('Resource limit rejected capture', 'Erfassung wegen Ressourcengrenze abgelehnt'), collection_failed: t('Collection failed', 'Erfassung fehlgeschlagen') };
    return reasons[value] ?? t('Unavailable', 'Nicht verfügbar');
}
const bytes = (n: number | null, format: (n: number) => string, fallback: string): string => n === null ? fallback : `${format(n)} B`;
function ProcessTable({ rows, t, number }: { rows: ProcessRow[]; t: Translate; number: (n: number) => string }) {
    return <table><caption className="sr-only">{t('Visible processes · current page', 'Sichtbare Prozesse · aktuelle Seite')}</caption><thead><tr>{['PID', t('Name', 'Name'), t('State', 'Zustand'), t('Parent PID', 'Eltern-PID'), t('Resident memory', 'Residenter Speicher'), t('CPU time (s), cumulative', 'CPU-Zeit (s), kumulativ'), t('Threads', 'Threads'), t('Field availability', 'Feldverfügbarkeit')].map(s => <th scope="col" key={s}>{s}</th>)}</tr></thead><tbody>{rows.map(p => <tr key={p.pid}><th scope="row">{p.pid}</th><td>{p.name ?? outcome(p.observation, t)}</td><td>{p.state?.replaceAll('_', ' ') ?? '—'}</td><td>{p.parentPid === null ? '—' : number(p.parentPid)}</td><td>{bytes(p.rssBytes, number, '—')}</td><td>{p.cpuTimeSeconds === null ? '—' : number(p.cpuTimeSeconds)}</td><td>{p.threads === null ? '—' : number(p.threads)}</td><td><span>{outcome(p.observation, t)}</span>{p.observation.reason !== 'none' && <small>{reason(p.observation.reason, t)}</small>}</td></tr>)}</tbody></table>;
}
function VolumeTable({ rows, t, number }: { rows: VolumeRow[]; t: Translate; number: (n: number) => string }) {
    const groups = [t('Measured local filesystems', 'Gemessene lokale Dateisysteme'), t('Local filesystems · capacity unavailable', 'Lokale Dateisysteme · Kapazität nicht verfügbar'), t('Memory-backed filesystems', 'Speicherbasierte Dateisysteme'), t('Remote filesystems', 'Entfernte Dateisysteme'), t('Unclassified filesystems', 'Nicht klassifizierte Dateisysteme'), t('Virtual and pseudo filesystems', 'Virtuelle und Pseudo-Dateisysteme')];
    return <table><caption className="sr-only">{t('Visible mounts · current page', 'Sichtbare Mounts · aktuelle Seite')}</caption><thead><tr>{[t('Mount point', 'Einhängepunkt'), t('Filesystem / kind', 'Dateisystem / Art'), t('Capacity', 'Kapazität'), t('Available', 'Verfügbar'), t('Used', 'Belegt'), t('Capacity measurement', 'Kapazitätsmessung'), t('Filesystem group', 'Dateisystemgruppe')].map(s => <th scope="col" key={s}>{s}</th>)}</tr></thead><tbody>{rows.map((v, i) => {
        const fallback = v.measurement.status === 'not_applicable' ? t('N/A', 'Nicht anwendbar') : v.measurement.status === 'denied' ? t('Denied', 'Verweigert') : t('Unavailable', 'Nicht verfügbar');
        return <Fragment key={v.id}>{(i === 0 || volumeGroup(rows[i - 1]) !== volumeGroup(v)) && <tr className="overview-group"><th colSpan={7} scope="colgroup">{groups[volumeGroup(v)]} <small>{t('on this page', 'auf dieser Seite')}</small></th></tr>}<tr><th scope="row">{v.mountPoint}<small>{v.id}</small></th><td>{v.filesystem}<small>{v.kind}</small></td><td>{bytes(v.totalBytes, number, fallback)}</td><td>{bytes(v.availableBytes, number, fallback)}</td><td>{v.usedPercent === null ? v.measurement.status === 'observed' && v.totalBytes === 0 ? t('N/A · zero capacity', 'Nicht anwendbar · Nullkapazität') : fallback : `${number(v.usedPercent)}%`}</td><td>{outcome(v.measurement, t)}{v.measurement.reason !== 'none' && <small>{reason(v.measurement.reason, t)}</small>}</td><td>{v.filesystemGroup}</td></tr></Fragment>;
    })}</tbody></table>;
}
export function CompleteOverviewPanel({ deviceId, section, sessionKey }: { deviceId: string; section: OverviewSection; sessionKey?: string | number }) {
    const operator = useOperator(), [locale] = useLocale();
    if (!operator || operator.mode !== 'lan' || !operator.authenticated) return <p>{locale === 'de' ? 'Ein authentifizierter LAN-Operator-Zugang ist erforderlich.' : 'Authenticated LAN operator access is required.'}</p>;
    return <OverviewSession key={`${deviceId}:${section}:${sessionKey ?? operator.expiresAt ?? ''}`} deviceId={deviceId} section={section}/>;
}
function OverviewSession({ deviceId, section }: { deviceId: string; section: OverviewSection }) {
    const [locale] = useLocale(), t: Translate = (en, de) => locale === 'de' ? de : en, id = useId(), r = useCompleteOverview(deviceId, section);
    const number = (n: number) => new Intl.NumberFormat(locale === 'de' ? 'de-DE' : 'en-GB', { maximumFractionDigits: 3 }).format(n);
    const title = section === 'processes' ? t('Processes · complete visible enumeration', 'Prozesse · vollständige sichtbare Aufzählung') : t('Mounts · complete visible enumeration', 'Mounts · vollständige sichtbare Aufzählung');
    const selected = r.view?.[section], complete = selected?.complete, visible = !!r.view && overviewSectionVisible(r.view, section, r.elapsed), page = visible ? r.page : null;
    const field = (label: string, value: string | number) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>;
    const errors = { loadError: t('The manager could not be read. Retry or refresh.', 'Der Manager konnte nicht gelesen werden. Wiederholen oder aktualisieren.'), invalid: t('The manager returned inconsistent or unsupported overview data. Rows were cleared.', 'Der Manager lieferte widersprüchliche oder nicht unterstützte Daten. Zeilen wurden entfernt.'), timeout: t('The request timed out. Retry or refresh.', 'Die Anfrage hat das Zeitlimit erreicht. Wiederholen oder aktualisieren.'), session: t('Your session has ended. Sign in again.', 'Die Sitzung ist beendet. Erneut anmelden.'), clock: t('The time anchor is no longer reliable. Refresh before continuing.', 'Der Zeitanker ist nicht mehr verlässlich. Vor dem Fortfahren aktualisieren.'), busy: t('The manager is busy. Retry in a moment.', 'Der Manager ist ausgelastet. Gleich erneut versuchen.'), restart: t('The generation or cursor changed or expired. Refresh to explicitly restart; previous rows were cleared.', 'Generation oder Cursor geändert oder abgelaufen. Zum Neubeginn aktualisieren; vorherige Zeilen wurden entfernt.'), searchInvalid: t('Search accepts at most 128 printable ASCII characters.', 'Die Suche erlaubt höchstens 128 druckbare ASCII-Zeichen.') };
    const names = { observed: t('Fields observed', 'Felder beobachtet'), denied: t('Denied', 'Verweigert'), exited: t('Exited', 'Beendet'), invalid: t('Invalid', 'Ungültig'), unsupported: t('Unsupported', 'Nicht unterstützt'), unavailable: t('Unavailable', 'Nicht verfügbar'), notApplicable: t('Not applicable', 'Nicht anwendbar') };
    return <section className="package-observations complete-overview" aria-labelledby={`${id}-title`} aria-busy={r.loading}><div className="package-heading"><h2 id={`${id}-title`}>{title}</h2><button className="button" disabled={r.loading || r.error === 'session'} onClick={r.refresh}><RefreshCw size={15}/>{t('Refresh section and restart', 'Abschnitt aktualisieren und neu beginnen')}</button></div>
        <p className="package-note">{t('Agent-visible Linux namespaces only. Complete enumeration covers every row in a successful capture, even when some row fields could not be read. It does not establish device health or physical host coverage.', 'Nur für den Agent sichtbare Linux-Namensräume. Eine vollständige Aufzählung umfasst jede Zeile einer erfolgreichen Erfassung, auch bei nicht lesbaren Feldern. Sie belegt weder Gerätezustand noch vollständige physische Host-Abdeckung.')}</p>
        <p className="package-note">{section === 'processes' ? t('CPU time is cumulative, not current utilization. A process may exit during capture; denied, exited and unavailable rows retain their PID.', 'Die CPU-Zeit ist kumulativ, keine aktuelle Auslastung. Prozesse können während der Erfassung enden; verweigerte, beendete und nicht verfügbare Zeilen behalten ihre PID.') : t('Agent-visible mounts are not a physical-host disk inventory. Local measured capacity comes first, then unavailable local, memory, remote, unclassified and virtual mounts. Groups below apply to this page. Shared filesystem groups and layered filesystems can overlap: do not sum capacities.', 'Für den Agent sichtbare Mounts sind kein Inventar physischer Host-Datenträger. Zuerst gemessene lokale Kapazitäten, dann nicht verfügbare lokale, Speicher-, entfernte, nicht klassifizierte und virtuelle Mounts. Gruppen gelten für diese Seite. Dateisystemgruppen und Schichten können sich überlappen: Kapazitäten nicht addieren.')}</p>
        {r.loading && <p role="status"><LoaderCircle size={15}/>{t('Reading complete overview…', 'Vollständige Übersicht wird gelesen…')}</p>}
        {r.error && <div className="package-error" role="alert"><TriangleAlert size={16}/><p>{errors[r.error]}</p>{['loadError', 'timeout', 'busy'].includes(r.error) && <button className="button" onClick={r.retry} disabled={r.loading}>{t('Retry request', 'Anfrage wiederholen')}</button>}</div>}
        {r.view && selected && <>
            {selected.status === 'not_configured' && <p>{t('Complete process and mount collection is not configured. It requires the separate local consent and a compatible managed-operations-v3 agent.', 'Vollständige Prozess- und Mount-Erfassung ist nicht eingerichtet. Sie erfordert die separate lokale Zustimmung und einen kompatiblen managed-operations-v3-Agenten.')}</p>}
            {selected.transfer && selected.transfer.binding.generationId !== complete?.binding.generationId && <div className="overview-attempt"><strong>{t('Latest transfer', 'Letzte Übertragung')}: {selected.transfer.state}</strong><p>{number(selected.transfer.acceptedRows)} / {number(selected.transfer.declaredRows)} {t('rows received', 'Zeilen empfangen')} · {number(selected.transfer.acceptedChunks)} / {number(selected.transfer.expectedChunks)} {t('chunks', 'Blöcke')}</p><p>{t('Original attempt capture', 'Ursprüngliche Versuchserfassung')}: {selected.transfer.manifest.captureStartedAt} → {selected.transfer.manifest.captureFinishedAt}</p></div>}
            {selected.failure && <div className="overview-attempt" role="status"><strong>{t('Latest collection attempt failed', 'Letzter Erfassungsversuch fehlgeschlagen')}</strong><p>{reason(selected.failure.reason, t)} · {selected.failure.attemptedAt}</p><p>{t('Attempt sequence', 'Versuchssequenz')} {selected.failure.sequence} · {selected.failure.generationId}</p></div>}
            {(selected.failure || selected.transfer && selected.transfer.binding.generationId !== complete?.binding.generationId) && complete && <p className="package-note">{t('The retained complete generation keeps its original capture time and expiry. A later failed or pending attempt does not refresh it.', 'Die vollständige gespeicherte Generation behält ihre ursprüngliche Erfassungszeit und Frist. Ein späterer fehlgeschlagener oder ausstehender Versuch erneuert sie nicht.')}</p>}
            {!visible && <p role="status">{complete ? t('Retained metadata only. Original observations have expired; no rows are shown.', 'Nur gespeicherte Metadaten. Ursprüngliche Beobachtungen sind abgelaufen; keine Zeilen werden angezeigt.') : t('No complete generation is available. Missing or failed collection is not a successful zero-row capture.', 'Keine vollständige Generation verfügbar. Fehlende oder fehlgeschlagene Erfassung ist keine erfolgreiche Null-Zeilen-Erfassung.')}</p>}
            {complete && <>
                <dl className="package-counts overview-totals">{field(t('Complete enumeration rows', 'Vollständig aufgezählte Zeilen'), number(complete.manifest.observedCount))}{field(t('Original observation age (minutes)', 'Ursprüngliches Beobachtungsalter (Minuten)'), Number.isFinite(r.elapsed) ? number(Math.floor((inventoryAge(r.view.serverNow, complete.manifest.collectedAt) + r.elapsed) / 60000)) : t('Unknown', 'Unbekannt'))}{field(t('Rows on this page', 'Zeilen auf dieser Seite'), page ? number(page.items.length) : '—')}</dl>
                <p className="package-note">{t('Enumeration coverage: complete. Field outcomes below count rows in the entire selected generation, not only this page.', 'Aufzählungsabdeckung: vollständig. Feldzustände zählen Zeilen der gesamten gewählten Generation, nicht nur dieser Seite.')}</p>
                <dl className="overview-coverage">{overviewOutcomes.map(k => field(names[k], number(complete.manifest[section].fieldCoverage[k])))}</dl>
                <details className="overview-provenance"><summary>{t('Original generation and capture details', 'Ursprüngliche Generation und Erfassungsdetails')}</summary><dl className="package-facts">{field(t('Section generation', 'Abschnittsgeneration'), complete.binding.generationId)}{field(t('Sequence', 'Sequenz'), complete.binding.sequence)}{field(t('Capture generation', 'Erfassungsgeneration'), complete.manifest.captureGenerationId)}{field(t('Capture started', 'Erfassung begonnen'), complete.manifest.captureStartedAt)}{field(t('Capture finished', 'Erfassung beendet'), complete.manifest.captureFinishedAt)}{field(t('Transfer completed', 'Übertragung abgeschlossen'), complete.completedAt)}{field(t('Original retention deadline', 'Ursprüngliche Aufbewahrungsfrist'), complete.retainedUntil)}</dl></details>
            </>}
            {r.view.processes.complete && r.view.volumes.complete && <p className="package-note overview-independent">{t('Sections are retained independently.', 'Abschnitte werden unabhängig aufbewahrt.')} {r.view.processes.complete.manifest.captureGenerationId !== r.view.volumes.complete.manifest.captureGenerationId ? t('Mixed captures: ', 'Verschiedene Erfassungen: ') : t('Shared capture: ', 'Gemeinsame Erfassung: ')}{t('Processes', 'Prozesse')} {r.view.processes.complete.manifest.captureStartedAt} · {t('Mounts', 'Mounts')} {r.view.volumes.complete.manifest.captureStartedAt}</p>}
            {visible && <><form className="complete-package-search" onSubmit={e => { e.preventDefault(); r.startSearch(); }}><label htmlFor={`${id}-search`}>{t('Search this complete section', 'Vollständigen Abschnitt durchsuchen')}</label><div><input id={`${id}-search`} type="search" maxLength={128} value={r.search} onChange={e => r.changeSearch(e.target.value)} placeholder={section === 'processes' ? t('PID or process name', 'PID oder Prozessname') : t('Mount ID, path, filesystem or kind', 'Mount-ID, Pfad, Dateisystem oder Art')}/><button className="button" disabled={r.loading}><Search size={15}/>{t('Search from first page', 'Ab erster Seite suchen')}</button></div><p className="package-note">{t('Server-side search traverses the pinned generation. Each request returns up to 100 rows and scans at most 2,048. Continue until exhausted; no total match count is known in advance. Search accepts printable ASCII, up to 128 characters.', 'Die serverseitige Suche durchläuft die fixierte Generation. Jede Anfrage liefert bis zu 100 Zeilen und prüft höchstens 2.048. Bis zum Ende fortsetzen; die Trefferzahl ist vorher unbekannt. Suche mit druckbarem ASCII, bis zu 128 Zeichen.')}</p></form>
                {page && <><dl className="overview-progress">{field(t('Rows scanned so far', 'Bisher geprüfte Zeilen'), `${number(r.scanned)} / ${number(page.totalRows)}`)}{field(t('Matches found so far', 'Bisher gefundene Treffer'), number(r.matches))}</dl>{page.items.length > 0 ? <div className="package-table-scroll" role="region" aria-label={title} tabIndex={0}>{section === 'processes' ? <ProcessTable rows={page.items.map(row => row.process!)} t={t} number={number}/> : <VolumeTable rows={page.items.map(row => row.volume!)} t={t} number={number}/>}</div> : <p role="status">{!page.exhausted ? t('No matches in this scan window. More rows remain; continue searching.', 'Keine Treffer in diesem Suchabschnitt. Weitere Zeilen stehen aus; Suche fortsetzen.') : page.totalRows === 0 ? t('Successful complete enumeration contained zero rows.', 'Die erfolgreiche vollständige Aufzählung enthielt null Zeilen.') : r.matches === 0 ? t('No matches in the complete generation.', 'Keine Treffer in der vollständigen Generation.') : t('No further matches. Earlier pages contained matches.', 'Keine weiteren Treffer. Frühere Seiten enthielten Treffer.')}</p>}<div className="complete-package-pagination"><p>{page.exhausted ? t('The entire retained section has been scanned.', 'Der gesamte gespeicherte Abschnitt wurde durchsucht.') : page.searchIncomplete ? t('Search is incomplete. More rows remain.', 'Suche unvollständig. Weitere Zeilen stehen aus.') : t('More rows remain in this complete generation.', 'Weitere Zeilen dieser vollständigen Generation stehen aus.')}</p>{!page.exhausted && <button className="button" onClick={r.next} disabled={r.loading}>{page.searchIncomplete ? t('Continue search', 'Suche fortsetzen') : t('Next page', 'Nächste Seite')}</button>}</div><p className="package-note">{t('Paging deadline', 'Seitenfrist')}: {page.cursorExpiresAt}</p></>}
            </>}
        </>}
        <p className="package-note package-retention"><Info size={16}/>{t('Rows remain available for at most 24 hours from their original capture. Refresh reads existing observations; it does not start collection. Limits reject incomplete captures rather than presenting a sampled prefix as complete.', 'Zeilen bleiben höchstens 24 Stunden ab ihrer ursprünglichen Erfassung verfügbar. Aktualisieren liest vorhandene Beobachtungen und startet keine Erfassung. Grenzen führen zur Ablehnung unvollständiger Erfassungen statt einer als vollständig dargestellten Stichprobe.')}</p>
    </section>;
}
