import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clock3, Database, FileText, HardDrive, Info, LoaderCircle, MemoryStick, MessageSquare, Monitor, Play, ShieldCheck, Terminal, TriangleAlert } from 'lucide-react';
import { mutate, request } from './api';
import { ActivityList, CaseStatus, Dialog, EvidenceCard, Loading, MetricValue, OSIcon, SectionHead, Severity, Source, Status } from './components';
import type { Case, Device } from './types';
import { caseStatusLabels, fullDate, relativeTime, noteBytes } from './utils';

export function DeviceDetail({id,onClose,onCase}: {id:string;onClose:()=>void;onCase:(id:string)=>void}) {
  const [device,setDevice] = useState<Device | null>(null); const [error,setError] = useState(''); const [tab,setTab] = useState('overview'); const [retry,setRetry] = useState(0);
  useEffect(() => { let active=true; setDevice(null); setError(''); setTab('overview'); request<Device>(`/devices/${encodeURIComponent(id)}`).then(value=>{if(active)setDevice(value);}).catch(err=>{if(active)setError(err.message);}); return ()=>{active=false;}; }, [id,retry]);
  return <Dialog title={device ? `Gerät ${device.name}` : 'Gerätedetails'} onClose={onClose} className="device-drawer"><div className="drawer-eyebrow"><Monitor size={14}/>GERÄTEDETAILS</div>{error ? <div className="detail-error" role="alert"><TriangleAlert size={25}/><h2>Gerät nicht verfügbar</h2><p>{error}</p><button className="button" onClick={()=>setRetry(v=>v+1)}>Erneut versuchen</button></div> : !device ? <Loading/> : <><div className="device-detail-heading"><OSIcon platform={device.platform}/><div><h2>{device.name}</h2><p>{device.os}</p></div></div><div className="detail-badges"><Status status={device.status}/><Source synthetic={device.synthetic}/><span className="detail-time"><Clock3 size={13}/>{relativeTime(device.lastSeen)}</span></div><div className={`provenance-notice ${device.synthetic ? '' : 'real'}`}><Database size={16}/><p>{device.synthetic ? 'Synthetisches Beispielgerät. Messwerte, Ereignisse und Belege dienen der Demonstration.' : 'Echte Messwerte aus dieser Linux-Sandbox. Die angezeigte Umgebung ist kein entfernter Kundenrechner.'}</p></div><div className="drawer-tabs" role="tablist" aria-label="Gerätedaten">{[{id:'overview',name:'Übersicht'},{id:'evidence',name:'Belege',count:device.evidence.length},{id:'capabilities',name:'Fähigkeiten',count:device.capabilities.length}].map(item=><button key={item.id} role="tab" aria-selected={tab===item.id} aria-controls={`device-${item.id}`} id={`tab-${item.id}`} onClick={()=>setTab(item.id)}>{item.name}{item.count!==undefined && <span>{item.count}</span>}</button>)}</div><div className="drawer-content" role="tabpanel" id={`device-${tab}`} aria-labelledby={`tab-${tab}`}>
    {tab==='overview' && <><div className="device-metrics">{[{label:'CPU',metric:device.cpu,icon:Terminal},{label:'Arbeitsspeicher',metric:device.memory,icon:MemoryStick},{label:'Datenträger',metric:device.disk,icon:HardDrive}].map(item=><div className="device-metric-card" key={item.label}><span className="device-metric-label"><item.icon size={14}/>{item.label}</span><MetricValue metric={item.metric}/><span className="metric-source">{item.metric.source}</span></div>)}</div><section className="detail-section"><SectionHead title="Geräteprofil"/><dl className="metadata-grid"><div><dt>Gerätename</dt><dd className="mono">{device.name}</dd></div><div><dt>Standort</dt><dd>{device.site}</dd></div><div><dt>Gruppe</dt><dd>{device.group}</dd></div><div><dt>IP-Adresse</dt><dd className="mono">{device.ip || 'Nicht erfasst'}</dd></div><div><dt>Laufzeit</dt><dd>{device.uptime || 'Nicht verfügbar'}</dd></div><div><dt>Collector-Version</dt><dd className="mono">{device.agentVersion || 'Nicht verfügbar'}</dd></div><div className="metadata-wide"><dt>Letzter Kontakt</dt><dd>{fullDate(device.lastSeen)}</dd></div></dl>{device.tags.length>0 && <div className="device-tags">{device.tags.map(tag=><span key={tag}>{tag}</span>)}</div>}</section><section className="detail-section"><SectionHead title="Verknüpfte Untersuchungen" count={device.caseIds.length}/>{device.caseIds.length ? device.caseIds.map(caseId=><button className="linked-case" key={caseId} onClick={()=>onCase(caseId)}><span><FileText size={16}/><strong>{caseId}</strong></span><span>Untersuchen<ArrowRight size={15}/></span></button>) : <p className="quiet-empty"><CheckCircle2 size={16}/>Keine Untersuchung zu diesem Gerät.</p>}</section><div className="quality-explainer"><Info size={16}/><p><strong>Datenqualität ist Teil der Diagnose.</strong> Veraltete, verweigerte oder fehlende Werte sind ausdrücklich markiert. Fehlende Daten bedeuten keinen gesunden Zustand.</p></div></>}
    {tab==='evidence' && <><div className="tab-intro"><h3>Jede Beobachtung hat eine Quelle.</h3><p>Öffne einen Beleg für Messwert, Zeitpunkt und Herkunft.</p></div><div className="evidence-list">{device.evidence.map((evidence,index)=><EvidenceCard key={evidence.id} evidence={evidence} index={index}/>)}</div>{!device.evidence.length && <p className="quiet-empty">Für dieses Gerät sind keine Belege verfügbar.</p>}</>}
    {tab==='capabilities' && <><div className="tab-intro"><h3>Unterstützung transparent gemacht.</h3><p>Fähigkeiten gelten nur für den angegebenen Collector und seine Berechtigungen.</p></div><div className="device-capabilities">{device.capabilities.map(capability=><div key={capability.id}><span className={`capability-icon ${capability.status}`}>{capability.status==='supported' ? <Check size={16}/> : capability.status==='limited' ? <Info size={16}/> : <span>—</span>}</span><div><strong>{capability.name}</strong><p>{capability.detail}</p></div><span className={`capability-state ${capability.status}`}>{{supported:'Unterstützt',limited:'Eingeschränkt',unsupported:'Nicht verfügbar',denied:'Verweigert'}[capability.status]}</span></div>)}</div></>}
  </div><div className="drawer-footer"><ShieldCheck size={14}/><span>Lesende Geräteansicht · keine Remote-Ausführung</span><code>{device.id}</code></div></>}</Dialog>;
}

export function CaseDetail({id,onBack,onDevice,onChanged}: {id:string;onBack:()=>void;onDevice:(id:string)=>void;onChanged:()=>void}) {
  const [item,setItem] = useState<Case | null>(null); const [error,setError] = useState(''); const [retry,setRetry] = useState(0); const [note,setNote] = useState(''); const [saving,setSaving] = useState(false); const [saveError,setSaveError] = useState(''); const [saved,setSaved] = useState('');
  useEffect(() => { let active=true; setItem(null); setError(''); setNote(''); setSaved(''); request<Case>(`/cases/${encodeURIComponent(id)}`).then(value=>{if(active)setItem(value);}).catch(err=>{if(active)setError(err.message);}); return ()=>{active=false;}; }, [id,retry]);
  const changeStatus = async (status: Case['status']) => { if(!item || saving)return; setSaving(true); setSaveError(''); setSaved(''); try {const next=await mutate<Case>(`/cases/${encodeURIComponent(item.id)}/status`,{status});setItem(next);setSaved(`Status gespeichert: ${caseStatusLabels[status]}`);onChanged();}catch(err){setSaveError(err instanceof Error ? err.message : 'Status konnte nicht gespeichert werden.');}finally{setSaving(false);} };
  const saveNote = async (event: React.SubmitEvent<HTMLFormElement>) => {event.preventDefault();if(!item || !note.trim() || noteBytes(note.trim()) > 2000 || saving)return;setSaving(true);setSaveError('');setSaved('');try{const next=await mutate<Case>(`/cases/${encodeURIComponent(item.id)}/notes`,{text:note.trim()});setItem(next);setNote('');setSaved('Notiz lokal gespeichert.');onChanged();}catch(err){setSaveError(err instanceof Error ? err.message : 'Notiz konnte nicht gespeichert werden.');}finally{setSaving(false);} };
  return <><button className="back-link" onClick={onBack}><ArrowLeft size={15}/>Alle Untersuchungen</button>{error ? <div className="panel detail-error" role="alert"><TriangleAlert size={24}/><h2>Untersuchung nicht verfügbar</h2><p>{error}</p><button className="button" onClick={()=>setRetry(v=>v+1)}>Erneut versuchen</button></div> : !item ? <Loading label="Untersuchung wird geladen …"/> : <><div className="case-detail-header"><div><div className="case-heading-meta"><span className="eyebrow">{item.id}</span><span className="separator-dot">·</span><Source synthetic={item.synthetic}/><span className="separator-dot">·</span><span className="text-secondary">{relativeTime(item.createdAt)}</span></div><h1>{item.title}</h1><div className="case-heading-device"><button onClick={()=>onDevice(item.deviceId)}><Monitor size={14}/>{item.deviceName}<ArrowRight size={13}/></button><Severity value={item.severity}/><CaseStatus status={item.status}/></div></div><div className="case-status-actions">{item.status==='open' && <button className="button primary" disabled={saving} onClick={()=>void changeStatus('investigating')}><Play size={14}/>Untersuchung beginnen</button>}{item.status==='investigating' && <button className="button" disabled={saving} onClick={()=>void changeStatus('resolved')}><CheckCircle2 size={16}/>Fall abschließen</button>}{item.status==='resolved' && <button className="button" disabled={saving} onClick={()=>void changeStatus('open')}>Wieder öffnen</button>}</div></div>{saveError && <div className="error-banner" role="alert"><TriangleAlert size={17}/><p>{saveError}</p></div>}{saved && <div className="success-banner" role="status"><Check size={15}/>{saved}</div>}
  <div className="case-detail-grid"><div className="case-content-column"><section className="panel finding-panel"><div className="finding-label"><span><ShieldCheck size={15}/>REGELBASIERTER BEFUND</span><span className={`confidence ${item.confidence==='limited' ? 'limited' : ''}`}>{item.confidence==='evidence-backed' ? 'Durch Belege gestützt' : 'Eingeschränkte Datenlage'}</span></div><h2>Was die Daten zeigen</h2><p className="finding-summary">{item.summary}</p><div className="finding-footer"><span><span className="dot teal"/>Regel <code>{item.ruleId}</code></span><span>{item.evidenceIds.length} verknüpfte Belege</span></div></section><section className="panel evidence-panel"><SectionHead title="Belege" count={item.evidence.length} action={<span className="section-hint">Quelle · Zeitpunkt · Qualität</span>}/><div className="evidence-list">{item.evidence.map((evidence,index)=><EvidenceCard evidence={evidence} key={evidence.id} index={index}/>)}</div>{!item.evidence.length && <p className="panel-empty">Keine Belege verfügbar. Dieser Befund ist nicht bestätigt.</p>}<div className="panel-footnote"><Info size={14}/><span>Belege öffnen, um Beobachtung und Schlussfolgerung zu prüfen.</span></div></section><section className="panel next-steps-panel"><SectionHead title="Der nächste sinnvolle Schritt" action={<span className="read-only-badge"><ShieldCheck size={13}/>Nur lesend</span>}/><ol className="next-steps">{item.nextSteps.map((step,index)=><li key={`${index}-${step}`}><span>{index+1}</span><p>{step}</p></li>)}</ol><div className="runbook-footer"><Terminal size={15}/><span>Runbook: <code>{item.runbookId}</code> · Empfehlungen werden nicht ausgeführt.</span></div></section><section className="panel notes-panel"><SectionHead title="Notizen" count={item.notes.length} action={<MessageSquare size={17}/>}/>{item.notes.length>0 && <div className="notes-list">{item.notes.map(entry=><div className="note" key={entry.id}><div className="note-avatar">LO</div><div><div className="note-author"><strong>{entry.author}</strong><time dateTime={entry.createdAt} title={fullDate(entry.createdAt)}>{relativeTime(entry.createdAt)}</time></div><p>{entry.text}</p></div></div>)}</div>}<form onSubmit={event=>void saveNote(event)}><label htmlFor="case-note" className="sr-only">Notiz zur Untersuchung</label><textarea id="case-note" maxLength={2000} rows={3} value={note} onChange={event=>setNote(event.target.value)} placeholder="Beobachtung oder Entscheidung festhalten …"/><div className="note-form-footer"><span className={noteBytes(note)>2000 ? "text-warning" : ""}>Lokal gespeichert · {noteBytes(note)}/2000 UTF-8 Bytes</span><button type="submit" className="button primary" disabled={!note.trim() || noteBytes(note.trim()) > 2000 || saving}>{saving ? <LoaderCircle className="spin" size={14}/> : <PlusIcon/>}Notiz speichern</button></div></form></section></div>
  <aside className="case-side-column"><section className="panel case-context-panel"><SectionHead title="Kontext"/><dl><div><dt>Gerät</dt><dd><button className="text-button" onClick={()=>onDevice(item.deviceId)}>{item.deviceName}<ArrowRight size={13}/></button></dd></div><div><dt>Kategorie</dt><dd>{{storage:'Datenträger',service:'Dienst',network:'Netzwerk'}[item.category]}</dd></div><div><dt>Datenquelle</dt><dd><Source synthetic={item.synthetic}/></dd></div><div><dt>Erstellt</dt><dd>{fullDate(item.createdAt)}</dd></div><div><dt>Aktualisiert</dt><dd>{fullDate(item.updatedAt)}</dd></div></dl></section><section className="panel case-timeline"><SectionHead title="Verlauf" count={item.timeline.length}/><ActivityList items={item.timeline}/></section><div className="investigation-note"><ShieldCheck size={19}/><strong>Du behältst die Kontrolle.</strong><p>Kein KI-Modell verbunden. Keine Shell und keine automatische Fehlerbehebung. Alle Aussagen beruhen auf den aufgeführten Belegen.</p></div></aside></div></>}</>;
}
function PlusIcon(){return <span aria-hidden="true" className="plus-symbol">+</span>;}
