import { act, cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { EnrollmentSection } from './enrollment';
import * as downloadCommands from './verified-download-command';
import { APIError, AUTH_REQUIRED_EVENT, mutate, request } from './api';
import { AuthBoundary } from './auth';
import { publicBootstrap, enrollmentDeadline, terminationAction, validEnrollmentList } from './enrollment-types';
import type { EnrollmentList, EnrollmentSnapshot, EnrollmentState, InvitationCreation } from './enrollment-types';
import { setLocale } from './i18n';
vi.mock('./api',async original=>({...await original<typeof import('./api')>(),request:vi.fn(),mutate:vi.fn()}));
const invite='invite_'+'1'.repeat(32),fingerprint='ab'.repeat(32),secret='A'.repeat(43);
function record(state:EnrollmentState='created',revision=1):EnrollmentSnapshot {return {version:'tracebolt.enrollment-state.v2',binding:{instanceID:'manager_'+'2'.repeat(32),origin:'https://localhost',profile:'tls',collectionProfile:'basic-readonly-v1',issuerFingerprint:'c'.repeat(64)},invitationID:invite,createRequestID:'request_'+'3'.repeat(32),platform:'linux',revision,state,createdAt:1791046800,deadlineAt:1791047400,updatedAt:1791046810,claim:{claimID:'claim_'+'4'.repeat(32),requestID:'request_'+'5'.repeat(32),keyFingerprint:fingerprint,csrHash:'c'.repeat(64),claimHash:'d'.repeat(64),comparisonCode:'12ab'.repeat(8),at:1791046810},approval:{requestID:'',deviceID:state==='created'||state==='claimed_pending'?'':'agent_'+'6'.repeat(32),keyFingerprint:fingerprint,at:0},intent:{intentID:'',requestID:'',serialHex:'',templateVersion:'',deviceID:'',keyFingerprint:'',notBefore:0,notAfter:0,at:0},issuance:{requestID:'',certificateHash:'',at:0},activation:{requestID:'',at:0},termination:{requestID:'',from:'',at:0}};}
function listing(items:EnrollmentSnapshot[]=[],enabled=true):EnrollmentList {return {serverNow:new Date(1791046800*1000).toISOString(),schemaVersion:'tracebolt.enrollment-operator.v2',enabled,platforms:enabled?['linux']:[],recordLimit:25,items};}
function creation():InvitationCreation {const snapshot=record();return {serverNow:new Date(1791046800*1000).toISOString(),schemaVersion:'tracebolt.enrollment-invitation.v2',snapshot,invitationSecret:secret,bootstrap:{schemaVersion:'tracebolt.enrollment-bootstrap.v2',managerInstanceId:snapshot.binding.instanceID,profile:'tls',enrollmentOrigin:'https://localhost',agentOrigin:'https://localhost:9443',collectionProfile:snapshot.binding.collectionProfile,invitationId:invite,serverCaPem:'-----BEGIN CERTIFICATE-----\nVEVTVF9QVUJMSUNfQ0VSVElGSUNBVEU=\n-----END CERTIFICATE-----',issuerRootPem:'-----BEGIN CERTIFICATE-----\nUk9PVF9DRVJUSUZJQ0FURQ==\n-----END CERTIFICATE-----',issuerPem:'-----BEGIN CERTIFICATE-----\nSVNTVUVSX0NFUlRJRklDQVRF\n-----END CERTIFICATE-----'}};}
const changed=vi.fn(),device=vi.fn();
function section(){return <EnrollmentSection onChanged={changed} onDevice={device} deviceIds={[]}/>;}
let current:EnrollmentList;
beforeEach(()=>{setLocale('en',false);current=listing();vi.mocked(request).mockReset().mockImplementation(async()=>structuredClone(current));vi.mocked(mutate).mockReset();changed.mockClear();device.mockClear();localStorage.clear();sessionStorage.clear();window.location.hash='/devices';});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();vi.useRealTimers();});
async function add(){render(section());await waitFor(()=>expect(screen.getByRole('button',{name:'Add device'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Add device'}));return screen.getByRole('dialog',{name:'Add device'});}
async function openRecord(item:EnrollmentSnapshot){current=listing([item]);render(section());await waitFor(()=>expect(screen.getByRole('button',{name:/Invitations/})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:/Invitations/}));fireEvent.click(screen.getByRole('button',{name:new RegExp(`Review invitation ${invite}`)}));return screen.getByRole('dialog',{name:'Review invitation'});}
async function create(){vi.mocked(mutate).mockResolvedValue(creation());const dialog=await add();fireEvent.click(within(dialog).getByRole('button',{name:'Create invitation'}));await screen.findByLabelText('One-time invitation secret');return dialog;}

describe('explicit enrollment availability and public exports',()=>{
 it('does not enable creation before explicit supported capability',async()=>{current=listing([],false);render(section());await screen.findByText('Enrollment is not configured on this manager.');expect(screen.getByRole('button',{name:'Add device'})).toBeDisabled();expect(mutate).not.toHaveBeenCalled();expect(validEnrollmentList({...listing(),items:[record(),record()]})).toBe(false);});
 it('shows an unavailable state on API failure, with no invented records',async()=>{vi.mocked(request).mockRejectedValue(new Error(secret));render(section());await screen.findByRole('alert');expect(screen.getByRole('button',{name:'Add device'})).toBeDisabled();expect(document.body.textContent).not.toContain(secret);expect(document.querySelector('.enrollment-row')).toBeNull();});
 it('describes the selected Linux platform without fake installer links when download is explicitly disabled',async()=>{vi.spyOn(downloadCommands,'verifiedLinuxDownloadAvailable').mockReturnValue(false);const dialog=await add();expect(within(dialog).getByText('Linux selected. Close this dialog to switch operating systems.')).toBeVisible();expect(dialog.querySelector('.enrollment-platforms')).toBeNull();expect(within(dialog).getByText('Public bootstrap file. No installer is included in this build.')).toBeVisible();expect(dialog.querySelector('a')).toBeNull();expect(mutate).not.toHaveBeenCalled();});
 it('exports a fixed public schema and rejects secret-bearing or private-key bootstrap data',()=>{const response=creation();const exported=publicBootstrap(response.bootstrap,response.snapshot,secret)!;expect(JSON.stringify(exported)).not.toContain(secret);expect(Object.keys(exported)).toHaveLength(10);expect(publicBootstrap({...response.bootstrap,invitationSecret:secret},response.snapshot,secret)).toBeNull();expect(publicBootstrap({...response.bootstrap,issuerPem:'-----BEGIN PRIVATE KEY-----'},response.snapshot,secret)).toBeNull();expect(publicBootstrap({...response.bootstrap,enrollmentOrigin:'https://attacker.example'},response.snapshot,secret)).toBeNull();expect(publicBootstrap({...response.bootstrap,invitationId:'invite_'+'9'.repeat(32)},response.snapshot,secret)).toBeNull();});
 it('counts retained terminal records toward the real capacity',async()=>{current=listing(Array.from({length:25},(_,i)=>({...record('revoked',9),invitationID:'invite_'+i.toString(16).padStart(32,'0')})));render(section());await screen.findByText(/Limit reached: 25 retained records/);expect(screen.getByRole('button',{name:'Add device'})).toBeDisabled();expect(mutate).not.toHaveBeenCalled();});
});

describe('one-time invitation handling',()=>{
 it('creates once, masks the secret and never automatically copies or stores it',async()=>{const clipboard=vi.fn().mockResolvedValue(undefined);vi.stubGlobal('navigator',{...navigator,clipboard:{writeText:clipboard}});const dialog=await create();const input=screen.getByLabelText('One-time invitation secret');expect(input).toHaveAttribute('type','password');expect(input).toHaveValue(secret);expect(clipboard).not.toHaveBeenCalled();expect(mutate).toHaveBeenCalledTimes(1);expect(mutate).toHaveBeenCalledWith('/enrollment/invitations',{requestId:expect.stringMatching(/^request_[a-f0-9]{32}$/),platform:'linux'},expect.any(AbortSignal));expect(JSON.stringify({...localStorage,...sessionStorage})).not.toContain(secret);expect(window.location.href).not.toContain(secret);fireEvent.click(within(dialog).getByRole('button',{name:'Reveal invitation secret'}));expect(input).toHaveAttribute('type','text');fireEvent.click(within(dialog).getByRole('button',{name:'Copy invitation secret'}));await screen.findByText('Copied. Clear your clipboard after use.');expect(clipboard).toHaveBeenCalledExactlyOnceWith(secret);fireEvent.keyDown(document,{key:'Escape'});expect(screen.queryByLabelText('One-time invitation secret')).not.toBeInTheDocument();expect(document.body.textContent).not.toContain(secret);});
 it('downloads only the public bootstrap after an explicit click',async()=>{const dialog=await create();let blob:Blob|undefined;vi.stubGlobal('URL',Object.assign(URL,{createObjectURL:vi.fn((value:Blob)=>{blob=value;return 'blob:public-fixture';}),revokeObjectURL:vi.fn()}));vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});fireEvent.click(within(dialog).getByRole('button',{name:'Download bootstrap file'}));expect(blob).toBeDefined();const text=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsText(blob!);});expect(JSON.parse(text)).toEqual(creation().bootstrap);expect(text).not.toContain(secret);});
 it('clears a revealed secret on pagehide and does not recover it from readback',async()=>{await create();fireEvent.click(screen.getByRole('button',{name:'Reveal invitation secret'}));act(()=>window.dispatchEvent(new Event('pagehide')));expect(screen.queryByLabelText('One-time invitation secret')).not.toBeInTheDocument();expect(screen.getByText(/The secret is no longer available/)).toBeVisible();expect(mutate).toHaveBeenCalledTimes(1);});
 it('never installs a late create response after navigation',async()=>{let finish!:(value:InvitationCreation)=>void;vi.mocked(mutate).mockImplementation(()=>new Promise<InvitationCreation>(resolve=>{finish=resolve;}));const dialog=await add();fireEvent.click(within(dialog).getByRole('button',{name:'Create invitation'}));fireEvent.click(within(dialog).getByRole('button',{name:'Create invitation'}));expect(mutate).toHaveBeenCalledTimes(1);act(()=>window.dispatchEvent(new Event('hashchange')));await act(async()=>finish(creation()));expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(screen.queryByLabelText('One-time invitation secret')).not.toBeInTheDocument();expect(changed).not.toHaveBeenCalled();});
 it('does not recover or replay an uncertain create response',async()=>{vi.mocked(mutate).mockRejectedValue(new APIError(secret));const dialog=await add();fireEvent.click(within(dialog).getByRole('button',{name:'Create invitation'}));await within(dialog).findByRole('alert');expect(dialog.textContent).toContain('An invitation may already exist');expect(dialog.textContent).not.toContain(secret);expect(within(dialog).queryByRole('button',{name:'Create invitation'})).not.toBeInTheDocument();fireEvent.click(within(dialog).getByRole('button',{name:'Check status'}));await waitFor(()=>expect(request).toHaveBeenCalledTimes(3));expect(mutate).toHaveBeenCalledTimes(1);});
 it('clears invitation state when operator access expires',async()=>{const session={mode:'lan',transport:'https',insecureTestMode:false,transportWarning:null,authenticationRequired:true,authenticated:true,csrfToken:'synthetic-session',serverNow:'2026-10-03T15:00:00Z',expiresAt:'2026-10-03T15:30:00Z',expiresInSeconds:1800};vi.mocked(request).mockImplementation(async path=>path==='/auth/session'?session:current);vi.mocked(mutate).mockResolvedValue(creation());render(<AuthBoundary>{section()}</AuthBoundary>);await waitFor(()=>expect(screen.getByRole('button',{name:'Add device'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Add device'}));fireEvent.click(screen.getByRole('button',{name:'Create invitation'}));await screen.findByLabelText('One-time invitation secret');act(()=>window.dispatchEvent(new Event(AUTH_REQUIRED_EVENT)));await screen.findByLabelText('Operator password');expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(screen.queryByDisplayValue(secret)).not.toBeInTheDocument();});
});

describe('device comparison and lifecycle decisions',()=>{
 it('requires comparison and binds approval to the exact displayed revision and full key',async()=>{const item=record('claimed_pending',2);vi.mocked(mutate).mockResolvedValue(record('approved',3));const dialog=await openRecord(item);const approve=within(dialog).getByRole('button',{name:'Approve device'});expect(approve).toBeDisabled();expect(dialog.textContent).toContain(fingerprint.match(/.{4}/g)!.join(' '));expect(dialog.textContent).toContain(item.claim.comparisonCode.match(/.{4}/g)!.join(' '));fireEvent.click(within(dialog).getByRole('checkbox'));fireEvent.click(approve);await within(dialog).findByText('Key approved');expect(mutate).toHaveBeenCalledWith(`/enrollment/${invite}/approve`,{requestId:expect.stringMatching(/^request_[a-f0-9]{32}$/),expectedRevision:2,expectedKeyFingerprint:fingerprint},expect.any(AbortSignal));expect(dialog.textContent).toContain('do not confirm ongoing collection');});
 it('resets comparison when a refreshed record changes its revision or key',async()=>{const dialog=await openRecord(record('claimed_pending',2));fireEvent.click(within(dialog).getByRole('checkbox'));expect(within(dialog).getByRole('button',{name:'Approve device'})).toBeEnabled();const next=record('claimed_pending',3);next.claim.keyFingerprint='cd'.repeat(32);current=listing([next]);fireEvent.click(within(dialog).getByRole('button',{name:'Check status'}));await waitFor(()=>expect(within(dialog).getByRole('button',{name:'Approve device'})).toBeDisabled());expect(within(dialog).getByRole('checkbox')).not.toBeChecked();expect(mutate).not.toHaveBeenCalled();});
 it('does not replace a newer revoked snapshot with a delayed older approval result',async()=>{let finish!:(value:EnrollmentSnapshot)=>void;vi.mocked(mutate).mockImplementation(()=>new Promise<EnrollmentSnapshot>(resolve=>{finish=resolve;}));const dialog=await openRecord(record('claimed_pending',2));fireEvent.click(within(dialog).getByRole('checkbox'));fireEvent.click(within(dialog).getByRole('button',{name:'Approve device'}));current=listing([record('revoked',6)]);fireEvent.click(screen.getByRole('button',{name:'Refresh enrollment status'}));await within(dialog).findByText('Revoked');await act(async()=>finish(record('approved',3)));expect(within(dialog).getByText('Revoked')).toBeVisible();expect(within(dialog).queryByRole('button',{name:'Approve device'})).not.toBeInTheDocument();});
 it('requires deliberate termination and exposes only phase-valid actions',async()=>{vi.mocked(mutate).mockResolvedValue(record('canceled',2));const dialog=await openRecord(record());fireEvent.click(within(dialog).getByRole('button',{name:'Cancel invitation'}));expect(mutate).not.toHaveBeenCalled();expect(within(dialog).getByText('Cancel this invitation?')).toBeVisible();fireEvent.click(within(dialog).getByRole('button',{name:'Confirm termination'}));await within(dialog).findByText('Canceled');expect(mutate).toHaveBeenCalledWith(`/enrollment/${invite}/terminate`,{requestId:expect.any(String),expectedRevision:1,action:'canceled'},expect.any(AbortSignal));expect(terminationAction('claimed_pending')).toBe('rejected');expect(terminationAction('activated')).toBe('revoked');expect(terminationAction('expired')).toBeNull();const activated=record('activated',6);activated.intent.notAfter=1793639400;expect(enrollmentDeadline(activated)).toBe(activated.intent.notAfter);});
 it('renders device-supplied metadata as inert text',async()=>{const item=record('claimed_pending',2);item.binding.collectionProfile='<img src=x onerror=alert(1)>';const dialog=await openRecord(item);fireEvent.click(within(dialog).getByText('Destination & profile'));expect(dialog.textContent).toContain(item.binding.collectionProfile);expect(dialog.querySelector('img')).toBeNull();expect(dialog.querySelector('script')).toBeNull();});
});

describe('approval coverage limits',()=>{
 it('does not allow approval with malformed comparison metadata',async()=>{const item=record('claimed_pending',2);item.claim.comparisonCode='1234';const dialog=await openRecord(item);expect(within(dialog).getByText('Comparison data is incomplete. Approval is unavailable.')).toBeVisible();expect(within(dialog).getByRole('button',{name:'Approve device'})).toBeDisabled();expect(within(dialog).queryByRole('checkbox')).not.toBeInTheDocument();expect(mutate).not.toHaveBeenCalled();});
 it('requires confirmation before revoking an activated identity and never calls it online',async()=>{const item=record('activated',6);item.intent.notAfter=1793639400;vi.mocked(mutate).mockResolvedValue({...record('revoked',7),intent:item.intent,termination:{requestID:'request_'+'8'.repeat(32),from:'activated',at:1791047200}});const dialog=await openRecord(item);expect(within(dialog).getByText('Identity activated')).toBeVisible();expect(dialog.textContent).not.toContain('Online');fireEvent.click(within(dialog).getByRole('button',{name:'Revoke identity'}));expect(mutate).not.toHaveBeenCalled();fireEvent.click(within(dialog).getByRole('button',{name:'Confirm termination'}));await within(dialog).findByText('Revoked');expect(mutate).toHaveBeenCalledWith(`/enrollment/${invite}/terminate`,{requestId:expect.any(String),expectedRevision:6,action:'revoked'},expect.any(AbortSignal));expect(within(dialog).queryByRole('button',{name:'Revoke identity'})).not.toBeInTheDocument();});
});

it('never presents approval from a mismatched response context',async()=>{const next=record('approved',3);next.binding.origin='https://another-manager.example';vi.mocked(mutate).mockResolvedValue(next);const dialog=await openRecord(record('claimed_pending',2));fireEvent.click(within(dialog).getByRole('checkbox'));fireEvent.click(within(dialog).getByRole('button',{name:'Approve device'}));await within(dialog).findByRole('alert');expect(within(dialog).queryByText('Key approved')).not.toBeInTheDocument();expect(within(dialog).getByRole('checkbox')).not.toBeChecked();expect(changed).not.toHaveBeenCalled();});

it('reports an uncertain action and refreshes after closing an in-flight creation',async()=>{vi.mocked(mutate).mockImplementation(()=>new Promise(()=>{}));const dialog=await add();fireEvent.click(within(dialog).getByRole('button',{name:'Create invitation'}));fireEvent.keyDown(document,{key:'Escape'});expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(screen.getByRole('status')).toHaveTextContent('An invitation may already exist');await waitFor(()=>expect(request).toHaveBeenCalledTimes(2));expect(mutate).toHaveBeenCalledTimes(1);});

describe('server-anchored enrollment deadlines',()=>{
 it('disables approval against the validated server deadline, not browser wall-clock time',async()=>{vi.spyOn(Date,'now').mockReturnValue(0);const item=record('claimed_pending',2);const dialog=await openRecord(item);fireEvent.click(within(dialog).getByRole('checkbox'));expect(within(dialog).getByRole('button',{name:'Approve device'})).toBeEnabled();current.serverNow=new Date((item.deadlineAt+1)*1000).toISOString();fireEvent.click(within(dialog).getByRole('button',{name:'Check status'}));await within(dialog).findByText('The server deadline has passed. Approval is unavailable; refresh status.');expect(within(dialog).getByRole('button',{name:'Approve device'})).toBeDisabled();expect(within(dialog).getByRole('checkbox')).not.toBeChecked();expect(mutate).not.toHaveBeenCalled();});
 it('removes a displayed invitation secret when its short server deadline passes',async()=>{vi.useFakeTimers({toFake:['setTimeout','clearTimeout','setInterval','clearInterval','performance']});const response=creation();response.snapshot.deadlineAt=response.snapshot.createdAt+1;vi.mocked(mutate).mockResolvedValue(response);render(section());await act(async()=>{});fireEvent.click(screen.getByRole('button',{name:'Add device'}));fireEvent.click(screen.getByRole('button',{name:'Create invitation'}));await act(async()=>{});expect(screen.getByLabelText('One-time invitation secret')).toHaveValue(secret);await act(async()=>{await vi.advanceTimersByTimeAsync(1001);});expect(screen.queryByLabelText('One-time invitation secret')).not.toBeInTheDocument();expect(screen.getByText(/The secret is no longer available/)).toBeVisible();});
 it('rejects missing clock anchors and malformed public certificate framing',()=>{expect(validEnrollmentList({...listing(),serverNow:undefined})).toBe(false);const response=creation();for(const issuerPem of ['garbage'+response.bootstrap.issuerPem,response.bootstrap.issuerPem+'garbage','-----BEGIN PRIVATE KEY-----\nAAAA\n-----END PRIVATE KEY-----'])expect(publicBootstrap({...response.bootstrap,issuerPem},response.snapshot,secret)).toBeNull();for(const agentOrigin of ['https://localhost:443','https://LOCALHOST:9443','https://localhost:9443/','https://localhost:09443'])expect(publicBootstrap({...response.bootstrap,agentOrigin},response.snapshot,secret)).toBeNull();expect(publicBootstrap({...response.bootstrap,issuerPem:'-----BEGIN CERTIFICATE-----\n'+secret+'=\n-----END CERTIFICATE-----'},response.snapshot,secret)).toBeNull();});
});

it('requires a fresh server-clock anchor and comparison after restoring a hidden page',async()=>{const dialog=await openRecord(record('claimed_pending',2));fireEvent.click(within(dialog).getByRole('checkbox'));act(()=>window.dispatchEvent(new Event('pagehide')));expect(within(dialog).getByRole('button',{name:'Approve device'})).toBeDisabled();expect(within(dialog).getByRole('checkbox')).not.toBeChecked();expect(within(dialog).getByText('Server time is unconfirmed. Refresh status.')).toBeVisible();act(()=>window.dispatchEvent(new Event('pageshow')));await waitFor(()=>expect(request).toHaveBeenCalledTimes(2));await waitFor(()=>expect(within(dialog).queryByText('Server time is unconfirmed. Refresh status.')).not.toBeInTheDocument());expect(within(dialog).getByRole('button',{name:'Approve device'})).toBeDisabled();expect(mutate).not.toHaveBeenCalled();});

it('cannot restore a clock from an in-flight read after the page was hidden',async()=>{const dialog=await openRecord(record('claimed_pending',2));let finish!:(value:EnrollmentList)=>void;vi.mocked(request).mockImplementationOnce(()=>new Promise<EnrollmentList>(resolve=>{finish=resolve;}));fireEvent.click(within(dialog).getByRole('button',{name:'Check status'}));act(()=>window.dispatchEvent(new Event('pagehide')));await act(async()=>finish(listing([record('claimed_pending',2)])));expect(within(dialog).getByText('Server time is unconfirmed. Refresh status.')).toBeVisible();expect(within(dialog).getByRole('button',{name:'Approve device'})).toBeDisabled();expect(mutate).not.toHaveBeenCalled();});


describe('fresh operational collection consent',()=>{
 function managedListing():EnrollmentList{return {...listing(),collectionProfile:'managed-operations-v1',collectionPrivacy:'metadata_labels_may_be_sensitive'};}
 function managedCreation():InvitationCreation{const response=creation();response.snapshot.binding.collectionProfile='managed-operations-v1';response.bootstrap.collectionProfile='managed-operations-v1';return response;}
 it('accepts only the explicit profile/privacy pair while preserving basic compatibility',()=>{
  expect(validEnrollmentList(listing())).toBe(true);
  expect(validEnrollmentList({...listing(),collectionProfile:'basic-readonly-v1'})).toBe(true);
  expect(validEnrollmentList(managedListing())).toBe(true);
  for(const value of [ {...listing(),collectionProfile:'managed-operations-v1'}, {...managedListing(),collectionPrivacy:'anonymous'}, {...listing(),collectionPrivacy:'metadata_labels_may_be_sensitive'}, {...managedListing(),collectionProfile:'future-profile'}, {...listing(),collectionProfile:null} ])expect(validEnrollmentList(value)).toBe(false);
 });
 it('requires a visible affirmative acknowledgement and adds only its typed boolean to the create request',async()=>{
  current=managedListing();vi.mocked(mutate).mockResolvedValue(managedCreation());const dialog=await add();
  expect(within(dialog).getByText(/Names and mount paths may contain personal or sensitive information/)).toBeVisible();
  expect(within(dialog).getByText(/No command lines, environment variables or raw log bodies/)).toHaveTextContent('No AI export.');
  expect(within(dialog).getByText(/Coverage depends on the agent’s namespace and permissions/)).toBeVisible();
  const consent=within(dialog).getByRole('checkbox',{name:'I acknowledge this additional collection for the new device.'});const button=within(dialog).getByRole('button',{name:'Create invitation'});
  expect(consent).not.toBeChecked();expect(button).toBeDisabled();fireEvent.click(button);expect(mutate).not.toHaveBeenCalled();
  fireEvent.click(consent);expect(button).toBeEnabled();fireEvent.click(button);await screen.findByLabelText('One-time invitation secret');
  expect(mutate).toHaveBeenCalledExactlyOnceWith('/enrollment/invitations',{requestId:expect.stringMatching(/^request_[a-f0-9]{32}$/),platform:'linux',collectionAcknowledged:true},expect.any(AbortSignal));
  expect(JSON.stringify({...localStorage,...sessionStorage})).not.toContain('collectionAcknowledged');
 });
 it('never reveals a secret or exports bootstrap when the response silently changes the acknowledged profile',async()=>{
  current=managedListing();vi.mocked(mutate).mockResolvedValue(creation());const dialog=await add();fireEvent.click(within(dialog).getByRole('checkbox'));fireEvent.click(within(dialog).getByRole('button',{name:'Create invitation'}));await within(dialog).findByRole('alert');
  expect(within(dialog).queryByLabelText('One-time invitation secret')).not.toBeInTheDocument();expect(within(dialog).queryByRole('button',{name:'Download bootstrap file'})).not.toBeInTheDocument();expect(document.body.textContent).not.toContain(secret);expect(mutate).toHaveBeenCalledTimes(1);
 });
 it('resets acknowledgement after close/reopen and after hiding the page',async()=>{
  current=managedListing();let dialog=await add();fireEvent.click(within(dialog).getByRole('checkbox'));fireEvent.keyDown(document,{key:'Escape'});fireEvent.click(screen.getByRole('button',{name:'Add device'}));dialog=screen.getByRole('dialog',{name:'Add device'});expect(within(dialog).getByRole('checkbox')).not.toBeChecked();fireEvent.click(within(dialog).getByRole('checkbox'));act(()=>window.dispatchEvent(new Event('pagehide')));expect(within(dialog).getByRole('checkbox')).not.toBeChecked();expect(within(dialog).getByRole('button',{name:'Create invitation'})).toBeDisabled();expect(mutate).not.toHaveBeenCalled();
 });
 it('clears an existing invitation dialog when a confirmed collection profile changes',async()=>{
  current=managedListing();vi.mocked(mutate).mockResolvedValue(managedCreation());const dialog=await add();fireEvent.click(within(dialog).getByRole('checkbox'));fireEvent.click(within(dialog).getByRole('button',{name:'Create invitation'}));await screen.findByLabelText('One-time invitation secret');current=listing();fireEvent.click(within(dialog).getByRole('button',{name:'Check status'}));await waitFor(()=>expect(screen.queryByRole('dialog')).not.toBeInTheDocument());expect(screen.queryByLabelText('One-time invitation secret')).not.toBeInTheDocument();expect(mutate).toHaveBeenCalledTimes(1);
 });
 it('shows German consent without losing the explicit checkbox gate',async()=>{
  setLocale('de',false);current=managedListing();render(section());await waitFor(()=>expect(screen.getByRole('button',{name:'Gerät hinzufügen'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'Gerät hinzufügen'}));const dialog=screen.getByRole('dialog',{name:'Gerät hinzufügen'});expect(within(dialog).getByText('Betriebsinventar · Linux')).toBeVisible();expect(within(dialog).getByRole('checkbox',{name:'Ich bestätige diese zusätzliche Erfassung für das neue Gerät.'})).not.toBeChecked();expect(within(dialog).getByRole('button',{name:'Einladung erstellen'})).toBeDisabled();
 });
});


it('invalidates a pending record decision with an uncertain outcome when current configuration cannot be confirmed',async()=>{
 vi.useFakeTimers({toFake:['setInterval','clearInterval']});const item=record('claimed_pending',2);let resolve!:(value:EnrollmentSnapshot)=>void;let signal:AbortSignal|undefined;vi.mocked(mutate).mockImplementation(async(_path,_body,s)=>new Promise<EnrollmentSnapshot>(done=>{resolve=done;signal=s;}));const dialog=await openRecord(item);fireEvent.click(within(dialog).getByRole('checkbox'));fireEvent.click(within(dialog).getByRole('button',{name:'Approve device'}));expect(signal).toBeDefined();vi.mocked(request).mockRejectedValue(new Error('synthetic configuration failure'));await act(async()=>{await vi.advanceTimersByTimeAsync(10000);});await screen.findByRole('alert');expect(signal!.aborted).toBe(true);expect(screen.queryByRole('dialog')).not.toBeInTheDocument();expect(screen.getByRole('status')).toHaveTextContent('Action not confirmed. Refresh status before making another decision.');await act(async()=>resolve(record('approved',3)));expect(changed).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'Add device'})).toBeDisabled();
});
