import { useEffect, useSyncExternalStore } from 'react';
import { english, germanOverrides } from './translations';
import type { TranslationKey } from './translations';
export type Locale='en'|'de';
export const LOCALE_KEY='tracebolt.locale';
export function initialLocale():Locale {try{const value=localStorage.getItem(LOCALE_KEY);return value==='de'?'de':'en';}catch{return 'en';}}
let locale:Locale=initialLocale();
const listeners=new Set<()=>void>();
export function getLocale():Locale{return locale;}
export function dateLocale():string{return locale==='de'?'de-DE':'en-GB';}
function updateDocument(){if(typeof document!=='undefined'){document.documentElement.lang=locale;document.title=t('Tracebolt · Gerätebetrieb');}}
export function setLocale(next:Locale,persist=true):void {if(next!=='en'&&next!=='de')return;locale=next;if(persist)try{localStorage.setItem(LOCALE_KEY,next);}catch{}updateDocument();for(const listener of listeners)listener();}
function subscribe(listener:()=>void){listeners.add(listener);return()=>{listeners.delete(listener);};}
export function useLocale(){const current=useSyncExternalStore(subscribe,getLocale,()=>'en' as Locale);useEffect(updateDocument,[current]);return [current,setLocale] as const;}
export function t(key:TranslationKey,values:Record<string,string|number>={}):string {const template=locale==='en'?english[key]:germanOverrides[key]??key;return template.replace(/\{(\d+)\}/g,(match,index)=>values[index]===undefined?match:String(values[index]));}
/** Re-localize stored UI notices; unknown provider/server text stays original. */
export function ui(message:string):string {if(Object.prototype.hasOwnProperty.call(english,message))return t(message as TranslationKey);for(const key of Object.keys(english) as TranslationKey[])if(english[key]===message || germanOverrides[key]===message)return t(key);return message;}
export function translatedLabels<T extends Record<string,TranslationKey>>(source:T):{[K in keyof T]:string}{const result={} as {[K in keyof T]:string};for(const key of Object.keys(source) as (keyof T)[])Object.defineProperty(result,key,{enumerable:true,get:()=>t(source[key])});return result;}
if(typeof window!=='undefined')window.addEventListener('storage',event=>{if(event.key===LOCALE_KEY)setLocale(event.newValue==='de'?'de':'en',false);});

const apiErrors:Record<string,TranslationKey>={"operator_boundary_required": "Bitte den freigegebenen Operator-Zugang verwenden.", "loopback_required": "Dieser Zugang ist nur lokal verfügbar.", "invalid_host": "Diese Manager-Adresse ist nicht freigegeben.", "invalid_origin": "Diese Browser-Adresse ist nicht für den Manager freigegeben.", "cross_site": "Anfragen von anderen Websites sind gesperrt.", "invalid_framing": "Das Anfrageformat wird nicht unterstützt.", "invalid_path": "Der angeforderte Pfad ist ungültig.", "not_found": "Der angeforderte Eintrag wurde nicht gefunden.", "invalid_query": "Diese Abfrage wird nicht unterstützt.", "method_not_allowed": "Diese Aktion wird nicht unterstützt.", "storage_error": "Der lokale Zustand konnte nicht gelesen oder gespeichert werden.", "origin_required": "Änderungen sind nur über dieselbe Manager-Adresse erlaubt.", "csrf_required": "Der Zugriffstoken ist nicht mehr gültig. Status erneut prüfen.", "json_required": "Die Anfrage muss im JSON-Format vorliegen.", "body_too_large": "Die Anfrage überschreitet die erlaubte Größe.", "invalid_body": "Die Anfrage konnte nicht gelesen werden.", "invalid_json": "Die Anfrage enthält ungültige oder unerwartete Felder.", "invalid_note": "Die Notiz muss 1 bis 2000 UTF-8-Bytes enthalten.", "invalid_status": "Der gewählte Fallstatus ist ungültig.", "local_limit": "Das Limit für den lokalen Fallverlauf wurde erreicht.", "ui_not_built": "Die Oberfläche wurde auf dem Manager noch nicht gebaut.", "invalid_ai_config": "Anbieter-Einstellungen ungültig. Ziel, Modell und neuen Schlüssel prüfen.", "config_revision_mismatch": "Anbieter-Einstellungen wurden geändert. Aktuelles Ziel erneut prüfen.", "configuration_error": "Die Anbieter-Einstellungen konnten nicht geändert werden.", "analysis_busy": "Eine andere Analyse läuft oder wird abgebrochen.", "authentication_required": "Die Sitzung ist abgelaufen. Bitte erneut anmelden.", "case_evidence_invalid": "Die Fallbelege konnten nicht sicher für die Analyse vorbereitet werden.", "tls_required": "Dieser Operator-Zugang erfordert HTTPS.", "ambiguous_session_cookie": "Mehrdeutige Sitzungsdaten. Bitte neu anmelden.", "invalid_credentials": "Anmeldung nicht möglich. Passwort prüfen.", "login_rate_limited": "Zu viele Anmeldeversuche. Bitte später erneut versuchen.", "authentication_busy": "Anmeldung vorübergehend nicht verfügbar."};
export function apiErrorText(code:unknown,fallback:string):string{return typeof code==="string"&&Object.prototype.hasOwnProperty.call(apiErrors,code)?t(apiErrors[code]):fallback;}
