import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import App from './App';
import { LanguageSelector } from './LanguageSelector';
import { EvidenceCard, Status } from './components';
import { apiErrorText, getLocale, initialLocale, LOCALE_KEY, setLocale, t, ui, useLocale } from './i18n';
import { fullDate, relativeTime, statusLabels } from './utils';
import { english } from './translations';
import { request } from './api';
vi.mock('./api',async original=>({...await original<typeof import('./api')>(),request:vi.fn()}));
const session={mode:'development',transport:'http',insecureTestMode:false,transportWarning:null,authenticationRequired:false,authenticated:false,csrfToken:'dev-fixture',serverNow:'2026-10-03T15:00:00Z',expiresAt:null,expiresInSeconds:null};
const overview={generatedAt:'2026-10-03T15:00:00Z',stats:{totalDevices:0,healthyDevices:0,attentionDevices:0,openCases:0,criticalCases:0},devices:[],cases:[],activity:[]};
beforeEach(()=>{localStorage.clear();sessionStorage.clear();setLocale('en',false);window.location.hash='/devices';vi.mocked(request).mockImplementation(async path=>path==='/auth/session'?session:overview);});
afterEach(()=>{cleanup();vi.restoreAllMocks();setLocale('de',false);});
describe('explicit English-default locale',()=>{
 it('defaults to English independently of browser language and invalid stored state',()=>{vi.spyOn(navigator,'language','get').mockReturnValue('de-DE');expect(initialLocale()).toBe('en');localStorage.setItem(LOCALE_KEY,'"de"');expect(initialLocale()).toBe('en');localStorage.setItem(LOCALE_KEY,'de');expect(initialLocale()).toBe('de');});
 it('renders the actual workspace in English then switches without refetching or navigating',async()=>{render(<App/>);await screen.findByRole('heading',{name:'Devices',level:1});expect(screen.getByLabelText('Search devices')).toBeVisible();expect(document.documentElement.lang).toBe('en');expect(screen.getByLabelText('Switch to dark theme')).toBeVisible();const calls=vi.mocked(request).mock.calls.length;fireEvent.change(screen.getByLabelText('Language'),{target:{value:'de'}});expect(screen.getByRole('heading',{name:'Geräte',level:1})).toBeVisible();expect(screen.getByLabelText('Geräte durchsuchen')).toBeVisible();expect(localStorage.getItem(LOCALE_KEY)).toBe('de');expect(window.location.hash).toBe('#/devices');expect(request).toHaveBeenCalledTimes(calls);expect(document.documentElement.lang).toBe('de');});
 it('switches labels and time formatting but preserves original evidence verbatim',()=>{const raw='<script>nicht übersetzen</script>';function Sample(){useLocale();return <><LanguageSelector/><Status status="unknown"/><EvidenceCard index={0} evidence={{id:'raw-evidence',title:'Gerätefehler im Original',source:raw,detail:raw,value:raw,collectedAt:'2026-10-03T15:00:00Z',quality:'stale',synthetic:true}}/></>;}const{container}=render(<Sample/>);expect(screen.getByText('Unknown')).toBeVisible();expect(screen.getByText('Gerätefehler im Original')).toBeVisible();fireEvent.click(container.querySelector('summary')!);expect(container.textContent).toContain(raw);expect(container.querySelector('script')).toBeNull();const enDate=fullDate('2026-10-03T15:00:00Z');fireEvent.change(screen.getByLabelText('Language'),{target:{value:'de'}});expect(screen.getByText('Unbekannt')).toBeVisible();expect(statusLabels.stale).toBe('Veraltet');expect(fullDate('2026-10-03T15:00:00Z')).not.toBe(enDate);expect(container.textContent).toContain(raw);});
 it('localizes relative dates and stored notices, leaving arbitrary source text untouched',()=>{expect(relativeTime('0001-01-01T00:00:00Z')).toBe('Time unknown');expect(relativeTime('2026-10-02T15:00:00Z',Date.parse('2026-10-03T15:00:00Z'))).toBe('1 day ago');expect(ui('Notiz lokal gespeichert.')).toBe('Note saved locally.');expect(ui('Original event from service X')).toBe('Original event from service X');setLocale('de',false);expect(ui('Note saved locally.')).toBe('Notiz lokal gespeichert.');});
 it('keeps interpolation placeholders identical across both translations',()=>{for(const[key,value]of Object.entries(english)){const extract=(text:string)=>Array.from(text.matchAll(/\{(\d+)\}/g),match=>match[1]).sort();expect(extract(value),key).toEqual(extract(key));}expect(t('Geräte: {0} · Demo: {1} · lokal: {2}',{0:3,1:2,2:1})).toContain('3');});
 it('localizes known API error codes and safely retains unknown diagnostics',()=>{expect(apiErrorText('config_revision_mismatch','original')).toBe('Provider settings changed. Review the current destination again.');expect(apiErrorText('constructor','original')).toBe('original');expect(apiErrorText(null,'raw diagnostic')).toBe('raw diagnostic');setLocale('de',false);expect(apiErrorText('invalid_note','original')).toContain('UTF-8-Bytes');});
 it('responds to a locale change from another tab without storing secrets',()=>{act(()=>window.dispatchEvent(new StorageEvent('storage',{key:LOCALE_KEY,newValue:'de'})));expect(getLocale()).toBe('de');expect(localStorage.getItem(LOCALE_KEY)).toBeNull();});
});

describe('LAN inventory without observations',()=>{
 it('renders the real awaiting-agent contract without demo, Linux or healthy claims',async()=>{const metric={value:null,unit:'%',quality:'unknown',source:'Awaiting authenticated agent observation',collectedAt:'0001-01-01T00:00:00Z'};const device={id:'agent_fixture',name:'Fixture workstation',platform:'unknown',os:'Awaiting agent',site:'Local network',group:'Managed devices',ip:null,status:'unknown',source:'lan',synthetic:false,lastSeen:'0001-01-01T00:00:00Z',agentVersion:'unknown',cpu:metric,memory:metric,disk:metric,uptime:'Unknown',tags:[],capabilities:[],evidence:[],trend:[],caseIds:[]};const lanSession={...session,mode:'lan',transport:'https',authenticationRequired:true,authenticated:true,expiresAt:'2026-10-03T15:30:00Z',expiresInSeconds:1800};vi.mocked(request).mockImplementation(async path=>path==='/auth/session'?lanSession:path.startsWith('/devices/')?device:{...overview,mode:'lan-tls-pilot',devices:[device],stats:{...overview.stats,totalDevices:1,unknownDevices:1}});render(<App/>);await screen.findByRole('heading',{name:'Devices',level:1});expect(screen.queryByRole('button',{name:/^Demo devices/})).not.toBeInTheDocument();expect(screen.getByRole('button',{name:/^LAN agents/})).toBeVisible();expect(screen.getByText('Time unknown')).toBeVisible();expect(screen.getByText('LAN agent')).toBeVisible();expect(document.querySelector('.device-table .status-healthy')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Open details: Fixture workstation'}));await screen.findByRole('dialog',{name:'Device Fixture workstation'});expect(screen.getByText('Approved LAN agent. Metrics appear only after an accepted sample.')).toBeVisible();expect(document.body.textContent).not.toContain('0001');expect(document.body.textContent).not.toContain('Local Linux environment');});
});
