import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { abortProtectedRequests, request } from './api';
import { setLocale } from './i18n';
import { InvestigationList, InvestigationsPage } from './investigations';
import { useInvestigations } from './investigations-resource';
import { INVESTIGATIONS_BYTES, validInvestigationsView } from './investigations-types';
import type { InvestigationsView } from './investigations-types';
import goFixture from './proactive-ai-go-fixture.json';
import type { InvestigationAnalysis } from './investigation-analysis-types';

const now = '2026-10-07T08:00:00Z', earlier = '2026-10-07T07:57:00Z', id = 'agent_00000000000000000000000000000001';
function fixture(): InvestigationsView {
    const incident = { id: 'health_0000000000000001', key: 'filesystem:root', kind: 'filesystem' as const, target: '/', openedAt: earlier, lastObservedAt: now, resolvedAt: null, acknowledgedAt: null };
    const provenance = { method: 'ai', provider: 'openai-compatible', model: 'fixture-model', promptVersion: 'tracebolt.diagnostics-prompt.v1', runbookVersion: 'tracebolt.read-only-runbooks.v1', ruleId: 'health:filesystem', packetSHA256: 'a'.repeat(64), destination: 'https://api.example.com/v1', endpointOrigin: 'https://api.example.com' };
    const result = {
        schemaVersion: 'tracebolt.analysis.v1', id: 'analysis-fixture', fingerprint: 'b'.repeat(64), generatedAt: now,
        packet: { schemaVersion: 'tracebolt.evidence-packet.v1', dataScope: 'health-summary-v1', case: { id: incident.id, title: 'Root filesystem nearly full', summary: 'The manager confirmed root filesystem usage above the threshold.', category: 'filesystem', ruleId: 'health:filesystem', runbookId: 'storage', createdAt: earlier, updatedAt: now, synthetic: false },
            evidence: [{ id: 'health-event', title: 'Confirmed rule event', source: 'manager.health.incident', quality: 'healthy' as const, collectedAt: earlier, detail: 'Confirmed rule transition, not all underlying samples.', value: 'filesystem', synthetic: false }, { id: 'health-snapshot', title: 'Check at analysis admission', source: 'manager.health.check', quality: 'healthy' as const, collectedAt: now, detail: 'Current check snapshot for /.', value: '95.00 %', synthetic: false }],
            missingEvidenceIDs: [], observationWindow: { from: earlier, to: now }, gaps: [{ code: 'no-logs', evidenceIDs: [], detail: 'No journal content was requested or searched.' }] },
        baseline: { summary: 'Observed storage warning.', evidenceIDs: ['health-event', 'health-snapshot'], nextCheck: 'storage', nextSteps: ['Inspect storage usage read-only.'], provenance },
        ai: { status: 'completed' as const, reason: 'Unverified suggestions.', findings: { observedEvidenceIDs: ['health-event', 'health-snapshot'], hypotheses: [{ statement: 'Accumulated files might explain the usage.', evidenceIDs: ['health-snapshot'] }], counterevidence: [{ statement: 'Only the current usage is known.', evidenceIDs: ['health-snapshot'] }], missingData: ['No historical samples.'], nextCheck: 'storage' }, nextSteps: ['Review mount usage read-only.'], provenance },
        rootCauseConfirmed: false as const, limitations: ['Suggestions need human review.'],
    };
    return { schemaVersion: 'tracebolt.investigations.v1', serverNow: now, scope: 'open', offset: 0, total: 1, counts: { open: 1, recovered: 0, closed: 0, all: 1 }, devices: [{ schemaVersion: 'tracebolt.health-view.v1', deviceId: id, serverNow: now, evaluatedAt: now, status: 'attention', maintenanceUntil: null, monitoredServices: [], checks: [{ key: 'offline:contact', kind: 'offline', target: 'agent', state: 'ok', observedAt: now, value: null }, { key: 'filesystem:root', kind: 'filesystem', target: '/', state: 'open', observedAt: now, value: 95 }], incidents: [] }], items: [{ deviceId: id, incident, analysis: { status: 'completed', createdAt: now, finishedAt: now, recoveredAt: null, result } }] };
}
const analysis = (value: InvestigationsView) => value.items[0].analysis!;
const result = (value: InvestigationsView) => analysis(value).result!;
function Harness() { const resource = useInvestigations(true, 'fixture-session', 'cases'); return <InvestigationsPage resource={resource} devices={[]} scope="open" offset={0} onScope={() => {}} onPage={() => {}}/>; }
const json = (value: unknown) => new Response(JSON.stringify(value));
beforeEach(() => { setLocale('en', false); localStorage.clear(); sessionStorage.clear(); });
afterEach(() => { cleanup(); abortProtectedRequests(); vi.restoreAllMocks(); vi.unstubAllGlobals(); });

describe('optional bounded stored-analysis contract', () => {
    it('accepts the exact synthetic Go API result contract', () => { expect(validInvestigationsView(goFixture, 'open', 0)).toBe(true); });
    it('rejects inner/outer status disagreement', () => { const value = fixture(); analysis(value).status = 'canceled'; expect(validInvestigationsView(value, 'open', 0)).toBe(false); });
    it('accepts old investigation payloads and the complete analysis extension', () => { const value = fixture(); expect(validInvestigationsView(value, 'open', 0)).toBe(true); delete value.items[0].analysis; expect(validInvestigationsView(value, 'open', 0)).toBe(true); });
    it.each(['running', 'timeout', 'unavailable', 'invalid_response', 'canceled', 'interrupted', 'not_configured', 'busy', 'completed'] as const)('accepts safe %s records without inventing a result', status => { const value = fixture(); value.items[0].analysis = { status, createdAt: now, finishedAt: status === 'running' ? null : now, recoveredAt: null, result: null }; expect(validInvestigationsView(value, 'open', 0)).toBe(true); });
    it('rejects null, unknown or expanded analysis records', () => { for (const extension of [null, {}, { ...analysis(fixture()), status: 'confirmed' }, { ...analysis(fixture()), extra: true }, { ...analysis(fixture()), createdAt: '2026-02-31T00:00:00Z' }, { ...analysis(fixture()), finishedAt: earlier }, { ...analysis(fixture()), status: 'running' }]) { const value = fixture(); value.items[0].analysis = extension as InvestigationAnalysis; expect(validInvestigationsView(value, 'open', 0)).toBe(false); } });
    it('rejects invalid citations, false root-cause certainty and foreign incident data', () => { const certainty = fixture(); result(certainty).rootCauseConfirmed = true as never; const citation = fixture(); result(citation).ai.findings!.hypotheses[0].evidenceIDs = ['unrelated-secret']; const foreign = fixture(); result(foreign).packet.case.id = 'health_0000000000000002'; const duplicate = fixture(); result(duplicate).packet.evidence[1].id = 'health-event'; const malformed = fixture(); result(malformed).packet.evidence[0].collectedAt = 'tomorrow'; for (const value of [certainty, citation, foreign, duplicate, malformed]) expect(validInvestigationsView(value, 'open', 0)).toBe(false); });
    it('requires explicit typed scope and exactly the two health evidence IDs', () => { const missingScope = fixture(); delete (result(missingScope).packet as unknown as Record<string, unknown>).dataScope; const wrongScope = fixture(); Object.assign(result(wrongScope).packet, { dataScope: 'raw-logs' }); const extra = fixture(); result(extra).packet.evidence.push({ ...result(extra).packet.evidence[0], id: 'raw-log' }); const renamed = fixture(); result(renamed).packet.evidence[0].id = 'raw-log'; const profile = fixture(); Object.assign(result(profile).packet.evidence[0], { collectionProfile: 'managed-operations-v1' }); for (const value of [missingScope, wrongScope, extra, renamed, profile]) expect(validInvestigationsView(value, 'open', 0)).toBe(false); });
    it('rejects empty citations and claims citing evidence the model did not observe', () => { const empty = fixture(); result(empty).ai.findings!.hypotheses[0].evidenceIDs = []; const unobserved = fixture(); result(unobserved).ai.findings!.observedEvidenceIDs = ['health-event']; const counter = fixture(); result(counter).ai.findings!.counterevidence[0].evidenceIDs = []; for (const value of [empty, unobserved, counter]) expect(validInvestigationsView(value, 'open', 0)).toBe(false); });
    it('binds recovery to the same recovered health incident', () => { const value = fixture(); analysis(value).recoveredAt = now; expect(validInvestigationsView(value, 'open', 0)).toBe(false); value.items[0].incident.resolvedAt = now; value.items[0].incident.closedReason = 'monitoring_stopped'; value.scope = 'all'; value.counts = { open: 0, recovered: 0, closed: 1, all: 1 }; expect(validInvestigationsView(value, 'all', 0)).toBe(false); value.items[0].incident.closedReason = 'recovered'; value.counts = { open: 0, recovered: 1, closed: 0, all: 1 }; expect(validInvestigationsView(value, 'all', 0)).toBe(true); analysis(value).recoveredAt = earlier; expect(validInvestigationsView(value, 'all', 0)).toBe(false); });
    it('rejects excessive record bytes and unbounded model content', () => { const oversized = fixture(); result(oversized).limitations = Array.from({ length: 16 }, () => 'x'.repeat(2048)); expect(validInvestigationsView(oversized, 'open', 0)).toBe(false); const text = fixture(); result(text).ai.findings!.hypotheses[0].statement = 'x'.repeat(513); expect(validInvestigationsView(text, 'open', 0)).toBe(false); });
    it('allows original stale offline evidence without changing its timestamp', () => { const value = fixture(), incident = value.items[0].incident; incident.kind = 'offline'; incident.key = 'offline:contact'; incident.target = 'agent'; value.devices[0].checks[0].state = 'open'; const packet = result(value).packet; Object.assign(packet.case, { category: 'offline', ruleId: 'health:offline' }); packet.evidence[1].collectedAt = '2026-10-07T07:00:00Z'; packet.evidence[1].quality = 'stale'; packet.observationWindow.from = packet.evidence[1].collectedAt; packet.observationWindow.to = earlier; expect(validInvestigationsView(value, 'open', 0)).toBe(true); });
});
describe('read-only durable analysis presentation', () => {
    it('shows only a concise hypothesis in overview cards', () => { render(<InvestigationList view={fixture()} devices={[]} concise onAll={() => {}}/>); expect(screen.getByText(/Unconfirmed hypothesis: Accumulated files/)).toBeVisible(); expect(screen.queryByText('AI analysis & sources')).not.toBeInTheDocument(); expect(screen.queryByText('Review mount usage read-only.')).not.toBeInTheDocument(); });
    it('reads stored results on remount without triggering a run, then shows evidence and read-only guidance', async () => { const fetch = vi.fn().mockImplementation(() => Promise.resolve(json(fixture()))); vi.stubGlobal('fetch', fetch); const mounted = render(<Harness/>); await screen.findByText('AI suggestions saved'); mounted.unmount(); render(<Harness/>); await screen.findByText('AI suggestions saved'); fireEvent.click(screen.getByText('AI analysis & sources')); expect(screen.getByText(/Unconfirmed hypotheses\./)).toBeVisible(); expect(screen.getByRole('heading',{name:'Hypotheses'})).toBeVisible(); expect(screen.getByText('Sources')).toBeVisible(); expect(screen.getByText('health-event', { selector: 'strong' })).toBeVisible(); expect(screen.getAllByText(/Source quality at analysis: Current/)).toHaveLength(2); expect(screen.queryByText('healthy', { exact: true })).not.toBeInTheDocument(); expect(document.querySelector(`time[datetime="${earlier}"]`)).toBeInTheDocument(); expect(screen.getByText('No historical samples.')).toBeVisible(); expect(screen.getByText('Review mount usage read-only.')).toBeVisible(); expect(screen.getByText(/No additional logs or historical samples were checked/)).toBeVisible(); expect(fetch).toHaveBeenCalledTimes(2); expect(fetch.mock.calls.every(([path, options]) => path === '/api/investigations?scope=open&offset=0' && !options.method && !options.body)).toBe(true); expect(screen.queryByRole('button', { name: /Analyze|Run|Restart|Retry analysis/ })).not.toBeInTheDocument(); });
    it('treats model text as inert content and never turns it into actions', () => { const value = fixture(), payload = '<img src=x onerror=alert(1)><script>steal()</script> https://unsafe.example'; result(value).ai.findings!.hypotheses[0].statement = payload; const { container } = render(<InvestigationList view={value} devices={[]}/>); fireEvent.click(screen.getByText('AI analysis & sources')); expect(screen.getByText(payload, { selector: 'li' })).toBeVisible(); expect(container.querySelector('img,script')).toBeNull(); expect(container.querySelector('a[href="https://unsafe.example"]')).toBeNull(); });
    it('describes recovery as separate from proof of a hypothesis', () => { const value = fixture(); analysis(value).recoveredAt = now; value.items[0].incident.resolvedAt = now; value.items[0].incident.closedReason = 'recovered'; render(<InvestigationList view={value} devices={[]}/>); fireEvent.click(screen.getByText('AI analysis & sources')); expect(screen.getByText(/This does not confirm an AI hypothesis/)).toBeVisible(); });
    it('keeps failed/interrupted results clearly unavailable without claiming diagnosis', () => { const value = fixture(); Object.assign(analysis(value), { status: 'interrupted', result: null }); render(<InvestigationList view={value} devices={[]}/>); expect(screen.getByText('AI analysis interrupted')).toBeVisible(); fireEvent.click(screen.getByText('AI analysis & sources')); expect(screen.getByText(/No stored AI result is available/)).toBeVisible(); expect(screen.queryByRole('heading',{name:'Hypotheses'})).not.toBeInTheDocument(); });
    it('localizes stored result labels to German', () => { setLocale('de', false); render(<InvestigationList view={fixture()} devices={[]}/>); fireEvent.click(screen.getByText('KI-Analyse & Quellen')); expect(screen.getByRole('heading',{name:'Hypothesen'})).toBeVisible(); expect(screen.getByText(/Unbestätigte Hypothesen/)).toBeVisible(); });
});
describe('investigations response byte boundary', () => {
    it('permits the new cap only on canonical investigation GET paths', async () => { const fetch = vi.fn().mockImplementation(() => Promise.resolve(json({ padded: 'x'.repeat(300000) }))); vi.stubGlobal('fetch', fetch); await expect(request('/investigations?scope=open&offset=0', {}, INVESTIGATIONS_BYTES)).resolves.toHaveProperty('padded'); for (const path of ['/ai/proactive', '/investigations?scope=open&offset=0&extra=true', '/investigations?scope=unknown&offset=0']) await expect(request(path, {}, INVESTIGATIONS_BYTES)).rejects.toThrow(); expect(fetch).toHaveBeenCalledTimes(1); });
});
