import { useEffect, useId, useRef, useState } from 'react';
import { ArrowRight, Check, ChevronDown, ChevronLeft, ChevronRight, Clock3, LoaderCircle, RefreshCw, Search, Server, SlidersHorizontal, TriangleAlert } from 'lucide-react';
import { Dialog } from './components';
import { useLocale } from './i18n';
import { journalReportedAccess, journalServiceLabel } from './journal-sources';
import { JournalServicePicker } from './journal-service-picker';
import { JournalSourceOptions, JournalSelectedSource, JournalPermissionSummary } from './journal-source-options';
import { useJournal } from './journal-resource';
import type { JournalResource } from './journal-resource';
import { journalBytes, journalFold, JOURNAL_SEARCH_BYTES, validJournalQuery, validJournalUnit } from './journal-types';
import type { JournalQuery } from './journal-types';
import './journal.css';
import { JournalBrowseContent } from './journal-browse';
const copy = {
    en: {
        title: 'Logs', source: 'Service', period: 'Period', fetch: 'Fetch logs', reviewTitle: 'Review log request', dismiss: 'Back', advanced: 'Advanced', custom: 'Custom window', ends: 'Draft ends', results: 'Results', sourceDetails: 'Permissions & sources', replace: 'This request replaces the current captured snapshot.', choose: 'Choose a service', reviewWindow: 'Requested window (UTC)', referenceDetails: 'Reference time & limits', generationStale: 'The endpoint policy report is stale. Refresh status after the endpoint reports again before capturing logs.', newCapture: 'Last 15 min', newCaptureHint: 'Check manager time and prepare the last 15 minutes. Review and approval are still required.', snapshotAt: 'Snapshot captured', snapshotAge: 'Age at last status check', emptyHint: 'Check the exact unit, time window and severity. Alias targets are not reported here; an alias may have no entries under its own name. Choose the unit used by the journal.', applied: 'Applied search', refresh: 'Refresh status', refreshReference: 'Refresh status and reference time', intro: 'Capture a short journal window from one locally permitted service.', service: 'Exact service unit', start: 'From (UTC)', end: 'To (UTC)', severity: 'Include severity through', recent: '15 minutes ending at reference time', recent5: '5 minutes ending at reference time', recent30: '30 minutes ending at reference time', recent60: '1 hour ending at reference time', presets: 'Windows ending at the displayed reference time', presetHint: 'Reference time may be old. Refresh status, then choose a window; this does not capture logs.', managerTime: 'Last checked manager time (UTC)', chooseService: 'Choose observed service', manualService: 'Observed names do not confirm local permission.', capture: 'Capture logs', cancel: 'Cancel request / discard content',
        limits: 'Up to 1 hour within the last 24 hours. At most 500 captured rows / 512 KiB. Content expires 15 minutes after the request was created.',
        allowlist: 'The endpoint rechecks its local service grant and query limits for every capture. This page displays the last reported grant and cannot enable local access.',
        ack: 'I understand that log messages may contain credentials, personal data or other secrets, even after masking.', privacy: 'Masking is best effort and does not make log messages safe or anonymous.', reviewDetails: 'Limits & privacy', emptyHelp: 'Why is this empty?',
        plaintext: 'I also accept that this HTTP test sends log content over an unencrypted connection.',
        loading: 'Reading journal status or captured content…', paused: 'Content paused. Return here or refresh status to recheck access; no new capture starts.', waiting: 'Journal status is not loaded. Refresh status to continue.', configured: 'Not configured', configuredHint: 'This device needs the separate journal extension.', awaiting: 'Awaiting a request', awaitingHint: 'Choose a service, then fetch logs.',
        pending: 'Pending', pendingHint: 'Waiting for the agent to check its local permission. No content is available yet.', claimed: 'Claimed', claimedHint: 'The agent claimed this one-shot request. Collection is not yet confirmed.', available: 'Captured snapshot available', failed: 'Collection failed', denied: 'Local access denied', disabled: 'Local journal access disabled', helper_unavailable: 'Local journal helper unavailable', result_lost: 'Content lost / unavailable', lostHint: 'Retained content is unavailable. Refresh status to check again; no automatic recapture.', expired: 'Expired', expiredHint: 'The original retention window ended. Log rows have been cleared.', canceled: 'Canceled', canceledHint: 'This request no longer grants collection or content access.', unavailable: 'Captured content unavailable',
        search: 'Search captured messages', searchButton: 'Search capture', searchHint: 'Literal, case-insensitive search in this snapshot only. No live or whole-journal search.', searchLimit: 'Use at most 128 UTF-8 bytes.', previous: 'Previous', next: 'Next', empty: 'The complete capture contains no matching journal entries.', noMatches: 'No literal matches in this captured snapshot.', partialEmpty: 'No rows were retained; coverage is partial, so this is not evidence of an empty journal.', captured: 'captured', matches: 'matches', showing: 'Showing', partial: 'Partial coverage', complete: 'Complete coverage for the requested window visible to the agent', observed: 'Observed before capture limits', expires: 'Content expires', timestamp: 'Time (UTC)', priority: 'Severity', message: 'Message', details: 'Limits & privacy', unitHint: 'Example: example.service. No wildcards or shell expressions.', invalidForm: 'Choose one exact service, a UTC window of at most 1 hour within the last 24 hours, and severity 0–7.',
        load: 'The journal status or content could not be read. Refresh status before continuing.', invalid: 'The manager returned inconsistent or unsupported journal data. Rows were cleared.', timeout: 'The read timed out. Refresh status to try again.', session: 'Your session has ended. Sign in again.', clock: 'The time or request sequence is no longer reliable. Rows were cleared; refresh status.', conflict: 'The request or snapshot changed, expired or became unavailable. Refresh status.', uncertain: 'The action’s outcome is uncertain. Status is being checked; the action will not be repeated automatically.', uncertainHeld: 'The last action could not be confirmed. Refresh status before issuing another action.',
        cursor_unavailable: 'The source cursor is no longer available. Start a new query; retention or rotation may have removed entries.', none: 'No failure reported', permission_denied: 'Permission denied', source_missing: 'Journal source missing', invalid_source: 'Invalid journal source', read_failed: 'Journal read failed', sourceTimeout: 'Collection timed out', item_limit: 'Row limit reached', byte_limit: 'Byte limit reached', visibility_restricted: 'Source visibility restricted', not_supported: 'Source not supported', collector_busy: 'Collector busy',
    },
    de: {
        title: 'Logs', source: 'Dienst', period: 'Zeitraum', fetch: 'Logs abrufen', reviewTitle: 'Log-Anfrage prüfen', dismiss: 'Zurück', advanced: 'Erweitert', custom: 'Eigener Zeitraum', ends: 'Entwurf bis', results: 'Ergebnisse', sourceDetails: 'Freigabe & Quellen', replace: 'Diese Anfrage ersetzt den aktuell erfassten Snapshot.', choose: 'Dienst auswählen', reviewWindow: 'Angefragter Zeitraum (UTC)', referenceDetails: 'Referenzzeit & Grenzen', generationStale: 'Die Richtlinienmeldung des Endpunkts ist veraltet. Nach einer neuen Meldung den Status aktualisieren, bevor Logs erfasst werden.', newCapture: 'Letzte 15 Min.', newCaptureHint: 'Managerzeit prüfen und die letzten 15 Minuten vorbereiten. Prüfung und Zustimmung bleiben erforderlich.', snapshotAt: 'Snapshot erfasst', snapshotAge: 'Alter bei letzter Statusprüfung', emptyHint: 'Exakte Unit, Zeitraum und Schweregrad prüfen. Alias-Ziele werden hier nicht gemeldet; ein Alias kann unter seinem eigenen Namen ohne Einträge sein. Die im Journal verwendete Unit wählen.', applied: 'Angewendete Suche', refresh: 'Status aktualisieren', refreshReference: 'Status und Referenzzeit aktualisieren', intro: 'Ein kurzes Journal-Zeitfenster für genau einen lokal freigegebenen Dienst erfassen.', service: 'Exakte Service-Unit', start: 'Von (UTC)', end: 'Bis (UTC)', severity: 'Schweregrade bis einschließlich', recent: '15 Minuten bis zur Referenzzeit', recent5: '5 Minuten bis zur Referenzzeit', recent30: '30 Minuten bis zur Referenzzeit', recent60: '1 Stunde bis zur Referenzzeit', presets: 'Zeitfenster bis zur angezeigten Referenzzeit', presetHint: 'Die Referenzzeit kann veraltet sein. Status aktualisieren, dann Zeitraum wählen; das erfasst keine Logs.', managerTime: 'Zuletzt geprüfte Managerzeit (UTC)', chooseService: 'Beobachteten Dienst wählen', manualService: 'Beobachtete Namen bestätigen keine lokale Freigabe.', capture: 'Logs erfassen', cancel: 'Anfrage abbrechen / Inhalt verwerfen',
        limits: 'Höchstens 1 Stunde innerhalb der letzten 24 Stunden. Maximal 500 erfasste Zeilen / 512 KiB. Inhalte laufen 15 Minuten nach Erstellung der Anfrage ab.',
        allowlist: 'Der Endpunkt prüft die lokale Dienstfreigabe und Anfragegrenzen bei jeder Erfassung erneut. Diese Seite zeigt die zuletzt gemeldete Freigabe und kann lokalen Zugriff nicht aktivieren.',
        ack: 'Ich verstehe, dass Log-Nachrichten trotz Maskierung Zugangsdaten, personenbezogene Daten oder andere Geheimnisse enthalten können.', privacy: 'Maskierung ist nur bestmöglich und macht Log-Nachrichten nicht sicher oder anonym.', reviewDetails: 'Grenzen & Datenschutz', emptyHelp: 'Warum ist die Erfassung leer?',
        plaintext: 'Ich akzeptiere zusätzlich, dass dieser HTTP-Test Log-Inhalte unverschlüsselt überträgt.',
        loading: 'Journal-Status oder erfasster Inhalt wird gelesen…', paused: 'Inhalt pausiert. Zur Seite zurückkehren oder Status aktualisieren; keine neue Erfassung.', waiting: 'Der Journalstatus ist nicht geladen. Zum Fortfahren den Status aktualisieren.', configured: 'Nicht konfiguriert', configuredHint: 'Dieses Gerät benötigt die separate Journal-Erweiterung.', awaiting: 'Wartet auf eine Anfrage', awaitingHint: 'Dienst wählen, dann Logs abrufen.',
        pending: 'Ausstehend', pendingHint: 'Der Agent muss die lokale Freigabe noch prüfen. Noch kein Inhalt verfügbar.', claimed: 'Übernommen', claimedHint: 'Der Agent hat diese einmalige Anfrage übernommen. Die Erfassung ist noch nicht bestätigt.', available: 'Erfasster Snapshot verfügbar', failed: 'Erfassung fehlgeschlagen', denied: 'Lokaler Zugriff verweigert', disabled: 'Lokaler Journal-Zugriff deaktiviert', helper_unavailable: 'Lokaler Journal-Helper nicht verfügbar', result_lost: 'Inhalt verloren / nicht verfügbar', lostHint: 'Gespeicherter Inhalt nicht verfügbar. Status erneut prüfen; keine automatische Neuerfassung.', expired: 'Abgelaufen', expiredHint: 'Die ursprüngliche Aufbewahrungsfrist ist beendet. Log-Zeilen wurden entfernt.', canceled: 'Abgebrochen', canceledHint: 'Diese Anfrage erlaubt weder weitere Erfassung noch Inhaltszugriff.', unavailable: 'Erfasster Inhalt nicht verfügbar',
        search: 'Erfasste Nachrichten durchsuchen', searchButton: 'Snapshot durchsuchen', searchHint: 'Wörtliche Suche im Snapshot, unabhängig von Groß-/Kleinschreibung. Keine Live- oder Gesamtsuche.', searchLimit: 'Höchstens 128 UTF-8-Bytes verwenden.', previous: 'Zurück', next: 'Weiter', empty: 'Die vollständige Erfassung enthält keine passenden Journal-Einträge.', noMatches: 'Keine wörtlichen Treffer in diesem erfassten Snapshot.', partialEmpty: 'Keine Zeilen behalten; die Erfassung ist teilweise und belegt kein leeres Journal.', captured: 'erfasst', matches: 'Treffer', showing: 'Anzeige', partial: 'Teilweise Abdeckung', complete: 'Vollständige Abdeckung des angefragten, für den Agent sichtbaren Zeitfensters', observed: 'Vor Erfassungsgrenzen beobachtet', expires: 'Inhalt läuft ab', timestamp: 'Zeit (UTC)', priority: 'Schweregrad', message: 'Nachricht', details: 'Grenzen & Datenschutz', unitHint: 'Beispiel: example.service. Keine Platzhalter oder Shell-Ausdrücke.', invalidForm: 'Einen exakten Dienst, ein UTC-Zeitfenster von höchstens 1 Stunde innerhalb der letzten 24 Stunden und Schweregrad 0–7 wählen.',
        load: 'Journal-Status oder Inhalt konnte nicht gelesen werden. Vor dem Fortsetzen Status aktualisieren.', invalid: 'Der Manager hat widersprüchliche oder nicht unterstützte Journal-Daten geliefert. Zeilen wurden entfernt.', timeout: 'Das Lesen hat zu lange gedauert. Status zum Wiederholen aktualisieren.', session: 'Die Sitzung ist beendet. Bitte erneut anmelden.', clock: 'Zeit oder Anfragesequenz sind nicht mehr verlässlich. Zeilen wurden entfernt; Status aktualisieren.', conflict: 'Anfrage oder Snapshot wurde geändert, ist abgelaufen oder nicht mehr verfügbar. Status aktualisieren.', uncertain: 'Das Ergebnis ist unklar. Der Status wird geprüft; die Aktion wird nicht automatisch wiederholt.', uncertainHeld: 'Die letzte Aktion konnte nicht bestätigt werden. Vor einer weiteren Aktion den Status aktualisieren.',
        cursor_unavailable: 'Der Quellcursor ist nicht mehr verfügbar. Neue Suche starten; Aufbewahrung oder Rotation kann Einträge entfernt haben.', none: 'Kein Fehler gemeldet', permission_denied: 'Berechtigung verweigert', source_missing: 'Journal-Quelle fehlt', invalid_source: 'Ungültige Journal-Quelle', read_failed: 'Journal-Lesen fehlgeschlagen', sourceTimeout: 'Erfassungszeitlimit erreicht', item_limit: 'Zeilengrenze erreicht', byte_limit: 'Byte-Grenze erreicht', visibility_restricted: 'Quellensichtbarkeit eingeschränkt', not_supported: 'Quelle nicht unterstützt', collector_busy: 'Collector ausgelastet',
    },
};
const priorityNames = ['0 · Emergency', '1 · Alert', '2 · Critical', '3 · Error', '4 · Warning', '5 · Notice', '6 · Info', '7 · Debug'];
const inputTime = (s: string) => new Date(s).toISOString().slice(0, 19);
const displayTime = (value: string, locale: string, precise = false) => {
    const fraction = precise ? /\.(\d+)Z$/.exec(value)?.[1] : null;
    return new Intl.DateTimeFormat(locale === 'de' ? 'de-DE' : 'en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false, timeZone: 'UTC' }).formatToParts(new Date(value)).map(part => part.type === 'second' && fraction ? `${part.value}.${fraction}` : part.value).join('') + ' UTC';
};
// datetime-local may normalize a whole second with a fractional .000 suffix.
// Keep explicit UTC and the journal contract's maximum microsecond precision.
const utcInput = (s: string) => /^\d{4}-\d\d-\d\dT\d\d:\d\d(?::\d\d(?:\.\d{1,6})?)?$/.test(s) ? `${s.length === 16 ? `${s}:00` : s}Z` : '';
export function JournalHighlight({ text, search }: { text: string; search: string }) {
    if (!search) return <>{text}</>;
    const folded = journalFold(text), needle = journalFold(search), nodes = []; let at = 0, found = folded.indexOf(needle);
    while (found >= 0) { nodes.push(text.slice(at, found), <mark key={found}>{text.slice(found, found + needle.length)}</mark>); at = found + needle.length; found = folded.indexOf(needle, at); }
    nodes.push(text.slice(at)); return <>{nodes}</>;
}
type JournalPanelProps = { deviceId: string; insecureTestMode: boolean; sessionKey: string | null; initialUnit?: string };
export function JournalPanel(props: JournalPanelProps) {
    return <JournalSession key={`${props.deviceId}:${props.sessionKey ?? ''}:${props.insecureTestMode}`} {...props}/>;
}
function JournalSession({ deviceId, insecureTestMode, sessionKey, initialUnit }: JournalPanelProps) {
    return <JournalContent resource={useJournal(deviceId, insecureTestMode, sessionKey)} insecureTestMode={insecureTestMode} sessionKey={sessionKey} initialUnit={initialUnit}/>;
}
type JournalContentProps = { resource: JournalResource; insecureTestMode: boolean; sessionKey?: string | null; initialUnit?: string };
export function JournalContent(props: JournalContentProps) {
    const retained = useRef(false);
    if (props.resource.view?.generation?.schemaVersion === 'tracebolt.journal-generation-view.v3') retained.current = true;
    return retained.current ? <JournalBrowseContent {...props}/> : <LegacyJournalContent {...props}/>;
}
function LegacyJournalContent({ resource: r, insecureTestMode, sessionKey = null, initialUnit = '' }: JournalContentProps) {
    const [locale] = useLocale(), c = copy[locale], id = useId();
    const [unit, setUnit] = useState(() => validJournalUnit(initialUnit) ? initialUnit : ''), [start, setStart] = useState(''), [end, setEnd] = useState(''), [priority, setPriority] = useState(6);
    const [ack, setAck] = useState(false), [plainAck, setPlainAck] = useState(false), [search, setSearch] = useState(''), [pickerOpen, setPickerOpen] = useState(false), [preset, setPreset] = useState<number | null>(15);
    const [review, setReview] = useState<JournalQuery | null>(null), [preparingWindow, setPreparingWindow] = useState(false);
    const windowRead = useRef(0);
    useEffect(() => () => { windowRead.current++; }, []);
    const unitInput = useRef<HTMLInputElement>(null), pickerButton = useRef<HTMLButtonElement>(null), fetchButton = useRef<HTMLButtonElement>(null), advanced = useRef<HTMLDetailsElement>(null), submitting = useRef(false), windowInitialized = useRef(false), restorePickerFocus = useRef(false), restoreReviewFocus = useRef(false), statusRef = useRef<HTMLDivElement>(null);
    const view = r.view, request = view?.request, page = r.page;
    useEffect(() => { windowRead.current++; setPreparingWindow(false); setAck(false); setPlainAck(false); setSearch(''); setPickerOpen(false); setReview(null); restorePickerFocus.current = false; restoreReviewFocus.current = false; }, [r.reset]);
    useEffect(() => { if (!pickerOpen && restorePickerFocus.current) { restorePickerFocus.current = false; pickerButton.current?.focus(); } }, [pickerOpen]);
    useEffect(() => { if (!review && restoreReviewFocus.current) { restoreReviewFocus.current = false; (fetchButton.current?.disabled ? statusRef.current : fetchButton.current)?.focus(); } }, [review]);
    useEffect(() => { if (view && !windowInitialized.current) { windowInitialized.current = true; setEnd(inputTime(view.serverNow)); setStart(inputTime(new Date(Date.parse(view.serverNow) - 900000).toISOString())); } }, [view]);
    // Consent applies to the reviewed draft only. Ordinary status/metadata reads
    // do not reset inputs; editing any request field dismisses an older review.
    useEffect(() => { setReview(null); setAck(false); setPlainAck(false); }, [unit, start, end, priority]);
    const chooseWindow = (minutes: number, reference = view?.serverNow) => { if (!view?.configured || !reference) return; setEnd(inputTime(reference)); setStart(inputTime(new Date(Date.parse(reference) - minutes * 60000).toISOString())); setPreset(minutes); };
    const prepareRecentWindow = async () => {
        if (!view?.configured || r.busy || r.paused || r.uncertain || active || preparingWindow) return;
        const token = ++windowRead.current;
        setPreparingWindow(true); setReview(null); setAck(false); setPlainAck(false);
        try {
            const now = await r.refreshWindow();
            if (token === windowRead.current && now) chooseWindow(15, now);
        } finally { if (token === windowRead.current) setPreparingWindow(false); }
    };
    const chooseService = (name: string) => { if (!validJournalUnit(name)) return; setUnit(name); restorePickerFocus.current = true; setPickerOpen(false); };
    const closePicker = () => { restorePickerFocus.current = true; setPickerOpen(false); };
    const closeReview = () => { restoreReviewFocus.current = true; setReview(null); setAck(false); setPlainAck(false); };
    const query: JournalQuery = { unit, start: utcInput(start), end: utcInput(end), maxPriority: priority };
    const selectedPreset = view && preset !== null && end === inputTime(view.serverNow) && start === inputTime(new Date(Date.parse(view.serverNow) - preset * 60000).toISOString()) ? preset : null;
    const generationReady = !view?.generation || view.generation.fresh;
    const reportedAccess = journalReportedAccess(view, unit), scopeReady = reportedAccess !== 'reported_disabled' && reportedAccess !== 'outside_reported_scope';
    const valid = !!view && validJournalQuery(query, view.serverNow), active = !!request && ['pending', 'claimed'].includes(request.state);
    const canReview = Boolean(view?.configured && generationReady && scopeReady && valid && !preparingWindow && !r.busy && !r.paused && !r.uncertain && !active && r.failure !== 'session');
    const openReview = () => { if (!canReview || submitting.current) return; restorePickerFocus.current = false; setPickerOpen(false); setAck(false); setPlainAck(false); setReview({ ...query }); };
    const reviewed = review && review.unit === query.unit && review.start === query.start && review.end === query.end && review.maxPriority === query.maxPriority;
    const confirmCapture = () => {
        if (!review || !reviewed || !canReview || !ack || insecureTestMode && !plainAck || submitting.current) return;
        const approvedQuery = { ...review }, approvedContent = ack, approvedPlaintext = plainAck;
        submitting.current = true; closeReview(); setPickerOpen(false);
        void Promise.resolve(r.create(approvedQuery, approvedContent, approvedPlaintext)).finally(() => { submitting.current = false; });
    };
    const state = !view ? null : !view.configured ? 'configured' : !request ? 'awaiting' : request.state === 'expired' || request.state === 'canceled' ? request.state : ['disabled', 'denied', 'helper_unavailable', 'result_lost'].includes(view.localStatus) ? view.localStatus as 'disabled' | 'denied' | 'helper_unavailable' | 'result_lost' : page?.coverage === 'failed' ? 'failed' : view.contentStatus === 'available' ? 'available' : request.state === 'accepted' ? 'unavailable' : request.state;
    const hint = state === 'configured' ? c.configuredHint : state === 'awaiting' ? c.awaitingHint : state === 'pending' ? c.pendingHint : state === 'claimed' ? c.claimedHint : state === 'expired' ? c.expiredHint : state === 'canceled' ? c.canceledHint : state === 'result_lost' || state === 'unavailable' ? c.lostHint : null;
    const reason = page ? c[page.reason === 'timeout' ? 'sourceTimeout' : page.reason] : null;
    const serviceLabel = journalServiceLabel(unit, locale);
    return <section className="journal-panel detail-section" aria-labelledby={id} aria-busy={r.busy}>
        <header className="journal-heading"><h2 id={id}>{c.title}</h2><button type="button" className="button small" disabled={r.busy || r.failure === 'session'} onClick={r.refresh}><RefreshCw size={14}/>{c.refresh}</button></header>
        {r.failure && <p role="alert" className="journal-warning"><TriangleAlert size={16}/>{c[r.failure]}</p>}
        {r.uncertain && r.failure !== 'uncertain' && <p className="journal-warning">{c.uncertainHeld}</p>}
        {r.paused && !r.busy && !r.failure && <p role="status" className="journal-muted">{c.paused}</p>}
        {!view && !r.paused && !r.busy && !r.failure && <p role="status" className="journal-muted">{c.waiting}</p>}
        {r.busy && <p role="status" className="journal-muted"><LoaderCircle size={14} className="spin"/>{c.loading}</p>}
        {view?.configured !== false && r.failure !== 'session' && <form className="journal-capture" onSubmit={event => { event.preventDefault(); openReview(); }}>
            <fieldset disabled={!view?.configured || r.busy || r.paused}>
                <div className="journal-query-bar">
                    <div className="journal-source-control"><h3><Server size={16} aria-hidden="true"/>{c.source}</h3><div className="journal-source-choice"><button ref={pickerButton} type="button" className="journal-service-trigger" aria-haspopup="dialog" aria-expanded={pickerOpen} aria-label={c.chooseService} onClick={() => setPickerOpen(true)}><span><strong>{unit || c.choose}</strong>{serviceLabel && <span className="journal-service-label">{serviceLabel}</span>}</span><ChevronDown size={17} aria-hidden="true"/></button></div><JournalPermissionSummary unit={unit} view={view}/></div>
                    <div className="journal-period-control" role="group" aria-label={c.presets}><h3><Clock3 size={16} aria-hidden="true"/>{c.period}{view && selectedPreset === null && <span className="journal-custom-window">{c.custom}</span>}</h3><div className="journal-time-presets">{([[5, c.recent5], [15, c.recent], [30, c.recent30], [60, c.recent60]] as const).map(([minutes, label]) => <button key={minutes} type="button" className="button small" aria-label={label} aria-describedby={view ? `${id}-preset-reference` : undefined} aria-pressed={selectedPreset === minutes} onClick={() => chooseWindow(minutes)}>{minutes === 60 ? locale === 'de' ? '1 Stunde' : '1 hour' : `${minutes} min`}</button>)}</div><div className="journal-preset-hint">{view && <><span>{c.ends} {query.end && <time dateTime={query.end}>{displayTime(query.end, locale, true)}</time>}</span><span className="sr-only" id={`${id}-preset-reference`}>{c.managerTime}: {view.serverNow}</span></>}<button type="button" className="button small" disabled={preparingWindow || r.uncertain || active} onClick={() => void prepareRecentWindow()} title={c.newCaptureHint}>{preparingWindow ? <LoaderCircle size={14} className="spin"/> : <RefreshCw size={14}/>} {c.newCapture}</button></div></div>
                    <div className="journal-fetch-control"><button ref={fetchButton} type="submit" className="button primary" disabled={!canReview} aria-haspopup="dialog">{c.fetch}<ArrowRight size={16}/></button></div>
                </div>
                <details className="journal-advanced" ref={advanced}><summary><SlidersHorizontal size={15} aria-hidden="true"/>{c.advanced}</summary><div className="journal-filters"><label>{c.service}<input ref={unitInput} value={unit} onChange={event => setUnit(event.target.value)} placeholder="example.service" maxLength={255} autoComplete="off" spellCheck={false} aria-describedby={`${id}-unit`}/></label><label>{c.start}<input type="datetime-local" step="1" value={start} onChange={event => { setStart(event.target.value); setPreset(null); }}/></label><label>{c.end}<input type="datetime-local" step="1" value={end} onChange={event => { setEnd(event.target.value); setPreset(null); }}/></label><label>{c.severity}<span className="journal-select"><select value={priority} onChange={event => setPriority(Number(event.target.value))}>{priorityNames.map((name, n) => <option value={n} key={n}>{name}</option>)}</select><ChevronDown size={15} aria-hidden="true"/></span></label></div><p id={`${id}-unit`} className="journal-muted">{c.unitHint} {c.manualService}</p><p className="journal-muted">{c.presetHint}</p>{view && <p className="journal-muted">{c.managerTime}: <time dateTime={view.serverNow}>{view.serverNow}</time> <button type="button" className="button small" onClick={r.refresh} aria-label={c.refreshReference}>{c.refresh}</button></p>}</details>
                {view && unit && !valid && <p className="journal-warning">{c.invalidForm}</p>}
            </fieldset>
            {!generationReady && <p role="status" className="journal-warning">{c.generationStale}</p>}
        </form>}
        {state && <div ref={statusRef} tabIndex={-1} className={`journal-state journal-state-${state}`} role={!r.busy && !r.paused && generationReady ? 'status' : undefined}><div><strong>{c[state]}</strong>{hint && <p>{hint}</p>}{request && state !== 'available' && <p className="journal-request-summary"><code>{request.description.query.unit}</code><span> · </span><time dateTime={request.description.query.start}>{displayTime(request.description.query.start, locale, true)}</time><span> → </span><time dateTime={request.description.query.end}>{displayTime(request.description.query.end, locale, true)}</time></p>}</div>{request && ['pending', 'claimed', 'accepted'].includes(request.state) && <button type="button" className="button small" disabled={r.busy || r.uncertain || r.paused || r.failure === 'session'} onClick={r.cancelRequest}>{c.cancel}</button>}</div>}
        {view?.contentStatus === 'available' && <form className="journal-search" onSubmit={event => { event.preventDefault(); if (journalBytes(search) <= JOURNAL_SEARCH_BYTES) r.search(search); }}><div className="journal-results-heading"><h3>{c.results}</h3><span className="journal-capture-summary">{request?.description.query.unit}</span></div>{request && <p className="journal-captured-window"><Clock3 size={13} aria-hidden="true"/><time dateTime={request.description.query.start}>{displayTime(request.description.query.start, locale, true)}</time><span>→</span><time dateTime={request.description.query.end}>{displayTime(request.description.query.end, locale, true)}</time><span>· {priorityNames[request.description.query.maxPriority]}</span></p>}<label htmlFor={`${id}-search`}>{c.search}</label><div><input id={`${id}-search`} value={search} onChange={event => setSearch(event.target.value)} maxLength={128} autoComplete="off" spellCheck={false} aria-describedby={`${id}-search-hint`}/><button className="button" disabled={r.busy || journalBytes(search) > JOURNAL_SEARCH_BYTES}><Search size={14}/>{c.searchButton}</button></div><p id={`${id}-search-hint`} className="journal-muted">{c.searchHint}</p>{journalBytes(search) > JOURNAL_SEARCH_BYTES && <p role="alert">{c.searchLimit}</p>}</form>}
        {page && <div className="journal-results"><p className="journal-snapshot-age">{c.snapshotAt}: <time dateTime={page.observedAt}>{displayTime(page.observedAt, locale)}</time> · {c.snapshotAge}: {Math.max(0, Math.floor((Date.parse(view?.serverNow ?? page.serverNow) - Date.parse(page.observedAt)) / 60000))} min</p><div className="journal-count"><strong>{page.matchedRows} {c.matches} · {page.totalCapturedRows} {c.captured}</strong>{page.search && <span>{c.applied}: “{page.search}”</span>}<span className={page.coverage === 'complete' ? 'journal-muted' : 'journal-warning'}>{page.coverage === 'complete' ? c.complete : page.coverage === 'partial' ? c.partial : c.failed}{page.reason !== 'none' && ` · ${reason}`}</span></div>
            {!page.rows.length && page.coverage !== 'failed' && <><p>{page.totalCapturedRows === 0 ? page.coverage === 'partial' ? c.partialEmpty : c.empty : c.noMatches}</p>{page.totalCapturedRows === 0 && page.coverage === 'complete' && <details className="journal-empty-hint"><summary>{c.emptyHelp}</summary><p>{c.emptyHint}</p></details>}</>}
            {page.rows.length > 0 && <div className="journal-table-wrap"><table className="journal-table" role="table"><thead role="rowgroup"><tr role="row"><th role="columnheader" scope="col">{c.timestamp}</th><th role="columnheader" scope="col">{c.priority}</th><th role="columnheader" scope="col">{c.message}</th></tr></thead><tbody role="rowgroup">{page.rows.map((row, n) => <tr role="row" key={`${page.offset}:${n}`}><td role="cell"><time dateTime={row.timestamp}>{row.timestamp.replace('T', ' ').replace(/Z$/, '')}</time></td><td role="cell"><span className={`journal-priority journal-priority-${row.priority}`}>{priorityNames[row.priority]}</span></td><td role="cell" className="journal-message"><JournalHighlight text={row.message} search={page.search}/></td></tr>)}</tbody></table></div>}
            <nav className="journal-pagination" aria-label={locale === 'de' ? 'Log-Seiten' : 'Log pages'}><button className="button small" disabled={!r.canPrevious || r.busy} onClick={r.previous}><ChevronLeft size={14}/>{c.previous}</button><span>{c.showing} {page.rows.length ? page.offset + 1 : 0}–{page.offset + page.rows.length} / {page.matchedRows}</span><button className="button small" disabled={page.nextOffset === null || r.busy} onClick={r.next}>{c.next}<ChevronRight size={14}/></button></nav>
        </div>}
        <div className="journal-supporting-details"><details className="journal-context-details"><summary>{c.sourceDetails}</summary><JournalSourceOptions view={view}/><JournalSelectedSource unit={unit} view={view}/></details>
        <details className="journal-details"><summary>{c.details}</summary><p>{c.limits}</p><p>{c.allowlist}</p><p>{c.ack} {c.privacy}</p>{request && <dl><div><dt>{c.service}</dt><dd>{request.description.query.unit}</dd></div><div><dt>UTC</dt><dd>{request.description.query.start} → {request.description.query.end}</dd></div><div><dt>{c.expires}</dt><dd>{request.description.expiresAt}</dd></div>{page && <div><dt>{c.observed}</dt><dd>{page.observedCount}{!page.countExact && '+'}</dd></div>}</dl>}</details></div>
        {pickerOpen && view?.configured && <Dialog title={c.chooseService} onClose={closePicker} className="journal-picker-modal"><JournalServicePicker deviceId={view.deviceId} sessionKey={sessionKey} journalView={view} selectedUnit={unit} onSelect={chooseService} onClose={closePicker}/></Dialog>}
        {review && <Dialog title={c.reviewTitle} onClose={closeReview} className="journal-review-modal"><h2>{c.reviewTitle}</h2><dl className="journal-review-summary"><div><dt>{c.source}</dt><dd>{review.unit}</dd></div><div><dt>{c.reviewWindow}</dt><dd><time dateTime={review.start}>{displayTime(review.start, locale, true)}</time><span> → </span><time dateTime={review.end}>{displayTime(review.end, locale, true)}</time></dd></div><div><dt>{c.severity}</dt><dd>{priorityNames[review.maxPriority]}</dd></div></dl><JournalPermissionSummary unit={review.unit} view={view}/>{page && <p className="journal-warning">{c.replace}</p>}<details className="journal-review-details"><summary>{c.reviewDetails}</summary><p>{c.limits}</p><p>{c.privacy}</p></details><form onSubmit={event => { event.preventDefault(); confirmCapture(); }}><label className="journal-ack"><input type="checkbox" checked={ack} onChange={event => setAck(event.target.checked)}/><span>{c.ack}</span></label>{insecureTestMode && <label className="journal-ack journal-warning"><input type="checkbox" checked={plainAck} onChange={event => setPlainAck(event.target.checked)}/><span>{c.plaintext}</span></label>}<div className="journal-actions"><button type="button" className="button" onClick={closeReview}>{c.dismiss}</button><button type="submit" className="button primary" disabled={!reviewed || !canReview || !ack || insecureTestMode && !plainAck}><Check size={15}/>{c.capture}</button></div></form></Dialog>}
    </section>;
}
