import { useEffect, useId, useState } from 'react';
import { ChevronLeft, ChevronRight, LoaderCircle, RefreshCw, Search, TriangleAlert } from 'lucide-react';
import { useLocale } from './i18n';
import { useJournal } from './journal-resource';
import type { JournalResource } from './journal-resource';
import { journalBytes, journalFold, JOURNAL_SEARCH_BYTES, validJournalQuery } from './journal-types';
import type { JournalQuery } from './journal-types';
import './journal.css';
const copy = {
    en: {
        title: 'Service logs', newCapture: 'New capture', applied: 'Applied search', refresh: 'Refresh status', intro: 'Capture a short journal window from one explicitly allowlisted service.', service: 'Exact service unit', start: 'From (UTC)', end: 'To (UTC)', severity: 'Include severity through', recent: 'Last 15 minutes', capture: 'Capture logs', cancel: 'Cancel request / discard content',
        limits: 'Up to 1 hour within the last 24 hours. At most 500 captured rows / 512 KiB. Content expires 15 minutes after the request was created.',
        allowlist: 'The unit must match the endpoint’s local allowlist exactly. This page cannot enable local access or verify the allowlist.',
        ack: 'I understand that log messages may contain credentials, personal data or other secrets. Masking is best effort and does not make them safe or anonymous.',
        plaintext: 'I also accept that this HTTP test sends log content over an unencrypted connection.',
        loading: 'Reading journal status or captured content…', paused: 'Log content is paused while this page is inactive. Return to this page or refresh status to recheck access. No new capture is started.', waiting: 'Journal status is not loaded. Refresh status to continue.', configured: 'Not configured', configuredHint: 'This device is not eligible for the separate journal extension. No log content is available here.', awaiting: 'Awaiting a request', awaitingHint: 'No journal request or captured content is available.',
        pending: 'Pending', pendingHint: 'Waiting for the agent to check its local permission. No content is available yet.', claimed: 'Claimed', claimedHint: 'The agent claimed this one-shot request. Collection is not yet confirmed.', available: 'Captured snapshot available', failed: 'Collection failed', denied: 'Local access denied', disabled: 'Local journal access disabled', helper_unavailable: 'Local journal helper unavailable', result_lost: 'Content lost / unavailable', lostHint: 'The manager reports that retained content is unavailable for this request. Refresh status to check again. No new capture is started automatically.', expired: 'Expired', expiredHint: 'The original retention window ended. Log rows have been cleared.', canceled: 'Canceled', canceledHint: 'This request no longer grants collection or content access.', unavailable: 'Captured content unavailable',
        search: 'Literal text in captured messages', searchButton: 'Search capture', searchHint: 'Case-insensitive literal search across this captured snapshot only. It does not search the live or entire journal.', searchLimit: 'Use at most 128 UTF-8 bytes.', previous: 'Previous page', next: 'Next page', empty: 'The complete capture contains no matching journal entries.', noMatches: 'No literal matches in this captured snapshot.', partialEmpty: 'No rows were retained; coverage is partial, so this is not evidence of an empty journal.', captured: 'captured', matches: 'matches', showing: 'Showing', partial: 'Partial coverage', complete: 'Complete coverage for the requested window visible to the agent', observed: 'Observed before capture limits', expires: 'Content expires', timestamp: 'Time (UTC)', priority: 'Severity', message: 'Message', details: 'Capture details & limits', unitHint: 'Example: example.service. No wildcards or shell expressions.', invalidForm: 'Choose one exact service, a UTC window of at most 1 hour within the last 24 hours, and severity 0–7.',
        load: 'The journal status or content could not be read. Refresh status before continuing.', invalid: 'The manager returned inconsistent or unsupported journal data. Rows were cleared.', timeout: 'The read timed out. Refresh status to try again.', session: 'Your session has ended. Sign in again.', clock: 'The time or request sequence is no longer reliable. Rows were cleared; refresh status.', conflict: 'The request or snapshot changed, expired or became unavailable. Refresh status.', uncertain: 'The action’s outcome is uncertain. Status is being checked; the action will not be repeated automatically.', uncertainHeld: 'The last action could not be confirmed. Refresh status before issuing another action.',
        none: 'No failure reported', permission_denied: 'Permission denied', source_missing: 'Journal source missing', invalid_source: 'Invalid journal source', read_failed: 'Journal read failed', sourceTimeout: 'Collection timed out', item_limit: 'Row limit reached', byte_limit: 'Byte limit reached', visibility_restricted: 'Source visibility restricted', not_supported: 'Source not supported', collector_busy: 'Collector busy',
    },
    de: {
        title: 'Service-Logs', newCapture: 'Neue Erfassung', applied: 'Angewendete Suche', refresh: 'Status aktualisieren', intro: 'Ein kurzes Journal-Zeitfenster für genau einen lokal freigegebenen Dienst erfassen.', service: 'Exakte Service-Unit', start: 'Von (UTC)', end: 'Bis (UTC)', severity: 'Schweregrade bis einschließlich', recent: 'Letzte 15 Minuten', capture: 'Logs erfassen', cancel: 'Anfrage abbrechen / Inhalt verwerfen',
        limits: 'Höchstens 1 Stunde innerhalb der letzten 24 Stunden. Maximal 500 erfasste Zeilen / 512 KiB. Inhalte laufen 15 Minuten nach Erstellung der Anfrage ab.',
        allowlist: 'Die Unit muss exakt in der lokalen Freigabeliste des Endpunkts stehen. Diese Seite kann lokalen Zugriff weder aktivieren noch die Liste prüfen.',
        ack: 'Ich verstehe, dass Log-Nachrichten Zugangsdaten, personenbezogene Daten oder andere Geheimnisse enthalten können. Maskierung ist nur bestmöglich und macht sie nicht sicher oder anonym.',
        plaintext: 'Ich akzeptiere zusätzlich, dass dieser HTTP-Test Log-Inhalte unverschlüsselt überträgt.',
        loading: 'Journal-Status oder erfasster Inhalt wird gelesen…', paused: 'Log-Inhalte sind pausiert, solange diese Seite inaktiv ist. Zur Seite zurückkehren oder den Status aktualisieren, um den Zugriff erneut zu prüfen. Es wird keine neue Erfassung gestartet.', waiting: 'Der Journalstatus ist nicht geladen. Zum Fortfahren den Status aktualisieren.', configured: 'Nicht konfiguriert', configuredHint: 'Dieses Gerät ist für die separate Journal-Erweiterung nicht berechtigt. Hier sind keine Log-Inhalte verfügbar.', awaiting: 'Wartet auf eine Anfrage', awaitingHint: 'Keine Journal-Anfrage und kein erfasster Inhalt verfügbar.',
        pending: 'Ausstehend', pendingHint: 'Der Agent muss die lokale Freigabe noch prüfen. Noch kein Inhalt verfügbar.', claimed: 'Übernommen', claimedHint: 'Der Agent hat diese einmalige Anfrage übernommen. Die Erfassung ist noch nicht bestätigt.', available: 'Erfasster Snapshot verfügbar', failed: 'Erfassung fehlgeschlagen', denied: 'Lokaler Zugriff verweigert', disabled: 'Lokaler Journal-Zugriff deaktiviert', helper_unavailable: 'Lokaler Journal-Helper nicht verfügbar', result_lost: 'Inhalt verloren / nicht verfügbar', lostHint: 'Der Manager meldet, dass gespeicherter Inhalt für diese Anfrage nicht verfügbar ist. Zur erneuten Prüfung den Status aktualisieren. Es wird keine neue Erfassung automatisch gestartet.', expired: 'Abgelaufen', expiredHint: 'Die ursprüngliche Aufbewahrungsfrist ist beendet. Log-Zeilen wurden entfernt.', canceled: 'Abgebrochen', canceledHint: 'Diese Anfrage erlaubt weder weitere Erfassung noch Inhaltszugriff.', unavailable: 'Erfasster Inhalt nicht verfügbar',
        search: 'Wörtlicher Text in erfassten Nachrichten', searchButton: 'Snapshot durchsuchen', searchHint: 'Wörtliche Suche ohne Beachtung von Groß-/Kleinschreibung ausschließlich im erfassten Snapshot. Keine Suche im Live- oder gesamten Journal.', searchLimit: 'Höchstens 128 UTF-8-Bytes verwenden.', previous: 'Vorherige Seite', next: 'Nächste Seite', empty: 'Die vollständige Erfassung enthält keine passenden Journal-Einträge.', noMatches: 'Keine wörtlichen Treffer in diesem erfassten Snapshot.', partialEmpty: 'Keine Zeilen behalten; die Erfassung ist teilweise und belegt kein leeres Journal.', captured: 'erfasst', matches: 'Treffer', showing: 'Anzeige', partial: 'Teilweise Abdeckung', complete: 'Vollständige Abdeckung des angefragten, für den Agent sichtbaren Zeitfensters', observed: 'Vor Erfassungsgrenzen beobachtet', expires: 'Inhalt läuft ab', timestamp: 'Zeit (UTC)', priority: 'Schweregrad', message: 'Nachricht', details: 'Erfassungsdetails & Grenzen', unitHint: 'Beispiel: example.service. Keine Platzhalter oder Shell-Ausdrücke.', invalidForm: 'Einen exakten Dienst, ein UTC-Zeitfenster von höchstens 1 Stunde innerhalb der letzten 24 Stunden und Schweregrad 0–7 wählen.',
        load: 'Journal-Status oder Inhalt konnte nicht gelesen werden. Vor dem Fortsetzen Status aktualisieren.', invalid: 'Der Manager hat widersprüchliche oder nicht unterstützte Journal-Daten geliefert. Zeilen wurden entfernt.', timeout: 'Das Lesen hat zu lange gedauert. Status zum Wiederholen aktualisieren.', session: 'Die Sitzung ist beendet. Bitte erneut anmelden.', clock: 'Zeit oder Anfragesequenz sind nicht mehr verlässlich. Zeilen wurden entfernt; Status aktualisieren.', conflict: 'Anfrage oder Snapshot wurde geändert, ist abgelaufen oder nicht mehr verfügbar. Status aktualisieren.', uncertain: 'Das Ergebnis ist unklar. Der Status wird geprüft; die Aktion wird nicht automatisch wiederholt.', uncertainHeld: 'Die letzte Aktion konnte nicht bestätigt werden. Vor einer weiteren Aktion den Status aktualisieren.',
        none: 'Kein Fehler gemeldet', permission_denied: 'Berechtigung verweigert', source_missing: 'Journal-Quelle fehlt', invalid_source: 'Ungültige Journal-Quelle', read_failed: 'Journal-Lesen fehlgeschlagen', sourceTimeout: 'Erfassungszeitlimit erreicht', item_limit: 'Zeilengrenze erreicht', byte_limit: 'Byte-Grenze erreicht', visibility_restricted: 'Quellensichtbarkeit eingeschränkt', not_supported: 'Quelle nicht unterstützt', collector_busy: 'Collector ausgelastet',
    },
};
const priorityNames = ['0 · Emergency', '1 · Alert', '2 · Critical', '3 · Error', '4 · Warning', '5 · Notice', '6 · Info', '7 · Debug'];
const inputTime = (s: string) => new Date(s).toISOString().slice(0, 19);
const utcInput = (s: string) => /^\d{4}-\d\d-\d\dT\d\d:\d\d(?::\d\d)?$/.test(s) ? `${s.length === 16 ? `${s}:00` : s}Z` : '';
export function JournalHighlight({ text, search }: { text: string; search: string }) {
    if (!search) return <>{text}</>;
    const folded = journalFold(text), needle = journalFold(search), nodes = []; let at = 0, found = folded.indexOf(needle);
    while (found >= 0) { nodes.push(text.slice(at, found), <mark key={found}>{text.slice(found, found + needle.length)}</mark>); at = found + needle.length; found = folded.indexOf(needle, at); }
    nodes.push(text.slice(at)); return <>{nodes}</>;
}
type JournalPanelProps = { deviceId: string; insecureTestMode: boolean; sessionKey: string | null };
export function JournalPanel(props: JournalPanelProps) {
    return <JournalSession key={`${props.deviceId}:${props.sessionKey ?? ''}:${props.insecureTestMode}`} {...props}/>;
}
function JournalSession({ deviceId, insecureTestMode, sessionKey }: JournalPanelProps) {
    return <JournalContent resource={useJournal(deviceId, insecureTestMode, sessionKey)} insecureTestMode={insecureTestMode}/>;
}
export function JournalContent({ resource: r, insecureTestMode }: { resource: JournalResource; insecureTestMode: boolean }) {
    const [locale] = useLocale(), c = copy[locale], id = useId(), [unit, setUnit] = useState(''), [start, setStart] = useState(''), [end, setEnd] = useState(''), [priority, setPriority] = useState(6), [ack, setAck] = useState(false), [plainAck, setPlainAck] = useState(false), [search, setSearch] = useState('');
    const view = r.view, request = view?.request, page = r.page;
    useEffect(() => { setAck(false); setPlainAck(false); setSearch(''); }, [r.reset]);
    useEffect(() => { if (view && !start && !end) { setEnd(inputTime(view.serverNow)); setStart(inputTime(new Date(Date.parse(view.serverNow) - 900000).toISOString())); } }, [end, start, view]);
    const query: JournalQuery = { unit, start: utcInput(start), end: utcInput(end), maxPriority: priority };
    const valid = !!view && validJournalQuery(query, view.serverNow), active = !!request && ['pending', 'claimed'].includes(request.state);
    const state = !view ? null : !view.configured ? 'configured' : !request ? 'awaiting' : request.state === 'expired' || request.state === 'canceled' ? request.state : ['disabled', 'denied', 'helper_unavailable', 'result_lost'].includes(view.localStatus) ? view.localStatus as 'disabled' | 'denied' | 'helper_unavailable' | 'result_lost' : page?.coverage === 'failed' ? 'failed' : view.contentStatus === 'available' ? 'available' : request.state === 'accepted' ? 'unavailable' : request.state;
    const hint = state === 'configured' ? c.configuredHint : state === 'awaiting' ? c.awaitingHint : state === 'pending' ? c.pendingHint : state === 'claimed' ? c.claimedHint : state === 'expired' ? c.expiredHint : state === 'canceled' ? c.canceledHint : state === 'result_lost' || state === 'unavailable' ? c.lostHint : null;
    const reason = page ? c[page.reason === 'timeout' ? 'sourceTimeout' : page.reason] : null;
    return <section className="journal-panel detail-section" aria-labelledby={id} aria-busy={r.busy}>
        <header className="journal-heading"><div><h2 id={id}>{c.title}</h2><p className="journal-muted">{c.intro}</p></div><button className="button small" disabled={r.busy || r.failure === 'session'} onClick={r.refresh}><RefreshCw size={14}/>{c.refresh}</button></header>
        {r.failure && <p role="alert" className="journal-warning"><TriangleAlert size={16}/>{c[r.failure]}</p>}
        {r.uncertain && r.failure !== 'uncertain' && <p className="journal-warning">{c.uncertainHeld}</p>}
        {r.paused && !r.busy && !r.failure && <p role="status" className="journal-muted">{c.paused}</p>}
        {!view && !r.paused && !r.busy && !r.failure && <p role="status" className="journal-muted">{c.waiting}</p>}
        {r.busy && <p role="status" className="journal-muted"><LoaderCircle size={14} className="spin"/>{c.loading}</p>}
        {state && <div className={`journal-state journal-state-${state}`}><strong>{c[state]}</strong>{hint && <p>{hint}</p>}</div>}
        {view?.configured !== false && r.failure !== 'session' && <form className="journal-capture" onSubmit={event => { event.preventDefault(); if (valid && ack && (!insecureTestMode || plainAck)) { void r.create(query, ack, plainAck); setAck(false); setPlainAck(false); } }}>
            <h3 className="journal-form-title">{c.newCapture}</h3><fieldset disabled={!view?.configured || r.busy || r.paused}><div className="journal-filters"><label>{c.service}<input value={unit} onChange={event => setUnit(event.target.value)} placeholder="example.service" maxLength={255} autoComplete="off" spellCheck={false} aria-describedby={`${id}-unit`}/></label><label>{c.start}<input type="datetime-local" step="1" value={start} onChange={event => setStart(event.target.value)}/></label><label>{c.end}<input type="datetime-local" step="1" value={end} onChange={event => setEnd(event.target.value)}/></label><label>{c.severity}<select value={priority} onChange={event => setPriority(Number(event.target.value))}>{priorityNames.map((name, n) => <option value={n} key={n}>{name}</option>)}</select></label></div>
            <div className="journal-filter-help"><span id={`${id}-unit`}>{c.unitHint}</span><button type="button" className="text-button" onClick={() => { if (!view) return; setEnd(inputTime(view.serverNow)); setStart(inputTime(new Date(Date.parse(view.serverNow) - 900000).toISOString())); }}>{c.recent}</button></div>
            <label className="journal-ack"><input type="checkbox" checked={ack} onChange={event => setAck(event.target.checked)}/><span>{c.ack}</span></label>
            {insecureTestMode && <label className="journal-ack journal-warning"><input type="checkbox" checked={plainAck} onChange={event => setPlainAck(event.target.checked)}/><span>{c.plaintext}</span></label>}
            <div className="journal-actions"><button className="button primary" disabled={!valid || !ack || insecureTestMode && !plainAck || r.busy || r.uncertain || active}>{c.capture}</button>{request && ['pending', 'claimed', 'accepted'].includes(request.state) && <button type="button" className="button" disabled={r.busy || r.uncertain} onClick={r.cancelRequest}>{c.cancel}</button>}</div>
            {view && unit && !valid && <p className="journal-muted">{c.invalidForm}</p>}</fieldset>
        </form>}
        {view?.contentStatus === 'available' && <form className="journal-search" onSubmit={event => { event.preventDefault(); if (journalBytes(search) <= JOURNAL_SEARCH_BYTES) r.search(search); }}><p className="journal-capture-summary">{request?.description.query.unit} · {request?.description.query.start} → {request?.description.query.end} · {priorityNames[request?.description.query.maxPriority ?? 0]}</p><label htmlFor={`${id}-search`}>{c.search}</label><div><input id={`${id}-search`} value={search} onChange={event => setSearch(event.target.value)} maxLength={128} autoComplete="off" spellCheck={false} aria-describedby={`${id}-search-hint`}/><button className="button" disabled={r.busy || journalBytes(search) > JOURNAL_SEARCH_BYTES}><Search size={14}/>{c.searchButton}</button></div><p id={`${id}-search-hint`} className="journal-muted">{c.searchHint}</p>{journalBytes(search) > JOURNAL_SEARCH_BYTES && <p role="alert">{c.searchLimit}</p>}</form>}
        {page && <div className="journal-results"><div className="journal-count"><strong>{page.matchedRows} {c.matches} · {page.totalCapturedRows} {c.captured}</strong>{page.search && <span>{c.applied}: “{page.search}”</span>}<span className={page.coverage === 'complete' ? 'journal-muted' : 'journal-warning'}>{page.coverage === 'complete' ? c.complete : page.coverage === 'partial' ? c.partial : c.failed}{page.reason !== 'none' && ` · ${reason}`}</span></div>
            {!page.rows.length && page.coverage !== 'failed' && <p>{page.totalCapturedRows === 0 ? page.coverage === 'partial' ? c.partialEmpty : c.empty : c.noMatches}</p>}
            {page.rows.length > 0 && <div className="journal-table-wrap"><table className="journal-table"><thead><tr><th>{c.timestamp}</th><th>{c.priority}</th><th>{c.message}</th></tr></thead><tbody>{page.rows.map((row, n) => <tr key={`${page.offset}:${n}`}><td><time dateTime={row.timestamp}>{row.timestamp.replace('T', ' ').replace(/Z$/, '')}</time></td><td><span className={`journal-priority journal-priority-${row.priority}`}>{priorityNames[row.priority]}</span></td><td className="journal-message"><JournalHighlight text={row.message} search={page.search}/></td></tr>)}</tbody></table></div>}
            <nav className="journal-pagination" aria-label={locale === 'de' ? 'Log-Seiten' : 'Log pages'}><button className="button small" disabled={!r.canPrevious || r.busy} onClick={r.previous}><ChevronLeft size={14}/>{c.previous}</button><span>{c.showing} {page.rows.length ? page.offset + 1 : 0}–{page.offset + page.rows.length} / {page.matchedRows}</span><button className="button small" disabled={page.nextOffset === null || r.busy} onClick={r.next}>{c.next}<ChevronRight size={14}/></button></nav>
        </div>}
        <details className="journal-details"><summary>{c.details}</summary><p>{c.limits}</p><p>{c.allowlist}</p><p>{c.ack}</p>{request && <dl><div><dt>{c.service}</dt><dd>{request.description.query.unit}</dd></div><div><dt>UTC</dt><dd>{request.description.query.start} → {request.description.query.end}</dd></div><div><dt>{c.expires}</dt><dd>{request.description.expiresAt}</dd></div>{page && <div><dt>{c.observed}</dt><dd>{page.observedCount}{!page.countExact && '+'}</dd></div>}</dl>}</details>
    </section>;
}
