import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { abortProtectedRequests, APIError, AUTH_REQUIRED_EVENT, mutateRaw, request } from './api';
import { LOGOUT_INTENT_KEY, useOperator } from './auth';
import { setLocale } from './i18n';
import { ProactiveAISettingsPanel } from './proactive-ai';
import { PROACTIVE_SETTINGS_BYTES, validProactiveAISettings } from './proactive-ai-types';
import type { ProactiveAISettings } from './proactive-ai-types';

vi.mock('./api', async original => ({ ...await original<typeof import('./api')>(), request: vi.fn(), mutateRaw: vi.fn() }));
vi.mock('./auth', async original => ({ ...await original<typeof import('./auth')>(), useOperator: vi.fn() }));
const id = 'agent_00000000000000000000000000000001', second = 'agent_00000000000000000000000000000002';
const operator = { mode: 'lan' as const, authenticated: true, loginMode: 'shared' as const, expiresAt: '2026-10-06T14:00:00Z', insecureTestMode: false, logout: vi.fn(), theme: 'light' as const, setTheme: vi.fn() };
const fixture = (): ProactiveAISettings => ({ schemaVersion: 'tracebolt.proactive-ai-settings.v1', revision: 'revision-a', enabled: false, configRevision: 'config-a', providerConfigured: true, baseURL: 'http://127.0.0.1:11434/v1', model: 'fixture-model', deviceIds: [], availableDevices: [{ id }, { id: second }], dataScope: 'health-summary-v1', logsAllowed: false, resetsOnRestart: true, maxAnalysesPerHour: 6, cooldownMinutes: 30, minIntervalSeconds: 60, reason: '' });
const flush = () => act(async () => {}), advance = (ms: number) => act(async () => { await vi.advanceTimersByTimeAsync(ms); });
const button = (name: string) => screen.getByRole('button', { name });
const open = () => fireEvent.click(button('Proactive AI diagnostics'));
const refresh = () => fireEvent.click(button('Refresh proactive AI settings'));
const consent = () => screen.getByRole('checkbox', { name: /I approve future health-summary/ });
const enable = () => button('Approve and enable');
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>(done => { resolve = done; }); return { resolve, promise }; }
async function start(value: unknown = fixture()) { vi.mocked(request).mockResolvedValue(value); const mounted = render(<ProactiveAISettingsPanel/>); await flush(); return mounted; }
async function prepare() { const mounted = await start(); open(); fireEvent.click(screen.getByRole('checkbox', { name: new RegExp(id) })); fireEvent.click(consent()); return mounted; }
function mutation() { return JSON.parse(vi.mocked(mutateRaw).mock.calls.at(-1)![1]) as Record<string, unknown>; }
beforeEach(() => { vi.useFakeTimers(); vi.setSystemTime('2026-10-06T12:00:00Z'); localStorage.clear(); sessionStorage.clear(); setLocale('en', false); vi.spyOn(document, 'visibilityState', 'get').mockReturnValue('visible'); vi.mocked(useOperator).mockReturnValue(operator); vi.mocked(request).mockReset(); vi.mocked(mutateRaw).mockReset(); });
afterEach(() => { cleanup(); abortProtectedRequests(); vi.useRealTimers(); vi.restoreAllMocks(); });

describe('proactive settings contract', () => {
    it('accepts on, off, and unconfigured settings', () => { expect(validProactiveAISettings(fixture())).toBe(true); expect(validProactiveAISettings({ ...fixture(), enabled: true, deviceIds: [id] })).toBe(true); expect(validProactiveAISettings({ ...fixture(), providerConfigured: false, baseURL: '', model: '' })).toBe(true); });
    it.each([null, {}, { ...fixture(), logsAllowed: true }, { ...fixture(), dataScope: 'raw-logs' }, { ...fixture(), extra: true }, { ...fixture(), enabled: true }, { ...fixture(), enabled: true, deviceIds: [id], providerConfigured: false }, { ...fixture(), baseURL: 'https://user:pass@example.com' }, { ...fixture(), model: 'bad model' }, { ...fixture(), configRevision: '' }, { ...fixture(), deviceIds: [id, id] }, { ...fixture(), deviceIds: ['agent_not_enrolled'] }, { ...fixture(), availableDevices: [{ id, name: 'private' }] }, { ...fixture(), availableDevices: [{ id }, { id }] }, { ...fixture(), maxAnalysesPerHour: 7 }, { ...fixture(), resetsOnRestart: undefined }, { ...fixture(), resetsOnRestart: 'false' }])('rejects unsupported or expanded responses %j', value => expect(validProactiveAISettings(value)).toBe(false));
});
describe('persistent scope disclosure', () => {
    it.each([false, true])('accepts boolean restart behavior %s without expanding the response shape', resetsOnRestart => { expect(validProactiveAISettings({ ...fixture(), resetsOnRestart })).toBe(true); expect(validProactiveAISettings({ ...fixture(), resetsOnRestart, enabled: true, deviceIds: [id] })).toBe(true); });
    it('requires explicit after-restart approval with the original grant boundary and time', async () => {
        await start({ ...fixture(), resetsOnRestart: false }); open();
        expect(consent()).toHaveAccessibleName(/including after manager restart/); expect(consent()).not.toBeChecked();
        expect(screen.queryByText(/Approval resets to off/)).not.toBeInTheDocument(); expect(screen.getByText(/original approval time/)).toHaveTextContent('exact provider, device and data scope');
        fireEvent.click(screen.getByRole('checkbox', { name: new RegExp(id) })); expect(enable()).toBeDisabled(); fireEvent.click(consent());
        vi.mocked(mutateRaw).mockResolvedValue({ ...fixture(), resetsOnRestart: false, revision: 'revision-b', enabled: true, deviceIds: [id] }); fireEvent.click(enable()); await flush();
        expect(mutation()).toEqual({ expectedRevision: 'revision-a', configRevision: 'config-a', enabled: true, deviceIds: [id], approvedBaseURL: fixture().baseURL, approvedModel: fixture().model, dataScope: 'health-summary-v1', acknowledgeData: true });
        expect(consent()).not.toBeChecked(); expect(screen.getByText('Settings saved. No connectivity test was sent.')).toBeVisible();
    });
    it('localizes persisted approval without showing reset-off language', async () => {
        setLocale('de', false); await start({ ...fixture(), resetsOnRestart: false }); fireEvent.click(button('Proaktive KI-Diagnostik'));
        expect(screen.getByRole('checkbox', { name: /Ich erlaube künftige/ })).toHaveAccessibleName(/auch nach einem Manager-Neustart/);
        expect(screen.queryByText(/Nach Manager-Neustart oder Anbieteränderung wird/)).not.toBeInTheDocument(); expect(screen.getByText(/Die Freigabe gilt nach einem Manager-Neustart/)).toBeVisible(); expect(screen.getByText(/ursprünglichen Zeitpunkt/)).not.toBeVisible(); fireEvent.click(screen.getByText('Grenzen & Datenschutzdetails')); expect(screen.getByText(/ursprünglichen Zeitpunkt/)).toBeVisible();
    });
    it('clears previously reviewed scope when provider persistence mode changes', async () => {
        await prepare(); vi.mocked(request).mockResolvedValue({ ...fixture(), revision: 'revision-b', configRevision: 'config-persistent', resetsOnRestart: false });
        act(() => window.dispatchEvent(new Event('tracebolt-ai-config-changed'))); await flush(); expect(consent()).not.toBeChecked(); expect(consent()).toHaveAccessibleName(/including after manager restart/); expect(enable()).toBeDisabled(); expect(mutateRaw).not.toHaveBeenCalled();
    });
});
describe('explicit provider and data approval', () => {
    it('loads collapsed with only a bounded settings GET and no provider call', async () => { await start(); expect(button('Proactive AI diagnostics')).toHaveAttribute('aria-expanded', 'false'); expect(screen.queryByRole('checkbox')).not.toBeInTheDocument(); expect(request).toHaveBeenCalledExactlyOnceWith('/ai/proactive', { signal: expect.any(AbortSignal), cache: 'no-store' }, PROACTIVE_SETTINGS_BYTES); expect(mutateRaw).not.toHaveBeenCalled(); });
    it('requires an exact provider, selected devices and fresh scope consent; submits once', async () => {
        await start(); open(); expect(enable()).toBeDisabled(); expect(consent()).toBeDisabled(); fireEvent.click(screen.getByRole('checkbox', { name: new RegExp(id) })); expect(enable()).toBeDisabled(); fireEvent.click(consent()); expect(enable()).toBeEnabled();
        const pending = deferred<unknown>(); vi.mocked(mutateRaw).mockReturnValue(pending.promise); fireEvent.click(enable()); fireEvent.click(button('Proactive AI diagnostics')); fireEvent.click(button('Proactive AI diagnostics'));
        expect(mutateRaw).toHaveBeenCalledTimes(1); expect(mutation()).toEqual({ expectedRevision: 'revision-a', configRevision: 'config-a', enabled: true, deviceIds: [id], approvedBaseURL: fixture().baseURL, approvedModel: fixture().model, dataScope: 'health-summary-v1', acknowledgeData: true });
        await act(async () => pending.resolve({ ...fixture(), revision: 'revision-b', enabled: true, deviceIds: [id] })); expect(screen.queryByText('Settings saved. No connectivity test was sent.')).not.toBeInTheDocument(); expect(screen.getByRole('alert')).toHaveTextContent('may already have taken effect');
    });
    it('saves verified settings without storage, provider tests, or auto-repeat', async () => { const storage = vi.spyOn(Storage.prototype, 'setItem'); await prepare(); vi.mocked(mutateRaw).mockResolvedValue({ ...fixture(), revision: 'revision-b', enabled: true, deviceIds: [id] }); fireEvent.click(enable()); await flush(); expect(screen.getByText('Settings saved. No connectivity test was sent.')).toBeVisible(); expect(consent()).not.toBeChecked(); expect(button('Approve updated scope')).toBeDisabled(); expect(mutateRaw).toHaveBeenCalledTimes(1); expect(storage).not.toHaveBeenCalled(); });
    it('clears scope approval after changing any selected device', async () => { await prepare(); fireEvent.click(screen.getByRole('checkbox', { name: new RegExp(second) })); expect(consent()).not.toBeChecked(); expect(enable()).toBeDisabled(); });
    it('allows disabling or removing a saved device that is no longer authorized', async () => { await start({ ...fixture(), enabled: true, deviceIds: [id], availableDevices: [{ id: second }] }); open(); expect(screen.getByText(/Unavailable; remove/)).toBeVisible(); expect(button('Approve updated scope')).toBeDisabled(); expect(button('Disable proactive AI')).toBeEnabled(); fireEvent.click(screen.getByRole('checkbox', { name: /agent_00000000000000000000000000000001/ })); fireEvent.click(screen.getByRole('checkbox', { name: new RegExp(second) })); fireEvent.click(consent()); expect(button('Approve updated scope')).toBeEnabled(); });
    it('disables with no data acknowledgment and no new selection', async () => { await start({ ...fixture(), enabled: true, deviceIds: [id] }); open(); vi.mocked(mutateRaw).mockResolvedValue({ ...fixture(), revision: 'revision-b', deviceIds: [id] }); fireEvent.click(button('Disable proactive AI')); await flush(); expect(mutation()).toMatchObject({ enabled: false, acknowledgeData: false, deviceIds: [id] }); });
    it('keeps essential consent facts visible and moves optional detail after consent', async () => {
        await start(); open(); const summary = screen.getByText('Limits & privacy details'), details = summary.closest('details')!;
        expect(details).not.toHaveAttribute('open'); expect(consent()).not.toBeChecked(); expect(consent()).toBeVisible();
        expect(consent().compareDocumentPosition(details) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
        expect(screen.queryByRole('checkbox', { name: /raw logs/ })).not.toBeInTheDocument();
        expect(screen.getByText(/No raw logs, device names/)).toBeVisible(); expect(screen.getByText(/Provider charges may apply/)).toBeVisible(); expect(screen.getByText(/Approval resets to off/)).toBeVisible();
        expect(screen.getByText(/24 KiB/)).not.toBeVisible(); expect(screen.getByText(/Masking is best effort/)).not.toBeVisible();
        fireEvent.click(summary); expect(details).toHaveAttribute('open'); expect(screen.getByText(/separate local collection approval/)).toBeVisible(); expect(screen.getByText(/Masking is best effort/)).toBeVisible(); expect(screen.getByText(/24 KiB/)).toHaveTextContent('1,024 tokens');
        expect(screen.getByText(/Saving does not test provider connectivity/)).toBeVisible();
    });
    it('leaves named accounts read-only, even with unrelated capabilities', async () => { vi.mocked(useOperator).mockReturnValue({ ...operator, loginMode: 'named', actorId: 'operator_00000000000000000000000000000001', capabilities: ['read', 'manage_alarms'] }); await start({ ...fixture(), enabled: true, deviceIds: [id] }); open(); expect(screen.getByText(/Named accounts can read/)).toBeVisible(); expect(screen.queryByRole('button', { name: /Approve|Disable proactive/ })).not.toBeInTheDocument(); expect(screen.getByRole('checkbox', { name: new RegExp(id) })).toBeDisabled(); expect(mutateRaw).not.toHaveBeenCalled(); });
    it.each([{ ...operator, mode: 'development' as const }, { ...operator, authenticated: false }, null])('stays absent outside an authenticated LAN session', async value => { vi.mocked(useOperator).mockReturnValue(value); await start(); expect(request).not.toHaveBeenCalled(); expect(screen.queryByRole('region')).not.toBeInTheDocument(); });
    it('cannot enable without a provider and enrolled device', async () => { await start({ ...fixture(), providerConfigured: false, baseURL: '', model: '', availableDevices: [] }); open(); expect(screen.getByText(/Configure an AI provider above/)).toBeVisible(); expect(enable()).toBeDisabled(); expect(consent()).toBeDisabled(); });
    it('localizes controls and disclosure to German', async () => { setLocale('de', false); await start(); fireEvent.click(button('Proaktive KI-Diagnostik')); expect(button('Freigeben und aktivieren')).toBeDisabled(); expect(screen.getByText(/Keine Rohlogs, Gerätenamen/)).toBeVisible(); expect(screen.getByText(/Anbieterkosten können anfallen/)).toBeVisible(); expect(screen.getByText(/Höchstens 6 Analysen/)).not.toBeVisible(); fireEvent.click(screen.getByText('Grenzen & Datenschutzdetails')); expect(screen.getByText(/Höchstens 6 Analysen/)).toBeVisible(); });
});
describe('stale, interrupted and repeated flows', () => {
    it('invalidates provider approval immediately and reads the new provider after a save event', async () => { await prepare(); vi.mocked(request).mockResolvedValue({ ...fixture(), revision: 'revision-b', configRevision: 'config-b', baseURL: 'https://api.example.com/v1', model: 'next-model' }); act(() => window.dispatchEvent(new Event('tracebolt-ai-config-changed'))); expect(screen.queryByText(fixture().baseURL)).not.toBeInTheDocument(); await flush(); expect(screen.getByText('https://api.example.com/v1')).toBeVisible(); expect(consent()).not.toBeChecked(); expect(enable()).toBeDisabled(); expect(mutateRaw).not.toHaveBeenCalled(); });
    it('rejects a stale write without automatically replaying it', async () => { await prepare(); vi.mocked(mutateRaw).mockRejectedValue(new APIError('unsafe private upstream text', 409)); fireEvent.click(enable()); await flush(); expect(screen.getByRole('alert')).toHaveTextContent('provider or settings changed'); expect(screen.queryByText('unsafe private upstream text')).not.toBeInTheDocument(); expect(request).toHaveBeenCalledTimes(1); refresh(); await flush(); expect(consent()).not.toBeChecked(); expect(enable()).toBeDisabled(); expect(mutateRaw).toHaveBeenCalledTimes(1); });
    it('treats failed/invalid write responses as uncertain and clears approval', async () => { await prepare(); vi.mocked(mutateRaw).mockResolvedValue({ ...fixture(), logsAllowed: true }); fireEvent.click(enable()); await flush(); expect(screen.getByRole('alert')).toHaveTextContent('may already have taken effect'); expect(screen.queryByRole('checkbox')).not.toBeInTheDocument(); });
    it('deduplicates rapid repeated refreshes and ignores a response after unmount', async () => { const pending = deferred<unknown>(); vi.mocked(request).mockReturnValue(pending.promise); const mounted = render(<ProactiveAISettingsPanel/>); fireEvent.click(button('Refresh proactive AI settings')); fireEvent.click(button('Refresh proactive AI settings')); expect(request).toHaveBeenCalledTimes(1); const signal = vi.mocked(request).mock.calls[0][1]!.signal!; mounted.unmount(); expect(signal.aborted).toBe(true); await act(async () => pending.resolve(fixture())); expect(mutateRaw).not.toHaveBeenCalled(); });
    it('bounds reads at ten seconds and rejects late responses', async () => { const pending = deferred<unknown>(); vi.mocked(request).mockReturnValue(pending.promise); render(<ProactiveAISettingsPanel/>); await advance(10000); expect(screen.getByRole('alert')).toHaveTextContent('did not respond in time'); await act(async () => pending.resolve(fixture())); expect(screen.queryByText('Off')).not.toBeInTheDocument(); });
    it('bounds writes at ten seconds and requires an explicit read afterward', async () => { await prepare(); const pending = deferred<unknown>(); vi.mocked(mutateRaw).mockReturnValue(pending.promise); fireEvent.click(enable()); await advance(10000); expect(screen.getByRole('alert')).toHaveTextContent('may already have taken effect'); await act(async () => pending.resolve({ ...fixture(), enabled: true, deviceIds: [id] })); expect(request).toHaveBeenCalledTimes(1); expect(mutateRaw).toHaveBeenCalledTimes(1); expect(screen.queryByText('On')).not.toBeInTheDocument(); });
    it('clears idle snapshots at sixty seconds or on clock changes', async () => { await prepare(); await advance(60000); expect(screen.getByRole('status')).toHaveTextContent('review current settings'); refresh(); await flush(); vi.setSystemTime(Date.now() + 10000); await advance(1000); expect(screen.queryByRole('checkbox')).not.toBeInTheDocument(); });
    it('does not revive old approval after hide/focus', async () => { await prepare(); act(() => window.dispatchEvent(new Event('blur'))); act(() => window.dispatchEvent(new Event('focus'))); expect(screen.queryByRole('checkbox')).not.toBeInTheDocument(); expect(request).toHaveBeenCalledTimes(1); refresh(); await flush(); expect(consent()).not.toBeChecked(); });
    it('aborts writes on navigation and ignores late success', async () => { await prepare(); const pending = deferred<unknown>(); vi.mocked(mutateRaw).mockReturnValue(pending.promise); fireEvent.click(enable()); const signal = vi.mocked(mutateRaw).mock.calls[0][3]!; act(() => window.dispatchEvent(new Event('hashchange'))); expect(signal.aborted).toBe(true); await act(async () => pending.resolve({ ...fixture(), enabled: true, deviceIds: [id] })); expect(screen.getByRole('alert')).toHaveTextContent('may already have taken effect'); });
    it('locks on session revocation and cannot refresh', async () => { await prepare(); act(() => { abortProtectedRequests(); window.dispatchEvent(new Event(AUTH_REQUIRED_EVENT)); }); expect(screen.getByRole('alert')).toHaveTextContent('session or permissions changed'); expect(button('Refresh proactive AI settings')).toBeDisabled(); expect(screen.queryByRole('checkbox')).not.toBeInTheDocument(); });
    it('locks on cross-tab logout', async () => { await prepare(); act(() => { localStorage.setItem(LOGOUT_INTENT_KEY, '1'); window.dispatchEvent(new StorageEvent('storage', { key: LOGOUT_INTENT_KEY })); }); expect(button('Refresh proactive AI settings')).toBeDisabled(); });
});
