import { InventoryLiveStatus } from './inventory-live-status';
import { useId } from 'react';
import { Info, LoaderCircle, RefreshCw, Search, TriangleAlert } from 'lucide-react';
import { useOperator } from './auth';
import { useLocale } from './i18n';
import { inventoryAge } from './complete-packages-types';
import { systemAgeStatus, systemFilters, systemPageSize, systemSectionVisible } from './system-inventory-types';
import type { SocketRow, SystemFilter, SystemReason, SystemSection } from './system-inventory-types';
import { validJournalUnit } from './journal-types';
import { useSystemInventory } from './system-inventory-resource';
import { useServiceActions } from './service-action-resource';
import { serviceActionLabel, ServiceActionPanel } from './service-actions';
import './package-observations.css';
import './complete-packages.css';

const copy = {
    en: {
        logs: 'Open logs', logHint: 'Opens Logs with this service selected. Capture requires a separate confirmation and local permission.', services: 'System services', sockets: 'Local sockets and connections', access: 'Authenticated LAN operator access is required.', refresh: 'Refresh section and restart', loading: 'Reading system inventory…',
        intro: 'Linux observations in the agent-visible namespace. Complete enumeration does not establish device health.',
        network: 'Connection rows and process attribution have separate coverage. “Permission denied” under Attribution applies to the owner field. Collection failures appear in the section status.',
        not_configured: 'System inventory not configured', unknown: 'System inventory not configured or identity not eligible', awaiting: 'Awaiting system observations', fresh: 'Within the collection window', stale: 'Stale / historical observations', revoked: 'Device identity revoked', expired: 'Observations or identity expired',
        configured: 'Requires fresh managed-operations-v3 enrollment and explicit consent. Existing profiles keep their scope.',
        noComplete: 'No retained complete section is available. Missing or failed data is not a successful zero-row observation.', latestFailed: 'Latest section collection failed', prior: 'Showing the prior complete section at its original age. Newer attempts do not refresh it.',
        loadError: 'The manager could not be read. Retry or refresh this section.', invalid: 'The manager returned inconsistent or unsupported system inventory. Rows were cleared.', timeout: 'The request timed out. Retry or refresh this section.', session: 'Your session has ended. Sign in again.', clock: 'The time anchor is no longer reliable. Refresh before continuing.', busy: 'The manager is busy. Retry in a moment.', restart: 'The section generation or paging session changed or expired. Refresh to explicitly restart; previous rows were cleared.', searchInvalid: 'Search allows at most 128 UTF-8 bytes without control or formatting characters.',
        details: 'Source and collection details', ownerSource: 'Socket owner source: locally approved metadata helper', ownerSourceLimits: 'Original helper observations in the systemd PID 1 local namespace. This source does not guarantee every owner was visible or that permission is still enabled.', ownerStarted: 'Helper capture started', ownerFinished: 'Helper capture finished', scope: 'Read-only collection performs no network scan or DNS lookup and collects no raw logs, command lines, environment variables or UIDs. Numeric endpoints may expose private topology; a listener does not establish external reachability.', generation: 'Original generation', sequence: 'Original sequence', collected: 'Original observation time', count: 'Whole retained section', age: 'Observation age (minutes)', scanned: 'Rows scanned so far', matches: 'Matches found so far', shown: 'Rows on this page',
        search: 'Search this section', filter: 'Section filter', submit: 'Apply', all: 'All rows', active: 'Active services', failed: 'Failed services', enabled: 'Enabled services', 'tcp-listeners': 'TCP listeners', udp: 'UDP sockets', connections: 'Connections',
        scanHint: 'Up to 2,048 rows scanned per request. Continue for all matches; filters do not change the section total.', next: 'Next page', continue: 'Continue search or filter', retry: 'Retry request', emptyWindow: 'No matches in this scan window. More rows remain; continue.', zero: 'Successful complete enumeration contained zero rows in this section.', noMatches: 'No matches in the complete section.', noMore: 'No further matches; earlier pages contained matches.', finished: 'The entire retained section has been scanned.', more: 'More rows remain in this section.',
        service: 'Service unit', load: 'Load state', runtime: 'Active state', sub: 'Substate', enablement: 'Enablement', mainPid: 'Main PID', notObserved: 'Not observed', notCollected: 'Not collected',
        protocol: 'Protocol / family', local: 'Local endpoint', remote: 'Remote endpoint', state: 'Socket state', kind: 'Kind', owners: 'PID / process name', attribution: 'Attribution', nameUnknown: 'Process name unknown', noneOwners: 'Owner unknown', observed: 'Observed', partial: 'Partial', unavailable: 'Unavailable', listener: 'Listener', bound: 'Bound', connection: 'Connection', unclassified: 'Unclassified',
        none: 'No failure reported', source_missing: 'Source unavailable', permission_denied: 'Permission denied', not_supported: 'Not supported', invalid_source: 'Invalid source', read_failed: 'Read failed', item_limit: 'Row rejection limit reached', byte_limit: 'Byte rejection limit reached', collector_busy: 'Collector busy', not_collected: 'Not collected', no_match: 'No owner match', process_gone: 'Process no longer available', work_limit: 'Attribution work limit reached', owner_limit: 'Owner limit reached', timeoutReason: 'Collection timed out',
        limits: 'Sections expire 24 hours after observation. Source, time and storage limits can reject capture; limits do not establish device capacity.',
    },
    de: {
        logs: 'Logs öffnen', logHint: 'Öffnet Logs mit diesem Dienst. Eine Erfassung erfordert eine separate Bestätigung und lokale Freigabe.', services: 'Systemdienste', sockets: 'Lokale Sockets und Verbindungen', access: 'Ein authentifizierter LAN-Operator-Zugang ist erforderlich.', refresh: 'Abschnitt aktualisieren und neu beginnen', loading: 'Systeminventar wird gelesen…',
        intro: 'Linux-Beobachtungen im sichtbaren Agent-Namensraum. Vollständige Aufzählung belegt keinen Gerätezustand.',
        network: 'Verbindungen und Prozesszuordnung haben eine eigene Abdeckung. „Berechtigung verweigert“ unter Zuordnung betrifft das Eigentümerfeld. Erfassungsfehler stehen im Abschnittsstatus.',
        not_configured: 'Systeminventar nicht eingerichtet', unknown: 'Systeminventar nicht eingerichtet oder Identität nicht berechtigt', awaiting: 'Systembeobachtungen ausstehend', fresh: 'Im Erfassungszeitfenster', stale: 'Veraltete / historische Beobachtungen', revoked: 'Geräteidentität widerrufen', expired: 'Beobachtungen oder Identität abgelaufen',
        configured: 'Benötigt neues managed-operations-v3-Enrollment mit ausdrücklicher Zustimmung. Bestehende Profile behalten ihren Umfang.',
        noComplete: 'Kein vollständiger gespeicherter Abschnitt verfügbar. Fehlende oder fehlgeschlagene Daten sind keine erfolgreich leere Beobachtung.', latestFailed: 'Neueste Abschnittserfassung fehlgeschlagen', prior: 'Vorheriger vollständiger Abschnitt mit ursprünglichem Alter. Neuere Versuche erneuern es nicht.',
        loadError: 'Der Manager konnte nicht gelesen werden. Anfrage wiederholen oder Abschnitt aktualisieren.', invalid: 'Der Manager lieferte widersprüchliches oder nicht unterstütztes Systeminventar. Zeilen wurden entfernt.', timeout: 'Die Anfrage hat das Zeitlimit überschritten. Wiederholen oder Abschnitt aktualisieren.', session: 'Die Sitzung ist beendet. Erneut anmelden.', clock: 'Der Zeitanker ist nicht mehr verlässlich. Vor dem Fortfahren aktualisieren.', busy: 'Der Manager ist ausgelastet. Gleich erneut versuchen.', restart: 'Die Abschnittsgeneration oder Seitensitzung wurde geändert oder ist abgelaufen. Zum ausdrücklichen Neubeginn aktualisieren; vorherige Zeilen wurden entfernt.', searchInvalid: 'Die Suche erlaubt höchstens 128 UTF-8-Bytes ohne Steuer- oder Formatierungszeichen.',
        details: 'Quelle und Erfassungsdetails', ownerSource: 'Quelle der Socket-Zuordnung: lokal freigegebener Metadaten-Helper', ownerSourceLimits: 'Ursprüngliche Helper-Beobachtungen im lokalen Namensraum von systemd-PID 1. Diese Quelle garantiert weder die Sichtbarkeit jedes Eigentümers noch eine weiterhin aktive Freigabe.', ownerStarted: 'Beginn der Helper-Erfassung', ownerFinished: 'Ende der Helper-Erfassung', scope: 'Die lesende Erfassung führt weder Netzwerkscans noch DNS-Abfragen aus und erfasst keine Rohprotokolle, Befehlszeilen, Umgebungsvariablen oder UIDs. Numerische Endpunkte können private Topologie offenlegen; ein Listener belegt keine Erreichbarkeit von außen.', generation: 'Ursprüngliche Generation', sequence: 'Ursprüngliche Sequenz', collected: 'Ursprünglicher Beobachtungszeitpunkt', count: 'Gesamter gespeicherter Abschnitt', age: 'Alter der Beobachtung (Minuten)', scanned: 'Bisher geprüfte Zeilen', matches: 'Bisher gefundene Treffer', shown: 'Zeilen auf dieser Seite',
        search: 'Abschnitt durchsuchen', filter: 'Abschnittsfilter', submit: 'Anwenden', all: 'Alle Zeilen', active: 'Aktive Dienste', failed: 'Fehlgeschlagene Dienste', enabled: 'Aktivierte Dienste', 'tcp-listeners': 'TCP-Listener', udp: 'UDP-Sockets', connections: 'Verbindungen',
        scanHint: 'Bis zu 2.048 Zeilen geprüft je Anfrage. Für alle Treffer fortsetzen; Filter ändern die Gesamtzahl nicht.', next: 'Nächste Seite', continue: 'Suche oder Filter fortsetzen', retry: 'Anfrage wiederholen', emptyWindow: 'Keine Treffer in diesem Suchabschnitt. Weitere Zeilen stehen aus; fortsetzen.', zero: 'Die erfolgreiche vollständige Aufzählung enthielt keine Zeilen in diesem Abschnitt.', noMatches: 'Keine Treffer im vollständigen Abschnitt.', noMore: 'Keine weiteren Treffer; frühere Seiten enthielten Treffer.', finished: 'Der gesamte gespeicherte Abschnitt wurde durchsucht.', more: 'Weitere Zeilen dieses Abschnitts stehen aus.',
        service: 'Dienst-Unit', load: 'Ladezustand', runtime: 'Aktivzustand', sub: 'Unterzustand', enablement: 'Aktivierung', mainPid: 'Haupt-PID', notObserved: 'Nicht beobachtet', notCollected: 'Nicht erfasst',
        protocol: 'Protokoll / Familie', local: 'Lokaler Endpunkt', remote: 'Entfernter Endpunkt', state: 'Socket-Zustand', kind: 'Art', owners: 'PID / Prozessname', attribution: 'Zuordnung', nameUnknown: 'Prozessname unbekannt', noneOwners: 'Eigentümer unbekannt', observed: 'Beobachtet', partial: 'Teilweise', unavailable: 'Nicht verfügbar', listener: 'Listener', bound: 'Gebunden', connection: 'Verbindung', unclassified: 'Nicht klassifiziert',
        none: 'Kein Fehler gemeldet', source_missing: 'Quelle nicht verfügbar', permission_denied: 'Berechtigung verweigert', not_supported: 'Nicht unterstützt', invalid_source: 'Ungültige Quelle', read_failed: 'Lesen fehlgeschlagen', item_limit: 'Ablehnungsgrenze für Zeilen erreicht', byte_limit: 'Ablehnungsgrenze für Bytes erreicht', collector_busy: 'Collector ausgelastet', not_collected: 'Nicht erfasst', no_match: 'Keine Eigentümerzuordnung', process_gone: 'Prozess nicht mehr verfügbar', work_limit: 'Arbeitsgrenze für Zuordnung erreicht', owner_limit: 'Eigentümergrenze erreicht', timeoutReason: 'Erfassung hat Zeitlimit überschritten',
        limits: 'Abschnitte laufen 24 Stunden nach Beobachtung ab. Quellen-, Zeit- und Speichergrenzen können Erfassungen ablehnen; sie belegen keine Gerätekapazität.',
    },
};
export function SystemInventoryPanel({ deviceId, section, sessionKey, onOpenLogs }: { deviceId: string; section: SystemSection; sessionKey?: string | number; onOpenLogs?: (unit: string) => void }) {
    const operator = useOperator(), [locale] = useLocale();
    if (!operator || operator.mode !== 'lan' || !operator.authenticated) return <p>{copy[locale].access}</p>;
    return <SystemInventory key={`${deviceId}:${section}:${sessionKey ?? operator.expiresAt ?? ''}`} deviceId={deviceId} section={section} onOpenLogs={onOpenLogs}/>;
}
function SystemInventory({ deviceId, section, onOpenLogs }: { deviceId: string; section: SystemSection; onOpenLogs?: (unit: string) => void }) {
    const [locale] = useLocale(), labels = copy[locale], id = useId(), resource = useSystemInventory(deviceId, section, true), operator = useOperator();
    const actionAccess = section === 'services' && operator?.mode === 'lan' && operator.authenticated && operator.loginMode === 'named' && operator.actorId && operator.expiresAt && operator.capabilities?.includes('restart_service') ? { actorId: operator.actorId, sessionKey: operator.expiresAt, insecureTestMode: operator.insecureTestMode } : null;
    const actions = useServiceActions(deviceId, actionAccess);
    const { view, page } = resource, complete = view?.lastComplete[section], latest = view?.latest?.[section], visible = view && systemSectionVisible(view, section, resource.elapsed);
    const number = (n: number) => new Intl.NumberFormat(locale).format(n);
    const reason = (r: SystemReason) => labels[r === 'timeout' ? 'timeoutReason' : r];
    const field = (label: string, value: string) => <div><dt>{label}</dt><dd>{value}</dd></div>;
    const endpoint = (value: SocketRow['local']) => `${value.address.includes(':') ? `[${value.address}]` : value.address}:${value.port}`;
    return <section className="package-observations system-inventory" aria-labelledby={id} aria-busy={resource.loading}>
        <header className="package-heading"><h3 id={id}>{labels[section]}</h3><button className="button small" disabled={resource.loading || resource.error === 'session'} onClick={resource.refresh} aria-label={labels.refresh} title={labels.refresh}><RefreshCw size={14}/>{locale === 'de' ? 'Aktualisieren' : 'Refresh'}</button></header>
        {section === 'services' && <ServiceActionPanel workflow={actions} authorized={!!actionAccess}/>}
        <p className="package-note">{labels.intro}</p>{section === 'sockets' && <p className="package-note">{labels.network}</p>}
        <InventoryLiveStatus state={resource.liveState}/>
        {resource.loading && <p role="status"><LoaderCircle className="spin" size={16}/>{labels.loading}</p>}
        {resource.error && <p className="package-error" role="alert"><TriangleAlert size={16}/>{labels[resource.error]}</p>}
        {['busy', 'timeout', 'loadError'].includes(resource.error ?? '') && <button className="button small" disabled={resource.loading} onClick={resource.retry}>{labels.retry}</button>}
        {view && <>
            <p className="package-status" hidden={Boolean(complete && visible && latest?.generationId === complete.meta.generationId)}>{labels[view.status === 'fresh' && view.latest ? systemAgeStatus(view.serverNow, view.latest.collectedAt, resource.elapsed) : view.status]}</p>
            {(view.status === 'unknown' || view.status === 'not_configured') && <p>{labels.configured}</p>}
            {latest?.coverage === 'failed' && <p className="package-error" role="status">{labels.latestFailed}: {reason(latest.reason)}</p>}
            {!visible && <p>{labels.noComplete}</p>}
            {complete && visible && <>
                {latest?.generationId !== complete.meta.generationId && <p className="package-note">{labels.prior}</p>}
                <p className={`package-status package-status-${systemAgeStatus(view.serverNow, complete.meta.observedAt, resource.elapsed)}`}>{labels[systemAgeStatus(view.serverNow, complete.meta.observedAt, resource.elapsed)]}</p>
                <dl className="package-facts">{field(labels.collected, complete.meta.observedAt)}{field(labels.count, number(complete.meta.observedCount!))}{field(labels.age, number(Math.floor((inventoryAge(view.serverNow, complete.meta.observedAt) + resource.elapsed) / 60000)))}</dl>
                <details className="overview-provenance"><summary>{labels.details}</summary><dl className="package-facts">{field(labels.generation, complete.meta.generationId)}{field(labels.sequence, complete.sequence)}</dl><p className="package-note">{labels.scope}</p>{section === 'sockets' && complete.socketOwnerProvenance && <><p className="package-note">{labels.ownerSource}</p><dl className="package-facts">{field(labels.ownerStarted, complete.socketOwnerProvenance.startedAt)}{field(labels.ownerFinished, complete.socketOwnerProvenance.finishedAt)}</dl><p className="package-note">{labels.ownerSourceLimits}</p></>}</details>
                <form className="complete-package-search" onSubmit={event => { event.preventDefault(); resource.startSearch(); }}><label htmlFor={`${id}-search`}>{labels.search}</label><div><input id={`${id}-search`} type="search" value={resource.search} onChange={event => resource.changeSearch(event.target.value)} maxLength={128} autoComplete="off" spellCheck={false}/><label className="sr-only" htmlFor={`${id}-filter`}>{labels.filter}</label><select id={`${id}-filter`} value={resource.filter} onChange={event => resource.changeFilter(event.target.value as SystemFilter)}>{systemFilters[section].map(value => <option key={value} value={value}>{labels[value]}</option>)}</select><button type="submit" className="button" disabled={resource.loading}><Search size={15}/>{labels.submit}</button></div><p className="package-note">{labels.scanHint} {locale === 'de' ? 'Zeilen je Seite:' : 'Rows per page:'} {systemPageSize(section)}.</p></form>
                {page && <>
                    <dl className="package-counts">{field(labels.scanned, `${number(resource.scanned)} / ${number(page.totalRows)}`)}{field(labels.matches, number(resource.matches))}{field(labels.shown, number(page.returnedCount))}</dl>
                    {page.returnedCount > 0 ? <div className="package-table-scroll" role="region" aria-label={labels[section]} tabIndex={0}><table><caption className="sr-only">{labels[section]}</caption>{section === 'services' ? <><thead><tr>{[labels.service, labels.load, labels.runtime, labels.sub, labels.enablement, labels.mainPid, ...(onOpenLogs ? [labels.logs] : []), ...(actionAccess ? [serviceActionLabel(locale)] : [])].map(text => <th key={text} scope="col">{text}</th>)}</tr></thead><tbody>{page.services.map(row => <tr key={row.name}><th scope="row">{row.name}</th><td>{row.runtime?.loadState ?? labels.notObserved}</td><td>{row.runtime?.activeState ?? labels.notObserved}</td><td>{row.runtime?.subState ?? labels.notObserved}</td><td>{row.enablement ?? labels.notObserved}</td><td>{labels.notCollected}</td>{onOpenLogs && <td>{validJournalUnit(row.name) && <button type="button" className="text-button service-logs-link" aria-label={`${labels.logs}: ${row.name}`} title={labels.logHint} onClick={() => onOpenLogs(row.name)}>{labels.logs}</button>}</td>}{actionAccess && <td><button type="button" className="text-button" aria-label={`${serviceActionLabel(locale)}: ${row.name}`} disabled={!actions.canSelect(row.name)} onClick={() => actions.select(row.name)}>{serviceActionLabel(locale)}</button></td>}</tr>)}</tbody></> : <><thead><tr>{[labels.protocol, labels.local, labels.remote, labels.state, labels.kind, labels.owners, labels.attribution].map(text => <th key={text} scope="col">{text}</th>)}</tr></thead><tbody>{page.sockets.map((row, index) => <tr key={index}><th scope="row">{row.protocol.toUpperCase()} / {row.family}</th><td>{endpoint(row.local)}</td><td>{endpoint(row.remote)}</td><td>{row.state}</td><td>{labels[row.kind]}</td><td>{row.owners.length ? <ul className="system-owners">{row.owners.map(owner => <li key={owner.pid}>{owner.pid} / {owner.processName ?? `${labels.nameUnknown} (${reason(owner.nameReason)})`}</li>)}</ul> : labels.noneOwners}</td><td>{labels[row.attribution.coverage]}{row.attribution.reason !== 'none' && <> · {reason(row.attribution.reason)}</>}</td></tr>)}</tbody></>}</table></div> : <p role="status">{!page.exhausted ? labels.emptyWindow : page.totalRows === 0 ? labels.zero : resource.matches === 0 ? labels.noMatches : labels.noMore}</p>}
                    <div className="complete-package-pagination"><p>{page.exhausted ? labels.finished : labels.more}</p>{!page.exhausted && <button className="button" disabled={resource.loading} onClick={resource.next}>{resource.search.trim() || resource.filter !== 'all' ? labels.continue : labels.next}</button>}</div>
                </>}
            </>}
        </>}
        <p className="package-note package-retention"><Info size={16}/>{labels.limits}</p>
    </section>;
}
