import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { APIError, AUTH_REQUIRED_EVENT, request } from './api';
import { setLocale } from './i18n';
import { WindowsInventoryWorkspace } from './windows-inventory';
import { useWindowsInventory } from './windows-inventory-resource';
import { validWindowsInventoryView, type WindowsInventoryView } from './windows-inventory-types';
import { windowsDeviceId, windowsNow, windowsView } from './windows-inventory-fixture';
import { windowsVolumes } from './windows-volumes-fixture';
import { windowsNetwork } from './windows-network-fixture';
import { validWindowsNetwork, WINDOWS_NETWORK_BYTES, WINDOWS_NETWORK_STATES, type WindowsNetwork } from './windows-network-types';
vi.mock('./api', async original => ({ ...await original<typeof import('./api')>(), request: vi.fn() }));
const flush = () => act(async () => {});
function view(): WindowsInventoryView & { network: WindowsNetwork } { return { ...windowsView(), network: windowsNetwork() }; }
function Harness({ id = windowsDeviceId, session = 'fixture', enabled = true }: { id?: string; session?: string; enabled?: boolean }) { return <WindowsInventoryWorkspace resource={useWindowsInventory(id, enabled, session)}/>; }
async function network() { fireEvent.click(screen.getByRole('tab', { name: 'Network' })); await screen.findByText('[2001:db8::80]:443'); }
function single(address = '0.0.0.0', family: 'ipv4' | 'ipv6' = 'ipv4'): WindowsNetwork { const v = windowsNetwork(); v.rows = [{ ...v.rows[0], family, localAddress: address, remoteAddress: address, remotePort: 0, state: 'established' }]; v.observedCount = 1; return v; }
beforeEach(() => { setLocale('en', false); vi.mocked(request).mockReset().mockResolvedValue(view()); });
afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks(); });

describe('Windows network strict contract', () => {
    it('accepts every independent combination of the four optional capabilities', () => {
        for (let flags = 0; flags < 16; flags++) {
            const v = windowsView();
            if (flags & 1) v.events = { schemaVersion: 'tracebolt.windows-event-metadata.v1', scope: 'windows-application-system-event-headers-v1', grantId: 'e'.repeat(32), generationId: v.snapshot!.generationId, collectedAt: '2026-10-07T12:00:02Z', channels: ['Application', 'System'].map(channel => ({ channel: channel as 'Application' | 'System', quality: 'observed', reason: '', complete: true, truncated: false, observedCount: 0, rows: [] })) };
            if (flags & 2) v.volumes = windowsVolumes();
            if (flags & 4) v.processMetrics = { schemaVersion: 'tracebolt.windows-process-metrics.v1', scope: 'windows-process-metrics-v1', grantId: 'b'.repeat(32), generationId: v.snapshot!.generationId, collectedAt: '2026-10-07T12:00:02Z', observedCount: 1, truncated: false, rows: [{ pid: 44, cpuPercent: null, cpuQuality: 'first-sample', memoryBytes: '42', memoryQuality: 'observed' }] };
            if (flags & 8) v.network = windowsNetwork();
            expect(validWindowsInventoryView(v, windowsDeviceId), `combination ${flags}`).toBe(true);
        }
    });
    const mutations: [string, (v: WindowsNetwork) => void][] = [
        ['unknown snapshot member', v => Object.assign(v, { message: 'private' })], ['unknown endpoint member', v => Object.assign(v.rows[0], { processName: 'invented.exe' })], ['ungranted scope', v => Object.assign(v, { scope: 'windows-inventory-v1' })], ['unknown version', v => Object.assign(v, { schemaVersion: 'tracebolt.windows-network-endpoints.v2' })], ['missing grant', v => { v.grantId = ''; }], ['foreign generation', v => { v.generationId = `sample_${'b'.repeat(32)}`; }],
        ['noncanonical PID', v => { v.rows[0].pid = -0; }], ['negative PID', v => { v.rows[0].pid = -1; }], ['PID overflow', v => { v.rows[0].pid = 4294967296; }], ['fractional PID', v => { v.rows[0].pid = 1.5; }], ['local port overflow', v => { v.rows[0].localPort = 65536; }], ['remote port overflow', v => { v.rows[0].remotePort = 65536; }], ['negative local port', v => { v.rows[0].localPort = -1; }], ['noncanonical port', v => { v.rows[0].remotePort = -0; }], ['string port', v => Object.assign(v.rows[0], { localPort: '135' })],
        ['missing TCP remote address', v => { v.rows[1].remoteAddress = null; }], ['missing TCP remote port', v => { v.rows[1].remotePort = null; }], ['listener peer address', v => { v.rows[0].remoteAddress = '0.0.0.0'; }], ['listener peer port', v => { v.rows[0].remotePort = 0; }], ['missing TCP state', v => { v.rows[0].state = null; }], ['invented TCP state', v => Object.assign(v.rows[0], { state: 'unknown' })], ['UDP remote address', v => { v.rows[2].remoteAddress = '192.0.2.1'; }], ['UDP remote port', v => { v.rows[2].remotePort = 0; }], ['UDP state', v => { v.rows[2].state = 'listen'; }], ['unknown protocol', v => Object.assign(v.rows[0], { protocol: 'icmp' })], ['wrong family', v => { v.rows[0].family = 'ipv6'; }],
        ['count below rows', v => { v.observedCount = 3; }], ['count without omission', v => { v.observedCount = 5; }], ['omission without count', v => { v.truncated = true; }], ['count overflow', v => { v.observedCount = 16385; v.truncated = true; }], ['negative zero count', v => { v.observedCount = -0; v.rows = []; }], ['unsorted rows', v => { v.rows.reverse(); }], ['false observed exactness', v => { v.countExact = false; }], ['false partial exactness', v => { v.quality = 'partial'; }], ['denied data', v => { v.quality = 'denied'; v.countExact = false; }], ['unknown quality', v => Object.assign(v, { quality: 'healthy' })],
        ['expired capture', v => { v.collectedAt = '2026-10-06T12:00:10Z'; }], ['future capture', v => { v.collectedAt = '2026-10-07T12:00:40.000000001Z'; }], ['invalid date', v => { v.collectedAt = '2026-02-30T12:00:00Z'; }], ['non-UTC date', v => { v.collectedAt = '2026-10-07T12:00:03+00:00'; }],
    ];
    it.each(mutations)('rejects %s', (_name, mutate) => { const v = windowsNetwork(); mutate(v); expect(validWindowsNetwork(v, windowsNetwork().generationId, windowsNow)).toBe(false); });
    it.each(['example.com', 'http://192.0.2.1', '192.000.2.1', '192.0.2.256', '0x7f000001', '127.1', '192.0.2.1%4', '192.0.2.1:80', ' 192.0.2.1', '<img>'])('rejects nonnumeric or noncanonical IPv4 %s', value => { const v = single(value); expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(false); });
    it.each(['FE80::1', '2001:0db8::1', '[::1]', 'fe80::1%eth0', 'fe80::1%0', 'fe80::1%01', 'fe80::1%4294967296', 'fe80::1%4%5', '::ffff:c000:201', '2001:db8:::1', '1::2::3', '::1/128'])('rejects noncanonical IPv6 %s', value => { const v = single(value, 'ipv6'); expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(false); });
    it.each([['0.0.0.0', 'ipv4'], ['127.0.0.1', 'ipv4'], ['224.0.0.1', 'ipv4'], ['255.255.255.255', 'ipv4'], ['::', 'ipv6'], ['::1', 'ipv6'], ['ff02::1%4', 'ipv6'], ['fe80::1%4294967295', 'ipv6'], ['::ffff:192.0.2.1', 'ipv6']] as const)('accepts real endpoint address %s', (value, family) => { const v = single(value, family); expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(true); });
    it('supports every reported TCP state without inferring one', () => { for (const state of WINDOWS_NETWORK_STATES) { const v = single(); v.rows[0].state = state; if (state === 'listen') { v.rows[0].remoteAddress = null; v.rows[0].remotePort = null; } expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(true); } });
    it('supports truthful complete, exact trimmed, partial-empty and failed table states', () => {
        const v = windowsNetwork(); Object.assign(v, { observedCount: 12, truncated: true }); expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(true);
        Object.assign(v, { quality: 'partial', countExact: false, observedCount: 16384 }); expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(true);
        Object.assign(v, { rows: [], observedCount: 0, truncated: false }); expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(true);
        for (const quality of ['denied', 'unavailable', 'observed'] as const) { Object.assign(v, { quality, countExact: quality === 'observed' }); expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(true); }
    });
    it('sorts addresses and scope IDs numerically, while preserving duplicate API tuples', () => {
        const v = single('fe80::1%2', 'ipv6'); v.rows.push({ ...v.rows[0], localAddress: 'fe80::1%10' }); v.observedCount = 2; expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(true);
        v.rows.reverse(); expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(false);
        v.rows = [windowsNetwork().rows[2], windowsNetwork().rows[2]]; expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(true);
        v.rows = [{ ...v.rows[0], localAddress: '192.0.2.2' }, { ...v.rows[0], localAddress: '192.0.2.10' }]; expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(true);
        v.rows.reverse(); expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(false);
    });
    it('sorts absent listener peers before established peers on the same local endpoint', () => {
        const v = single(); v.rows.unshift({ ...v.rows[0], state: 'listen', remoteAddress: null, remotePort: null }); v.observedCount = 2; expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(true); v.rows.reverse(); expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(false);
    });
    it('enforces separate row and encoded-byte limits', () => {
        const v = windowsNetwork(); v.rows = Array.from({ length: 65 }, () => ({ ...v.rows[2] })); v.observedCount = 65; expect(validWindowsNetwork(v, v.generationId, windowsNow)).toBe(false);
        const large = single('ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff%4294967295', 'ipv6'); large.rows = Array.from({ length: 64 }, () => ({ ...large.rows[0], localPort: 65535, remotePort: 65535, pid: 4294967295 })); large.observedCount = 64;
        expect(new TextEncoder().encode(JSON.stringify(large)).length).toBeGreaterThan(WINDOWS_NETWORK_BYTES); expect(validWindowsNetwork(large, large.generationId, windowsNow)).toBe(false);
    });
    it('rejects explicit null, unknown alias, missing inventory and capture beyond receipt skew', () => {
        expect(validWindowsInventoryView({ ...windowsView(), network: null }, windowsDeviceId)).toBe(false);
        expect(validWindowsInventoryView({ ...windowsView(), windowsNetwork: windowsNetwork() }, windowsDeviceId)).toBe(false);
        for (const status of ['revoked', 'unavailable', 'awaiting', 'not_configured']) expect(validWindowsInventoryView({ ...view(), status, snapshot: null }, windowsDeviceId)).toBe(false);
        const v = view(); v.network.collectedAt = '2026-10-07T11:59:59.999999999Z'; expect(validWindowsInventoryView(v, windowsDeviceId)).toBe(false); v.network.collectedAt = '2026-10-07T12:00:31.000000001Z'; expect(validWindowsNetwork(v.network, v.snapshot!.generationId, v.serverNow)).toBe(true); expect(validWindowsInventoryView(v, windowsDeviceId)).toBe(false);
    });
});

describe('Network subtab and shared privacy lifecycle', () => {
    it('renders numeric endpoints, genuine zeros, TCP states and API PIDs without links or process joins', async () => {
        render(<Harness/>); await network();
        expect(screen.getByText('0.0.0.0:135')).toBeVisible(); expect(screen.queryByText('0.0.0.0:0')).toBeNull(); expect(within(screen.getByText('0.0.0.0:135').closest('tr')!).getByText('Not applicable')).toBeVisible(); expect(screen.getByText('[fe80::40%4]:5353')).toBeVisible(); expect(screen.getByText('listen')).toBeVisible(); expect(screen.getByText('established')).toBeVisible();
        const udp = screen.getByText('127.0.0.1:5353').closest('tr')!; expect(within(udp).getAllByText('Not applicable')).toHaveLength(2); expect(within(udp).getByText('42')).toBeVisible(); expect(within(screen.getByText('[fe80::40%4]:5353').closest('tr')!).getByText('Unavailable')).toBeVisible(); expect(within(screen.getByText('[fe80::40%4]:5353').closest('tr')!).queryByText('0')).toBeNull(); expect(screen.queryByText('fixture.exe')).toBeNull(); expect(screen.queryByRole('link')).toBeNull(); expect(screen.queryByRole('button', { name: /connect|kill|terminate|stop/i })).toBeNull();
        expect(document.querySelector('time[datetime="2026-10-07T12:00:03Z"]')).not.toBeNull(); expect(document.querySelector('time[datetime="2026-10-07T12:00:01Z"]')).not.toBeNull();
        fireEvent.click(screen.getByText('Scope & attribution')); expect(screen.getByText(/not a verified executable identity/)).toBeVisible();
    });
    it('shows unconfigured scope without inventing healthy or empty observations', async () => { vi.mocked(request).mockResolvedValue(windowsView()); render(<Harness/>); await flush(); fireEvent.click(screen.getByRole('tab', { name: 'Network' })); expect(screen.getByText(/Network endpoints are not configured/)).toBeVisible(); expect(screen.queryByRole('table')).toBeNull(); });
    it.each(['denied', 'unavailable', 'partial'] as const)('replaces old endpoints with truthful %s without successful zero', async quality => {
        render(<Harness/>); await network(); const v = view(); Object.assign(v.network, { quality, countExact: false, rows: [], observedCount: 0 }); vi.mocked(request).mockResolvedValue(v); fireEvent.click(screen.getByRole('button', { name: 'Refresh Windows inventory' })); await screen.findByText('No endpoint rows available; this does not establish an empty network.'); expect(screen.queryByText('[2001:db8::80]:443')).toBeNull(); expect(screen.queryByText('0 shown · 0 observed')).toBeNull(); expect(screen.queryByText('Enumeration complete within scope')).toBeNull();
    });
    it('shows exact omission and partial lower-bound counts', async () => { const v = view(); Object.assign(v.network, { observedCount: 100, truncated: true }); vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await network(); expect(screen.getByText('Bounded enumeration')).toBeVisible(); expect(screen.getByText('4 shown · 100 observed')).toBeVisible(); expect(screen.getByText(/Endpoints omitted/)).toBeVisible(); Object.assign(v.network, { quality: 'partial', countExact: false }); fireEvent.click(screen.getByRole('button', { name: 'Refresh Windows inventory' })); await screen.findByText('4 shown · at least 100 observed'); expect(screen.getByText('Partial enumeration')).toBeVisible(); });
    it('distinguishes successful empty within scope', async () => { const v = view(); Object.assign(v.network, { rows: [], observedCount: 0 }); vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await flush(); fireEvent.click(screen.getByRole('tab', { name: 'Network' })); expect(screen.getByText(/No endpoints returned by the caller-visible tables/)).toBeVisible(); expect(screen.getByText('0 shown · 0 observed')).toBeVisible(); });
    it('uses German labels and preserves keyboard access to Interfaces and Storage', async () => { setLocale('de', false); render(<Harness/>); await flush(); fireEvent.keyDown(screen.getByRole('tab', { name: 'Schnittstellen' }), { key: 'ArrowRight' }); expect(screen.getByRole('tab', { name: 'Netzwerk' })).toHaveFocus(); expect(screen.getByText('Besitzende PID laut API')).toBeVisible(); expect(screen.getByText('Lokaler Endpunkt')).toBeVisible(); expect(screen.getAllByText('Nicht anwendbar')).toHaveLength(5); fireEvent.keyDown(screen.getByRole('tab', { name: 'Netzwerk' }), { key: 'ArrowRight' }); expect(screen.getByRole('tab', { name: 'Speicher' })).toHaveFocus(); });
    it('marks an old network capture stale without refreshing its timestamp', async () => { const v = view(); v.network.collectedAt = '2026-10-07T11:55:00Z'; v.snapshot!.collectedAt = v.network.collectedAt; v.status = 'stale'; vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await network(); expect(screen.getByText('Stale observation')).toBeVisible(); expect(screen.getByText(/Stale network observation/)).toBeVisible(); });
    it('does not mark fresh network stale only because the base capture is stale', async () => { const v = view(); v.snapshot!.collectedAt = '2026-10-07T11:55:00Z'; v.status = 'stale'; vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await network(); expect(screen.getByText('Stale observation')).toBeVisible(); expect(screen.queryByText(/Stale network observation/)).toBeNull(); });
    it('marks capture stale only after the original two-minute boundary', async () => { vi.useFakeTimers(); vi.setSystemTime(windowsNow); const v = view(); v.network.collectedAt = '2026-10-07T11:58:10Z'; v.snapshot!.collectedAt = '2026-10-07T11:58:09Z'; v.status = 'stale'; vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await flush(); fireEvent.click(screen.getByRole('tab', { name: 'Network' })); expect(screen.queryByText(/Stale network observation/)).toBeNull(); await act(async () => vi.advanceTimersByTimeAsync(1000)); expect(screen.getByText(/Stale network observation/)).toBeVisible(); });
    it('keeps manager receipt age independent from a younger network capture', async () => { const v = view(); v.receivedAt = '2026-10-07T11:57:51Z'; v.snapshot!.collectedAt = '2026-10-07T11:58:11Z'; v.network.collectedAt = v.snapshot!.collectedAt; v.status = 'stale'; vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await network(); expect(screen.getByText(/Stale network observation/)).toBeVisible(); });
    it('hides network when its base view expires without mislabeling younger endpoints as expired', async () => { vi.useFakeTimers(); vi.setSystemTime(windowsNow); const v = view(); v.snapshot!.collectedAt = '2026-10-06T12:00:11Z'; v.status = 'stale'; vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await flush(); fireEvent.click(screen.getByRole('tab', { name: 'Network' })); expect(screen.getByText('[2001:db8::80]:443')).toBeVisible(); await act(async () => vi.advanceTimersByTimeAsync(1000)); expect(screen.queryByRole('table')).toBeNull(); expect(screen.queryByText(/network snapshot expired/)).toBeNull(); expect(screen.getByText(/No current network snapshot is available/)).toBeVisible(); });
    it('expires network at 24h within the base privacy envelope, hiding younger siblings too', async () => {
        vi.useFakeTimers(); vi.setSystemTime(windowsNow); const v = { ...view(), volumes: windowsVolumes() }; v.network.collectedAt = '2026-10-06T12:00:11Z'; v.snapshot!.collectedAt = v.network.collectedAt; v.status = 'stale'; vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await flush(); fireEvent.click(screen.getByRole('tab', { name: 'Network' })); expect(screen.getByText('[2001:db8::80]:443')).toBeVisible(); await act(async () => vi.advanceTimersByTimeAsync(1000)); expect(screen.queryByText('[2001:db8::80]:443')).toBeNull(); expect(screen.getByText(/network snapshot expired/)).toBeVisible(); fireEvent.click(screen.getByRole('tab', { name: 'Storage' })); expect(screen.queryByText('Enumeration complete within scope')).toBeNull(); expect(screen.queryByRole('table')).toBeNull(); fireEvent.click(screen.getByRole('tab', { name: 'Processes' })); expect(screen.queryByText('fixture.exe')).toBeNull();
    });
    it('keeps younger network when a sibling volume snapshot expires', async () => {
        vi.useFakeTimers(); vi.setSystemTime(windowsNow); const v = { ...view(), volumes: windowsVolumes() }; v.volumes.collectedAt = '2026-10-06T12:00:11Z'; vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await flush(); fireEvent.click(screen.getByRole('tab', { name: 'Network' })); await act(async () => vi.advanceTimersByTimeAsync(1000)); expect(screen.getByText('[2001:db8::80]:443')).toBeVisible(); expect(screen.queryByText(/Stale network observation/)).toBeNull();
    });
    it.each(['blur', 'pagehide', 'hashchange', AUTH_REQUIRED_EVENT])('clears every endpoint on %s', async event => { render(<Harness/>); await network(); act(() => window.dispatchEvent(new Event(event))); expect(screen.queryByText('[2001:db8::80]:443')).toBeNull(); expect(screen.queryByRole('table')).toBeNull(); });
    it('clears hidden-page data and skips protected reads while disabled or hidden', async () => {
        const result = render(<Harness/>); await network(); vi.spyOn(document, 'visibilityState', 'get').mockReturnValue('hidden'); act(() => document.dispatchEvent(new Event('visibilitychange'))); expect(screen.queryByRole('table')).toBeNull(); result.unmount(); vi.mocked(request).mockClear(); render(<Harness/>); await flush(); expect(request).not.toHaveBeenCalled(); cleanup(); vi.restoreAllMocks(); render(<Harness enabled={false}/>); await flush(); expect(request).not.toHaveBeenCalled();
    });
    it('aborts device/session replacement and discards late responses', async () => {
        let resolve!: (v: ReturnType<typeof view>) => void; const result = render(<Harness/>); await network(); vi.mocked(request).mockReturnValueOnce(new Promise(done => { resolve = done; })); fireEvent.click(screen.getByRole('button', { name: 'Refresh Windows inventory' })); const signal = vi.mocked(request).mock.calls.at(-1)![1]?.signal;
        const next = windowsView(), id = `agent_${'8'.repeat(32)}`; next.deviceId = id; vi.mocked(request).mockResolvedValue(next); result.rerender(<Harness id={id} session="new"/>); await act(async () => resolve(view())); expect(signal?.aborted).toBe(true); expect(screen.queryByText('[2001:db8::80]:443')).toBeNull();
    });
    it('never revives endpoints after request timeout', async () => {
        vi.useFakeTimers(); vi.setSystemTime(windowsNow); let resolve!: (v: ReturnType<typeof view>) => void; render(<Harness/>); await flush(); fireEvent.click(screen.getByRole('tab', { name: 'Network' })); vi.mocked(request).mockReturnValue(new Promise(done => { resolve = done; })); fireEvent.click(screen.getByRole('button', { name: 'Refresh Windows inventory' })); expect(screen.queryByRole('table')).toBeNull(); await act(async () => vi.advanceTimersByTimeAsync(10001)); expect(screen.getByRole('alert')).toHaveTextContent('timed out'); await act(async () => resolve(view())); expect(screen.queryByRole('table')).toBeNull();
    });
    it('rejects frozen manager replies instead of renewing capture age', async () => { vi.useFakeTimers(); vi.setSystemTime(windowsNow); render(<Harness/>); await flush(); fireEvent.click(screen.getByRole('tab', { name: 'Network' })); await act(async () => vi.advanceTimersByTimeAsync(15000)); expect(screen.queryByRole('table')).toBeNull(); expect(screen.getByRole('alert')).toHaveTextContent('time reference changed'); });
    it('clears endpoints after an untrusted browser clock change', async () => { vi.useFakeTimers(); vi.setSystemTime(windowsNow); render(<Harness/>); await flush(); fireEvent.click(screen.getByRole('tab', { name: 'Network' })); vi.setSystemTime('2026-10-07T11:00:00Z'); await act(async () => vi.advanceTimersByTimeAsync(1000)); expect(screen.queryByRole('table')).toBeNull(); expect(screen.getByRole('alert')).toHaveTextContent('time reference changed'); });
    it('hides unknown raw server fields and failures', async () => { vi.mocked(request).mockResolvedValue({ ...view(), network: { ...windowsNetwork(), private: 'private-raw-secret' } }); render(<Harness/>); await screen.findByRole('alert'); expect(document.body).not.toHaveTextContent('private-raw-secret'); expect(screen.queryByText('[2001:db8::80]:443')).toBeNull(); vi.mocked(request).mockRejectedValue(new APIError('private-raw-secret')); fireEvent.click(screen.getByRole('button', { name: 'Refresh Windows inventory' })); await flush(); expect(screen.getByRole('alert')).toHaveTextContent('unavailable'); expect(document.body).not.toHaveTextContent('private-raw-secret'); });
    it.each(['revoked', 'unavailable', 'awaiting', 'not_configured'] as const)('hides endpoint data for manager status %s', async status => { render(<Harness/>); await network(); vi.mocked(request).mockResolvedValue({ ...windowsView(), status, snapshot: null, ...(['awaiting', 'not_configured'].includes(status) ? { sequence: null, receivedAt: null } : {}) }); fireEvent.click(screen.getByRole('button', { name: 'Refresh Windows inventory' })); await flush(); expect(screen.queryByRole('table')).toBeNull(); expect(screen.queryByText('[2001:db8::80]:443')).toBeNull(); });
});
