import { fullDate } from './utils';
import type { WindowsInventoryResource } from './windows-inventory-resource';
import type { WindowsProcessMetric } from './windows-process-metrics-types';
export const processMetricsCopy = {
    en: { cpu: 'CPU (% of one logical processor)', ram: 'Working-set RAM (bytes)', missing: 'Process CPU and RAM are unavailable. Separate local consent is required; absent data does not establish zero usage.', note: 'CPU is a percentage of one logical processor and may exceed 100%. RAM is the working set in bytes, not private or committed memory. Values are matched only within this inventory generation.', stale: 'Stale process metrics. These values describe the original capture, not current usage.', captured: 'Process metrics captured', received: 'Accepted by manager', shown: 'shown', observed: 'observed within bounded scope', truncated: 'Process metric rows omitted by collection or transfer limits.', unavailable: 'Unavailable', denied: 'Access denied', 'first-sample': 'First sample; waiting for CPU interval', reset: 'CPU interval reset; waiting for next sample' },
    de: { cpu: 'CPU (% eines logischen Prozessors)', ram: 'RAM-Arbeitssatz (Bytes)', missing: 'Prozess-CPU und RAM sind nicht verfügbar. Separate lokale Zustimmung ist erforderlich; fehlende Daten belegen keinen Nullverbrauch.', note: 'CPU ist der Prozentanteil eines logischen Prozessors und kann 100 % überschreiten. RAM ist der Arbeitssatz in Bytes, nicht privater oder zugesicherter Speicher. Werte werden nur innerhalb dieser Inventargeneration zugeordnet.', stale: 'Veraltete Prozessmesswerte. Diese Werte beschreiben die ursprüngliche Erfassung, nicht den aktuellen Verbrauch.', captured: 'Prozessmesswerte erfasst', received: 'Vom Manager akzeptiert', shown: 'angezeigt', observed: 'im begrenzten Umfang beobachtet', truncated: 'Prozessmesszeilen durch Erfassungs- oder Übertragungsgrenzen ausgelassen.', unavailable: 'Nicht verfügbar', denied: 'Zugriff verweigert', 'first-sample': 'Erste Messung; CPU-Intervall ausstehend', reset: 'CPU-Intervall zurückgesetzt; nächste Messung ausstehend' },
};
export function processMetricCells(row: WindowsProcessMetric | undefined, locale: 'en' | 'de'): string[] {
    const c = processMetricsCopy[locale];
    return [row?.cpuQuality === 'observed' && row.cpuPercent !== null ? `${row.cpuPercent.toLocaleString(locale, { maximumSignificantDigits: 15 })} %` : c[row?.cpuQuality && row.cpuQuality !== 'observed' ? row.cpuQuality : 'unavailable'], row?.memoryQuality === 'observed' && row.memoryBytes !== null ? BigInt(row.memoryBytes).toLocaleString(locale) : c[row?.memoryQuality && row.memoryQuality !== 'observed' ? row.memoryQuality : 'unavailable']];
}
export function WindowsProcessMetricsNote({ resource, locale }: { resource: WindowsInventoryResource; locale: 'en' | 'de' }) {
    const c = processMetricsCopy[locale], metrics = resource.processMetrics;
    if (!metrics) return <p className="windows-inventory-caution">{c.missing}</p>;
    return <div className="windows-process-metrics-note"><p>{c.note}</p><p className="windows-inventory-count">{metrics.rows.length} {c.shown} · {metrics.observedCount} {c.observed}</p>{metrics.truncated && <p className="windows-inventory-caution">{c.truncated}</p>}<div className="windows-inventory-times"><span>{c.captured} <time dateTime={metrics.collectedAt}>{fullDate(metrics.collectedAt)}</time></span>{resource.view?.receivedAt && <span>{c.received} <time dateTime={resource.view.receivedAt}>{fullDate(resource.view.receivedAt)}</time></span>}</div>{resource.processMetricsStale && <p className="windows-inventory-caution">{c.stale}</p>}</div>;
}
