import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { abortProtectedRequests, APIError, AUTH_REQUIRED_EVENT, mutate, request } from './api';
import { useOperator } from './auth';
import { DeviceDetail } from './details';
import { setLocale } from './i18n';
import type { Device } from './types';
import { WindowsHealthSummary, windowsHealthSummary } from './windows-health';
import { useWindowsInventory } from './windows-inventory-resource';
import type { WindowsInventoryResource } from './windows-inventory-resource';
import { windowsDevice as fixtureWindowsDevice, windowsDeviceId, windowsNow, windowsView } from './windows-inventory-fixture';
import type { WindowsInventoryView } from './windows-inventory-types';

vi.mock('./api', async original => ({ ...await original<typeof import('./api')>(), request: vi.fn(), mutate: vi.fn() }));
vi.mock('./auth', async original => ({ ...await original<typeof import('./auth')>(), useOperator: vi.fn() }));
function windowsDevice(): Device { return { ...fixtureWindowsDevice(), capabilities: [{ id: 'agent_identity', name: 'Enrolled agent identity', status: 'supported', detail: 'Synthetic activated identity fixture' }] }; }
const operator = { mode: 'lan' as const, authenticated: true, expiresAt: '2026-10-07T13:00:00Z', insecureTestMode: false, logout: vi.fn(), theme: 'light' as const, setTheme: vi.fn() };
function resource(view = windowsView()): WindowsInventoryResource { return { elapsedMS: 0, view, snapshot: view.snapshot, status: view.status, loading: false, error: null, refresh: vi.fn(), events: null, eventsStale: false, volumes: null, volumesStale: false, processMetrics: null, processMetricsStale: false, network: null, networkStale: false, networkExpired: false }; }
const summary = (device = windowsDevice(), r = resource(), elapsed = 0, ready = true) => windowsHealthSummary(device, r, elapsed, ready);
function Harness({ device = windowsDevice(), session = 'fixture' }: { device?: Device; session?: string }) { const r = useWindowsInventory(device.id, true, session); return <><button onClick={r.refresh}>Refresh fixture</button><WindowsHealthSummary device={device} resource={r} sessionKey={session} metadataReady onOpenStorage={vi.fn()}/></>; }
const flush = () => act(async () => {});
const diskCard = () => within(screen.getByRole('region', { name: 'System volume' }));
beforeEach(() => { abortProtectedRequests(); setLocale('en', false); vi.mocked(request).mockReset().mockResolvedValue(windowsView()); vi.mocked(mutate).mockReset(); vi.mocked(useOperator).mockReturnValue(operator); });
afterEach(() => { cleanup(); abortProtectedRequests(); vi.useRealTimers(); vi.restoreAllMocks(); });

describe('Windows health read adapter', () => {
    it('reports receipt contact and neutral system-volume usage without thresholds', () => { const v = summary(); expect(v.contact).toBe('recent'); expect(v.receivedAt).toBe('2026-10-07T12:00:01Z'); expect(v.disk).toMatchObject({ state: 'current', value: 61, at: '2026-10-07T12:00:00Z' }); const d = windowsDevice(); d.disk.value = 99; expect(summary(d).disk).toMatchObject({ state: 'current', value: 99 }); });
    it('uses receipt age even when the inventory capture is stale or partial', () => { const v = windowsView(); v.status = 'stale'; v.snapshot!.collectedAt = '2026-10-07T11:55:00Z'; v.snapshot!.services = { ...v.snapshot!.services, quality: 'partial', complete: false, countExact: false }; const s = summary(windowsDevice(), resource(v)); expect(s.contact).toBe('recent'); expect(s.disk.state).toBe('current'); });
    it('never treats rereading an old accepted receipt as recent contact', () => { const v = windowsView(); v.receivedAt = '2026-10-07T11:57:00Z'; v.snapshot!.collectedAt = '2026-10-07T11:56:59Z'; v.status = 'stale'; expect(summary(windowsDevice(), resource(v)).contact).toBe('stale'); });
    it('uses strict nanosecond-aware receipt and metric boundaries', () => {
        const v = windowsView(); v.serverNow = '2026-10-07T12:02:01Z'; v.status = 'stale'; const d = windowsDevice(); d.agentCertificate!.checkedAt = v.serverNow; d.disk.collectedAt = '2026-10-07T12:00:01Z'; d.lastSeen = d.disk.collectedAt;
        expect(summary(d, resource(v))).toMatchObject({ contact: 'recent', disk: { state: 'current' } });
        v.serverNow = '2026-10-07T12:02:01.000000001Z'; d.agentCertificate!.checkedAt = v.serverNow; expect(summary(d, resource(v))).toMatchObject({ contact: 'stale', disk: { state: 'stale', value: null } });
    });
    it.each(['unknown', 'denied', 'stale', 'partial'] as const)('never upgrades %s quality', quality => { const d = windowsDevice(); Object.assign(d.disk, { quality }); expect(summary(d).disk).toMatchObject({ value: null, state: quality === 'partial' || quality === 'unknown' ? 'missing' : quality }); });
    it.each([null, NaN, Infinity, -1, 100.1, '61'])('withholds invalid or missing metric value %s', value => { const d = windowsDevice(); Object.assign(d.disk, { value }); expect(summary(d).disk).toMatchObject({ value: null, state: 'missing' }); });
    it.each(['bad', '2026-02-30T12:00:00Z', '2026-10-07T12:00:10.000000001Z'])('withholds malformed or future original capture %s', at => { const d = windowsDevice(); d.disk.collectedAt = at; expect(summary(d).disk.value).toBeNull(); expect(summary(d, resource(), 1000).disk.value).toBeNull(); });
    it('does not borrow another report, resource quality or percentage unit for disk', () => { const d = windowsDevice(); d.disk.collectedAt = '2026-10-07T11:57:00Z'; expect(summary(d).disk.state).toBe('stale'); d.disk.collectedAt = '2026-10-07T12:00:01Z'; expect(summary(d).disk.state).toBe('missing'); d.disk.collectedAt = d.lastSeen; d.disk.unit = 'bytes'; expect(summary(d).disk.state).toBe('missing'); });
    it.each(['platform', 'source', 'synthetic', 'id', 'certificate', 'identity'] as const)('fails closed on mismatched %s authority', field => { const d = windowsDevice(); if (field === 'platform') d.platform = 'linux'; if (field === 'source') d.source = 'synthetic'; if (field === 'synthetic') d.synthetic = true; if (field === 'id') d.id = `agent_${'8'.repeat(32)}`; if (field === 'certificate') delete d.agentCertificate; if (field === 'identity') d.capabilities[0].status = 'denied'; expect(summary(d)).toMatchObject({ contact: 'unknown', disk: { value: null } }); });
    it('requires exact current identity capability and the Windows inventory profile', () => { const d = windowsDevice(); d.capabilities = []; expect(summary(d).contact).toBe('unknown'); d.capabilities = [...windowsDevice().capabilities, ...windowsDevice().capabilities]; expect(summary(d).disk.value).toBeNull(); const r = resource(); Object.assign(r.view!, { collectionProfile: 'managed-operations-v3' }); expect(summary(windowsDevice(), r).disk.value).toBeNull(); });
    it.each(['revoked', 'awaiting', 'not_configured', 'unavailable'] as const)('hides values for %s inventory authority', status => { const r = resource(); r.status = status; r.snapshot = null; expect(summary(windowsDevice(), r)).toMatchObject({ contact: 'unknown', disk: { value: null, at: null, source: null } }); });
    it('withholds at certificate expiry, including elapsed time and nanoseconds', () => { const d = windowsDevice(); d.agentCertificate!.expiresAt = '2026-10-07T12:00:11Z'; expect(summary(d, resource(), 999).disk.value).toBe(61); expect(summary(d, resource(), 1000).disk.value).toBeNull(); d.agentCertificate!.expiresAt = windowsNow; expect(summary(d).contact).toBe('unknown'); const r = resource(); r.view!.serverNow = '2026-10-07T12:00:10.000000001Z'; expect(summary(d, r).disk.value).toBeNull(); });
    it('withholds invalid, missing or old certificate check provenance', () => { for (const at of ['bad', '2026-10-07T11:57:00Z', '2026-10-07T12:00:11Z']) { const d = windowsDevice(); d.agentCertificate!.checkedAt = at; expect(summary(d).disk.value).toBeNull(); } const d = windowsDevice(); d.agentCertificate!.expiresAt = null; expect(summary(d).contact).toBe('unknown'); });
    it('clears on inventory failure/loading and suppresses disk on metadata failure/loading', () => { for (const r of [{ ...resource(), error: 'unavailable' as const }, { ...resource(), loading: true }]) expect(summary(windowsDevice(), r)).toMatchObject({ contact: 'unknown', disk: { value: null } }); expect(summary(windowsDevice(), resource(), 0, false)).toMatchObject({ contact: 'recent', disk: { value: null, at: null, source: null } }); });
    it('rejects unreliable elapsed time', () => { for (const age of [NaN, Infinity, -1]) expect(summary(windowsDevice(), resource(), age)).toMatchObject({ contact: 'unknown', disk: { value: null } }); });
});

describe('Windows Health summary lifecycle and navigation', () => {
    it.each(['en', 'de'] as const)('keeps scope, original times, neutral values and storage action accessible in %s', async locale => { setLocale(locale, false); const open = vi.fn(); render(<WindowsHealthSummary device={windowsDevice()} resource={resource()} sessionKey="fixture" metadataReady onOpenStorage={open}/>); await flush(); expect(screen.getByText(locale === 'en' ? '61.0 %' : '61,0 %')).toBeVisible(); expect(screen.getByText(locale === 'en' ? 'Recent report' : 'Aktuelle Meldung')).toBeVisible(); expect(document.querySelector('time[datetime="2026-10-07T12:00:01Z"]')).not.toBeNull(); fireEvent.click(screen.getByText(locale === 'en' ? 'Sources & assessment limits' : 'Quellen & Bewertungsgrenzen')); expect(screen.getByText(/quota-aware|kontingentabhängige/)).toBeVisible(); fireEvent.click(screen.getByRole('button', { name: locale === 'en' ? 'Inspect storage' : 'Speicher ansehen' })); expect(open).toHaveBeenCalledOnce(); expect(document.body.textContent).not.toMatch(/Within threshold|No open alerts|healthy|Offline|Root disk/i); });
    it('expires a near-boundary disk sample using request-start delay', async () => { vi.useFakeTimers(); vi.setSystemTime(windowsNow); const d = windowsDevice(); d.disk.collectedAt = '2026-10-07T11:58:11Z'; let finish!: (v: WindowsInventoryView) => void; vi.mocked(request).mockReturnValueOnce(new Promise(resolve => { finish = resolve; })); render(<Harness device={d}/>); await flush(); await act(async () => vi.advanceTimersByTimeAsync(2000)); await act(async () => finish(windowsView())); expect(diskCard().getByText('Stale reading')).toBeVisible(); expect(screen.queryByText('61.0 %')).toBeNull(); });
    it.each([0, 1])('does not renew frozen or slowly advancing time after remount (%i ms)', async advance => { vi.useFakeTimers(); vi.setSystemTime(windowsNow); const d = windowsDevice(); d.disk.collectedAt = '2026-10-07T11:58:11Z'; const first = render(<Harness device={d}/>); await flush(); expect(screen.getByText('61.0 %')).toBeVisible(); first.unmount(); await act(async () => vi.advanceTimersByTimeAsync(2000)); const next = windowsView(); next.serverNow = new Date(Date.parse(windowsNow) + advance).toISOString(); vi.mocked(request).mockResolvedValue(next); render(<Harness device={d}/>); await flush(); expect(diskCard().getByText('Stale reading')).toBeVisible(); expect(screen.queryByText('61.0 %')).toBeNull(); });
    it('retains elapsed floor through loading/failure and rejects manager rollback', async () => { vi.useFakeTimers(); vi.setSystemTime(windowsNow); const first = render(<Harness/>); await flush(); vi.mocked(request).mockRejectedValueOnce(new APIError('private failure')); fireEvent.click(screen.getByText('Refresh fixture')); await flush(); expect(screen.queryByText('61.0 %')).toBeNull(); first.unmount(); const older = windowsView(); older.serverNow = '2026-10-07T12:00:09Z'; vi.mocked(request).mockResolvedValue(older); render(<Harness/>); await flush(); expect(screen.getByText('Observation age could not be verified. Readings are hidden.')).toBeVisible(); expect(screen.queryByText('61.0 %')).toBeNull(); expect(document.body).not.toHaveTextContent('private failure'); });
    it('clears on session loss, blur and failed refresh; ignores late replies', async () => { render(<Harness/>); await screen.findByText('61.0 %'); let finish!: (v: WindowsInventoryView) => void; vi.mocked(request).mockReturnValueOnce(new Promise(resolve => { finish = resolve; })); fireEvent.click(screen.getByText('Refresh fixture')); expect(screen.queryByText('61.0 %')).toBeNull(); act(() => window.dispatchEvent(new Event('blur'))); await act(async () => finish(windowsView())); expect(screen.queryByText('61.0 %')).toBeNull(); act(() => window.dispatchEvent(new Event('focus'))); await screen.findByText('61.0 %'); act(() => window.dispatchEvent(new Event(AUTH_REQUIRED_EVENT))); expect(screen.queryByText('61.0 %')).toBeNull(); expect(screen.queryByText('Recent report')).toBeNull(); });
    it('withholds when the browser clock becomes unreliable', async () => { vi.useFakeTimers(); vi.setSystemTime(windowsNow); render(<Harness/>); await flush(); vi.setSystemTime('2026-10-07T11:00:00Z'); await act(async () => vi.advanceTimersByTimeAsync(1000)); expect(screen.queryByText('61.0 %')).toBeNull(); expect(screen.queryByText('Recent report')).toBeNull(); });
    it('opens the existing Storage tab without a new read, grants, mutation or Linux health call', async () => { vi.mocked(request).mockImplementation(async path => path === `/devices/${windowsDeviceId}` ? windowsDevice() : path.endsWith('/windows-inventory') ? windowsView() : Promise.reject(new Error('Unexpected fixture request'))); render(<DeviceDetail id={windowsDeviceId} initialTab="health" onClose={vi.fn()} onCase={vi.fn()}/>); await screen.findByText('61.0 %'); expect(screen.getByRole('tab', { name: 'Health' })).toBeVisible(); expect(screen.queryByRole('tab', { name: 'Health & history' })).toBeNull(); fireEvent.click(screen.getByRole('button', { name: 'Inspect storage' })); expect(screen.getByRole('tab', { name: 'Inventory' })).toHaveFocus(); expect(screen.getByRole('tab', { name: 'Storage' })).toHaveAttribute('aria-selected', 'true'); expect(screen.getByText(/Separate local consent is required/)).toBeVisible(); expect(vi.mocked(request).mock.calls.every(([path]) => path === `/devices/${windowsDeviceId}` || path === `/devices/${windowsDeviceId}/windows-inventory`)).toBe(true); expect(mutate).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('tab', { name: 'Health' })); fireEvent.click(screen.getByRole('tab', { name: 'Inventory' })); expect(screen.getByRole('tab', { name: 'Processes' })).toHaveAttribute('aria-selected', 'true'); });
});
