import { inventoryAge } from './complete-packages-types';
export const WINDOWS_PROCESS_METRICS_BYTES = 12 * 1024;
export interface WindowsProcessMetric { pid: number; cpuPercent: number | null; cpuQuality: 'observed' | 'first-sample' | 'reset' | 'denied' | 'unavailable'; memoryBytes: string | null; memoryQuality: 'observed' | 'denied' | 'unavailable' }
export interface WindowsProcessMetrics { schemaVersion: 'tracebolt.windows-process-metrics.v1'; scope: 'windows-process-metrics-v1'; grantId: string; generationId: string; collectedAt: string; observedCount: number; truncated: boolean; rows: WindowsProcessMetric[] }
const exact = (v: unknown, keys: string[]): v is Record<string, unknown> => v !== null && typeof v === 'object' && !Array.isArray(v) && Object.keys(v).length === keys.length && keys.every(k => Object.hasOwn(v, k));
function row(v: unknown): v is WindowsProcessMetric {
    if (!exact(v, ['pid', 'cpuPercent', 'cpuQuality', 'memoryBytes', 'memoryQuality']) || typeof v.pid !== 'number' || !Number.isInteger(v.pid) || Object.is(v.pid, -0) || v.pid < 0 || v.pid > 4294967295) return false;
    const cpu = v.cpuQuality === 'observed' ? typeof v.cpuPercent === 'number' && Number.isFinite(v.cpuPercent) && !Object.is(v.cpuPercent, -0) && v.cpuPercent >= 0 && v.cpuPercent <= 429496729500 : typeof v.cpuQuality === 'string' && ['first-sample', 'reset', 'denied', 'unavailable'].includes(v.cpuQuality) && v.cpuPercent === null;
    const memory = v.memoryQuality === 'observed' ? typeof v.memoryBytes === 'string' && /^(0|[1-9]\d{0,19})$/.test(v.memoryBytes) && BigInt(v.memoryBytes) <= 18446744073709551615n : typeof v.memoryQuality === 'string' && ['denied', 'unavailable'].includes(v.memoryQuality) && v.memoryBytes === null;
    return cpu && memory;
}
export function validWindowsProcessMetrics(v: unknown, generation: string, serverNow: string): v is WindowsProcessMetrics {
    if (!exact(v, ['schemaVersion', 'scope', 'grantId', 'generationId', 'collectedAt', 'observedCount', 'truncated', 'rows']) || v.schemaVersion !== 'tracebolt.windows-process-metrics.v1' || v.scope !== 'windows-process-metrics-v1' || typeof v.grantId !== 'string' || !/^[a-f0-9]{32}$/.test(v.grantId) || typeof v.generationId !== 'string' || !/^sample_[a-f0-9]{32}$/.test(v.generationId) || v.generationId !== generation || typeof v.collectedAt !== 'string' || !/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d{1,9})?Z$/.test(v.collectedAt) || Number(v.collectedAt.slice(0,4)) < 1970 || !Number.isFinite(Date.parse(v.collectedAt)) || new Date(Date.parse(v.collectedAt)).toISOString().slice(0,19) !== v.collectedAt.slice(0,19) || !Number.isFinite(Date.parse(serverNow)) || inventoryAge(v.collectedAt, serverNow) > 30000 || inventoryAge(serverNow, v.collectedAt) >= 86400000 || typeof v.observedCount !== 'number' || !Number.isInteger(v.observedCount) || Object.is(v.observedCount, -0) || v.observedCount < 0 || v.observedCount > 128 || typeof v.truncated !== 'boolean' || !Array.isArray(v.rows) || v.rows.length > 128 || !v.rows.every(row) || new Set(v.rows.map(r => r.pid)).size !== v.rows.length || v.observedCount < v.rows.length || v.truncated !== (v.observedCount > v.rows.length) || v.rows.some((r, i) => i > 0 && r.pid <= (v.rows as WindowsProcessMetric[])[i - 1].pid)) return false;
    return new TextEncoder().encode(JSON.stringify(v)).byteLength <= WINDOWS_PROCESS_METRICS_BYTES;
}
