import wireFixture from '../../tests/fixtures/windows-contact-view.json';
import { describe, expect, it } from 'vitest';
import { windowsContactDevice, windowsContactView } from './windows-contact-fixture';
import { validWindowsContactView, windowsContactDeviceEligible, windowsContactStatus } from './windows-contact-types';
import { windowsDeviceId } from './windows-inventory-fixture';
describe('invented accepted-contact view contract', () => {
    it.each(Object.entries(wireFixture))('accepts Go evaluator-produced %s wire fixture', (_name, value) => { expect(validWindowsContactView(value, value.deviceId)).toBe(true); });
    it.each(['recent', 'pending', 'overdue', 'unknown'] as const)('accepts bounded manager-only %s state with distinct receipt and evaluation', status => { const value = windowsContactView(status); expect(validWindowsContactView(value, windowsDeviceId)).toBe(true); });
    it('supports no accepted report only as unknown with zero sequence', () => { const value = windowsContactView('unknown'); value.lastAcceptedAt = null; value.sequence = 0; value.evaluatedAt = null; value.incidents = []; expect(validWindowsContactView(value, windowsDeviceId)).toBe(true); value.status = 'recent'; expect(validWindowsContactView(value, windowsDeviceId)).toBe(false); });
    it('allows a new accepted tuple awaiting independent evaluation', () => { const value = windowsContactView('unknown'); value.evaluatedAt = '2026-10-07T11:59:50Z'; expect(validWindowsContactView(value, windowsDeviceId)).toBe(true); });
    it.each(['deviceId', 'certificateExpiresAt', 'lastAcceptedAt', 'evaluatedAt', 'sequence', 'incidents', 'extra'] as const)('rejects malformed %s without presenting history', field => { const value = windowsContactView(); Object.assign(value, { [field]: field === 'sequence' ? Number.MAX_SAFE_INTEGER + 1 : field === 'incidents' ? Array(101).fill(value.incidents[0]) : 'private-fixture' }); expect(validWindowsContactView(value, windowsDeviceId)).toBe(false); });
    it('rejects impossible dates, nanosecond future timestamps and expiry at boundary', () => { for (const patch of [{ lastAcceptedAt: '2026-02-30T12:00:00Z' }, { evaluatedAt: '2026-10-07T12:00:10.000000001Z' }, { certificateExpiresAt: '2026-10-07T12:00:10Z' }, { certificateExpiresAt: null }]) expect(validWindowsContactView({ ...windowsContactView(), ...patch }, windowsDeviceId)).toBe(false); });
    it('rejects malformed, duplicated and inconsistent incident lifecycles', () => { for (const patch of [{ id: 'wcontact_private' }, { openedAt: '2026-10-07T11:52:00Z' }, { recoverySequence: 0 }, { resolvedAt: null }, { closedReason: 'acknowledged' }, { lastConfirmedAt: '2026-10-07T11:54:00Z' }, { nativePayload: 'private' }]) { const value = windowsContactView(); Object.assign(value.incidents[0], patch); expect(validWindowsContactView(value, windowsDeviceId)).toBe(false); } const value = windowsContactView(); value.incidents.push(value.incidents[0]); expect(validWindowsContactView(value, windowsDeviceId)).toBe(false); });
    it('rejects incident confirmation beyond its independent evaluation', () => { const value = windowsContactView('overdue'); value.evaluatedAt = '2026-10-07T12:00:09Z'; expect(validWindowsContactView(value, windowsDeviceId)).toBe(false); });
    it('does not claim a current open state without exactly one open incident', () => { const value = windowsContactView(); value.status = 'overdue'; expect(validWindowsContactView(value, windowsDeviceId)).toBe(false); });
    it('withholds current evaluation after 120s without deleting history or locally opening an incident', () => { const value = windowsContactView('pending'); expect(windowsContactStatus(value, 120000)).toBe('pending'); expect(windowsContactStatus(value, 120000.000001)).toBe('unknown'); expect(value.incidents).toHaveLength(1); });
    it('withholds recent contact when original receipt crosses 120s including nanoseconds', () => { const value = windowsContactView(); expect(windowsContactStatus(value, 111000)).toBe('recent'); expect(windowsContactStatus(value, 111000.000001)).toBe('unknown'); for (const elapsed of [-1, NaN, Infinity]) expect(windowsContactStatus(value, elapsed)).toBe('unknown'); });
    it.each(['platform', 'source', 'synthetic', 'identity', 'certificate', 'id'] as const)('requires current Windows guided authority: %s', field => { const device = windowsContactDevice(); if (field === 'platform') device.platform = 'linux'; if (field === 'source') device.source = 'synthetic'; if (field === 'synthetic') device.synthetic = true; if (field === 'identity') device.capabilities = []; if (field === 'certificate') delete device.agentCertificate; if (field === 'id') device.id = `agent_${'8'.repeat(32)}`; expect(windowsContactDeviceEligible(device, windowsDeviceId)).toBe(false); });
});
