import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { AUTH_REQUIRED_EVENT, request } from './api';
import { setLocale } from './i18n';
import { WindowsInventoryWorkspace } from './windows-inventory';
import { useWindowsInventory } from './windows-inventory-resource';
import { validWindowsInventoryView } from './windows-inventory-types';
import { windowsDeviceId, windowsNow, windowsView } from './windows-inventory-fixture';
import { windowsVolumes } from './windows-volumes-fixture';
import { validWindowsProcessMetrics, type WindowsProcessMetrics } from './windows-process-metrics-types';
vi.mock('./api', async original => ({ ...await original<typeof import('./api')>(), request: vi.fn() }));
function metrics(): WindowsProcessMetrics { return { schemaVersion: 'tracebolt.windows-process-metrics.v1', scope: 'windows-process-metrics-v1', grantId: 'e'.repeat(32), generationId: `sample_${'a'.repeat(32)}`, collectedAt: '2026-10-07T12:00:02Z', observedCount: 1, truncated: false, rows: [{ pid: 44, cpuPercent: 125.25, cpuQuality: 'observed', memoryBytes: '18446744073709551615', memoryQuality: 'observed' }] }; }
function view() { return { ...windowsView(), processMetrics: metrics() }; }
function Harness({ session = 'fixture' }: { session?: string }) { return <WindowsInventoryWorkspace resource={useWindowsInventory(windowsDeviceId, true, session)}/>; }
const flush = () => act(async () => {});
beforeEach(() => { setLocale('en', false); vi.mocked(request).mockReset().mockResolvedValue(view()); });
afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks(); });
describe('process metric contract', () => {
    it('accepts old views and new explicitly scoped metrics', () => { expect(validWindowsInventoryView(windowsView(), windowsDeviceId)).toBe(true); expect(validWindowsInventoryView(view(), windowsDeviceId)).toBe(true); });
    const mutations: [string, (v: WindowsProcessMetrics) => void][] = [
        ['unknown member', v => Object.assign(v, { secret: true })], ['unknown row member', v => Object.assign(v.rows[0], { name: 'extra.exe' })], ['wrong scope', v => Object.assign(v, { scope: 'windows-inventory-v1' })], ['bad grant', v => { v.grantId = 'E'.repeat(32); }], ['wrong generation', v => { v.generationId = `sample_${'b'.repeat(32)}`; }],
        ['non-string CPU quality', v => Object.assign(v.rows[0], { cpuQuality: ['denied'], cpuPercent: null })], ['non-string memory quality', v => Object.assign(v.rows[0], { memoryQuality: ['denied'], memoryBytes: null })], ['negative PID', v => { v.rows[0].pid = -1; }], ['large PID', v => { v.rows[0].pid = 4294967296; }], ['fractional PID', v => { v.rows[0].pid = 1.5; }], ['duplicate PID', v => { v.rows.push({ ...v.rows[0] }); v.observedCount++; }],
        ['negative zero CPU', v => { v.rows[0].cpuPercent = -0; }], ['negative CPU', v => { v.rows[0].cpuPercent = -1; }], ['unbounded CPU', v => { v.rows[0].cpuPercent = Infinity; }], ['NaN CPU', v => { v.rows[0].cpuPercent = NaN; }], ['CPU upper bound', v => { v.rows[0].cpuPercent = 429496729501; }], ['null observed CPU', v => { v.rows[0].cpuPercent = null; }], ['denied non-null CPU', v => { v.rows[0].cpuQuality = 'denied'; }], ['unknown CPU quality', v => Object.assign(v.rows[0], { cpuQuality: 'healthy' })],
        ['numeric memory', v => Object.assign(v.rows[0], { memoryBytes: 42 })], ['overflow memory', v => { v.rows[0].memoryBytes = '18446744073709551616'; }], ['leading-zero memory', v => { v.rows[0].memoryBytes = '01'; }], ['negative memory', v => { v.rows[0].memoryBytes = '-1'; }], ['null observed memory', v => { v.rows[0].memoryBytes = null; }], ['denied non-null memory', v => { v.rows[0].memoryQuality = 'denied'; }],
        ['count limit', v => { v.observedCount = 129; v.truncated = true; }], ['missing truncation', v => { v.observedCount++; }], ['invented truncation', v => { v.truncated = true; }], ['expired capture', v => { v.collectedAt = '2026-10-06T12:00:10Z'; }], ['future capture', v => { v.collectedAt = '2026-10-07T12:00:41Z'; }], ['invalid date', v => { v.collectedAt = '2026-02-30T12:00:00Z'; }],
    ];
    it.each(mutations)('rejects %s', (_label, mutate) => { const v = metrics(); mutate(v); expect(validWindowsProcessMetrics(v, metrics().generationId, windowsNow)).toBe(false); });
    it('requires ascending PID and bounded encoded size', () => { const v = metrics(); v.rows = Array.from({ length: 128 }, (_, pid) => ({ ...v.rows[0], pid })); v.observedCount = 128; expect(validWindowsProcessMetrics(v, v.generationId, windowsNow)).toBe(false); v.rows = [v.rows[1], v.rows[0]]; v.observedCount = 2; expect(validWindowsProcessMetrics(v, v.generationId, windowsNow)).toBe(false); });
    it('accepts explicit non-observations and actual zeros', () => { for (const quality of ['first-sample', 'reset', 'denied', 'unavailable'] as const) { const v = metrics(); Object.assign(v.rows[0], { cpuQuality: quality, cpuPercent: null, memoryQuality: 'denied', memoryBytes: null }); expect(validWindowsProcessMetrics(v, v.generationId, windowsNow)).toBe(true); } const v = metrics(); Object.assign(v.rows[0], { cpuPercent: 0, memoryBytes: '0' }); expect(validWindowsProcessMetrics(v, v.generationId, windowsNow)).toBe(true); });
    it('binds the requested count to this inventory generation', () => { const v = view(); v.processMetrics.observedCount = 2; v.processMetrics.truncated = true; expect(validWindowsProcessMetrics(v.processMetrics, v.snapshot!.generationId, windowsNow)).toBe(true); expect(validWindowsInventoryView(v, windowsDeviceId)).toBe(false); });
    it('preserves old base admission but rejects ambiguous metric joins', () => { const v = view(); v.snapshot!.processes.rows.push({ ...v.snapshot!.processes.rows[0] }); v.snapshot!.processes.observedCount++; expect(validWindowsInventoryView(v, windowsDeviceId)).toBe(false); const { processMetrics: _metrics, ...old } = v; expect(validWindowsInventoryView(old, windowsDeviceId)).toBe(true); });
    it('rejects null extension, foreign PID and data on revoked views', () => { expect(validWindowsInventoryView({ ...view(), processMetrics: null }, windowsDeviceId)).toBe(false); const v = view(); v.processMetrics.rows[0].pid = 99; expect(validWindowsInventoryView(v, windowsDeviceId)).toBe(false); expect(validWindowsInventoryView({ ...view(), status: 'revoked', snapshot: null }, windowsDeviceId)).toBe(false); });
});
describe('Processes CPU and working-set RAM', () => {
    it('renders >100% CPU and exact uint64 RAM with explicit semantics', async () => { render(<Harness/>); expect(await screen.findByText('125.25 %')).toBeVisible(); expect(screen.getByText('18,446,744,073,709,551,615')).toBeVisible(); expect(screen.getByRole('columnheader', { name: 'Working-set RAM (bytes)' })).toBeVisible(); expect(screen.getByText(/may exceed 100%/)).toBeVisible(); expect(document.querySelector('time[datetime="2026-10-07T12:00:02Z"]')).not.toBeNull(); });
    it('shows missing consent without inventing zeros', async () => { vi.mocked(request).mockResolvedValue(windowsView()); render(<Harness/>); expect(await screen.findByText(/Separate local consent is required/)).toBeVisible(); expect(screen.queryByText('0 %')).toBeNull(); });
    it.each([['first-sample', 'First sample; waiting for CPU interval'], ['reset', 'CPU interval reset; waiting for next sample'], ['denied', 'Access denied'], ['unavailable', 'Unavailable']] as const)('explains %s without successful zeros', async (quality, label) => { const v = view(); Object.assign(v.processMetrics.rows[0], { cpuPercent: null, cpuQuality: quality, memoryBytes: null, memoryQuality: 'denied' }); vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await flush(); expect(screen.getAllByText(label).length).toBeGreaterThan(0); expect(screen.queryByText('0 %')).toBeNull(); });
    it('supports German labels and numbers', async () => { setLocale('de', false); render(<Harness/>); expect(await screen.findByText('125,25 %')).toBeVisible(); expect(screen.getByRole('columnheader', { name: 'RAM-Arbeitssatz (Bytes)' })).toBeVisible(); });
    it('marks independently stale metrics and keeps fresh metrics independent of inventory age', async () => { const v = view(); v.processMetrics.collectedAt = '2026-10-07T11:55:00Z'; vi.mocked(request).mockResolvedValue(v); const ui = render(<Harness/>); await flush(); expect(screen.getByText(/Stale process metrics/)).toBeVisible(); ui.unmount(); v.processMetrics = metrics(); v.snapshot!.collectedAt = '2026-10-07T11:55:00Z'; v.status = 'stale'; vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await flush(); expect(screen.queryByText(/Stale process metrics/)).toBeNull(); });
    it.each(['blur', 'pagehide', 'hashchange', AUTH_REQUIRED_EVENT])('clears private values on %s', async event => { render(<Harness/>); await screen.findByText('125.25 %'); act(() => window.dispatchEvent(new Event(event))); expect(screen.queryByText('125.25 %')).toBeNull(); });
    it('clears on session replacement and ignores late interrupted response', async () => { let resolve!: (v: ReturnType<typeof view>) => void; const ui = render(<Harness/>); await screen.findByText('125.25 %'); vi.mocked(request).mockReturnValueOnce(new Promise(done => { resolve = done; })); fireEvent.click(screen.getByRole('button', { name: 'Refresh Windows inventory' })); vi.mocked(request).mockResolvedValue(windowsView()); ui.rerender(<Harness session="replacement"/>); await act(async () => resolve(view())); expect(screen.queryByText('125.25 %')).toBeNull(); });
    it('expires metrics independently without discarding younger volumes or inventory', async () => { vi.useFakeTimers(); vi.setSystemTime(windowsNow); const v = { ...view(), volumes: windowsVolumes() }; v.processMetrics.collectedAt = '2026-10-06T12:00:11Z'; vi.mocked(request).mockResolvedValue(v); render(<Harness/>); await flush(); expect(screen.getByText('125.25 %')).toBeVisible(); await act(async () => vi.advanceTimersByTimeAsync(1000)); expect(screen.queryByText('125.25 %')).toBeNull(); expect(screen.getByText('fixture.exe')).toBeVisible(); fireEvent.click(screen.getByRole('tab', { name: 'Storage' })); expect(screen.getByText('Enumeration complete within scope')).toBeVisible(); });
    it('does not refresh metrics age from a frozen response', async () => { vi.useFakeTimers(); vi.setSystemTime(windowsNow); render(<Harness/>); await flush(); await act(async () => vi.advanceTimersByTimeAsync(15000)); expect(screen.queryByText('125.25 %')).toBeNull(); expect(screen.getByRole('alert')).toHaveTextContent('time reference changed'); });
});
